version: "2"

run:
  timeout: 5m
  tests: true

output:
  show-stats: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    # --- Default & Critical ---
    - errcheck
    - govet
    - staticcheck
    - unused

    # --- Error Handling & Naming ---
    - errname # Enforces "Err" prefix and "Error" suffix
    - errorlint # Enforces Go 1.13+ error wrapping (%w)
    - nilerr # Finds code that returns nil even if checks fail

    # --- Database & Logging ---
    - sqlclosecheck # Prevents connection leaks (vital for SQLite)
    - rowserrcheck # Ensures rows.Err() is checked after iteration
    - sloglint # Ensures structured logging consistency
    - depguard # Enforces allowed/denied dependencies
    - decorder # Ensures correct order

    # --- Quality & Security ---
    - revive # General Go style
    - gosec # Security (SQL Injection, file permissions)
    - gocritic # Catches subtle bugs and performance issues
    - misspell # Fixes typos
    - nolintlint # Ensures //nolint comments are actually needed
    - testifylint # Ensures correct testify usage
    - noctx # Prevents zombie requests

  settings:
    sloglint:
      no-global: "all"
      key-naming-case: snake
      static-msg: true
      no-mixed-args: true

    testifylint:
      enable-all: true

    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/sirupsen/logrus"
              desc: "We use log/slog only."
            - pkg: "go.uber.org/zap"
              desc: "We use log/slog only."
            - pkg: "log$"
              desc: "Use log/slog. For fatal errors, return them or use os.Exit only in main."

        governance_domain:
          files:
            - "internal/domain/**/*.go"
          deny:
            - pkg: "duck-demo/internal/api"
              desc: "governance: domain imports must stay within domain"
            - pkg: "duck-demo/internal/service"
              desc: "governance: domain imports must stay within domain"
            - pkg: "duck-demo/internal/db"
              desc: "governance: domain imports must stay within domain"
            - pkg: "duck-demo/internal/engine"
              desc: "governance: domain imports must stay within domain"
            - pkg: "duck-demo/internal/middleware"
              desc: "governance: domain imports must stay within domain"
            - pkg: "duck-demo/internal/declarative"
              desc: "governance: domain imports must stay within domain"
            - pkg: "duck-demo/cmd"
              desc: "governance: domain must not import cmd packages"
            - pkg: "duck-demo/pkg/cli"
              desc: "governance: domain must not import cli delivery packages"

        governance_service:
          files:
            - "internal/service/**/*.go"
          deny:
            - pkg: "duck-demo/internal/api"
              desc: "governance: service imports must flow toward domain"
            - pkg: "duck-demo/internal/db"
              desc: "governance: service imports must flow toward domain"
            - pkg: "duck-demo/internal/engine"
              desc: "governance: service imports must flow toward domain"
            - pkg: "duck-demo/internal/middleware"
              desc: "governance: service imports must flow toward domain"
            - pkg: "duck-demo/cmd"
              desc: "governance: service must not import cmd packages"
            - pkg: "duck-demo/pkg/cli"
              desc: "governance: service must not import cli delivery packages"

        governance_api:
          files:
            - "internal/api/**/*.go"
          deny:
            - pkg: "duck-demo/internal/db"
              desc: "governance: api imports must not depend on infrastructure layers"
            - pkg: "duck-demo/internal/engine"
              desc: "governance: api imports must not depend on infrastructure layers"
            - pkg: "duck-demo/internal/declarative"
              desc: "governance: api imports must not depend on infrastructure layers"
            - pkg: "duck-demo/cmd"
              desc: "governance: api must not import cmd packages"
            - pkg: "duck-demo/pkg/cli"
              desc: "governance: api must not import cli delivery packages"

        governance_db:
          files:
            - "internal/db/**/*.go"
          deny:
            - pkg: "duck-demo/internal/api"
              desc: "governance: db imports must stay inward toward domain"
            - pkg: "duck-demo/internal/service"
              desc: "governance: db imports must stay inward toward domain"
            - pkg: "duck-demo/internal/engine"
              desc: "governance: db imports must stay inward toward domain"
            - pkg: "duck-demo/internal/middleware"
              desc: "governance: db imports must stay inward toward domain"
            - pkg: "duck-demo/cmd"
              desc: "governance: db must not import cmd packages"
            - pkg: "duck-demo/pkg/cli"
              desc: "governance: db must not import cli delivery packages"

        governance_engine:
          files:
            - "internal/engine/**/*.go"
          deny:
            - pkg: "duck-demo/internal/api"
              desc: "governance: engine must not import api"
            - pkg: "duck-demo/internal/service"
              desc: "governance: engine must not import service"
            - pkg: "duck-demo/cmd"
              desc: "governance: engine must not import cmd packages"
            - pkg: "duck-demo/pkg/cli"
              desc: "governance: engine must not import cli delivery packages"

        governance_middleware:
          files:
            - "internal/middleware/**/*.go"
          deny:
            - pkg: "duck-demo/internal/service"
              desc: "governance: middleware must not import service"
            - pkg: "duck-demo/internal/db"
              desc: "governance: middleware must not import db"
            - pkg: "duck-demo/internal/engine"
              desc: "governance: middleware must not import engine"

  exclusions:
    paths:
      - vendor
      - context

    rules:
      - path: _test\.go
        linters:
          - depguard
      - path: \.gen\.go
        linters:
          - depguard
      - path: internal/db/dbstore/.*\.sql\.go
        linters:
          - depguard
      - path: internal/duckdbsql/catalog/.*_gen\.go
        linters:
          - depguard
      - path: _test\.go
        linters:
          - gosec
      - path: internal/api/handler\.go
        linters:
          - revive
        text: "exported:"
      - path: cmd/server/main\.go
        linters:
          - revive
        text: "unused-parameter"
      - linters:
          - revive
        text: "var-naming"
      - path: _test\.go
        linters:
          - revive
        text: "unused-parameter"
