# https://taskfile.dev

version: '3'

vars:
  DB_PATH: ./ducklake_meta.sqlite
  MIGRATIONS_DIR: internal/db/migrations

tasks:
  migrate-up:
    desc: Run database migrations up
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} up

  migrate-down:
    desc: Run database migrations down
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} down

  migrate-status:
    desc: Show database migration status
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} status

  new-migration:
    desc: "Create a new migration (usage: task new-migration -- NAME)"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} create {{.CLI_ARGS}} sql

  sqlc:
    desc: Generate sqlc code
    cmds:
      - sqlc generate

  genduckdb:
    desc: Regenerate DuckDB catalog metadata (keywords, types, functions)
    dir: scripts/genduckdb
    cmds:
      - go run . -gen=all -outdir=../../internal/duckdbsql/catalog/

  bundle-api:
    desc: Bundle split OpenAPI files into single resolved spec
    run: once
    cmds:
      - |
        attempts=0
        while [ "$attempts" -lt 3 ]; do
          attempts=$((attempts + 1))
          echo "Bundling OpenAPI spec (attempt ${attempts}/3)..."
          REDOCLY_BIN=$(npx --yes -p @redocly/cli@2.18.2 sh -lc 'command -v redocly')
          if node --require ./scripts/redocly-react-global.cjs "$REDOCLY_BIN" bundle internal/api/openapi.yaml -o internal/api/openapi.bundled.yaml; then
            exit 0
          fi
          if [ "$attempts" -lt 3 ]; then
            echo "Redocly bundle failed; retrying in 5s..."
            sleep 5
          fi
        done
        echo "Redocly bundle failed after 3 attempts."
        exit 1
    sources:
      - internal/api/openapi.yaml
      - internal/api/paths/*.yaml
      - internal/api/schemas/*.yaml
    generates:
      - internal/api/openapi.bundled.yaml

  generate-api:
    desc: Generate API types and server from OpenAPI spec
    deps: [bundle-api]
    cmds:
      - oapi-codegen -generate models -package api -o internal/api/types.gen.go internal/api/openapi.bundled.yaml
      - oapi-codegen -generate chi-server,strict-server,spec -package api -o internal/api/server.gen.go internal/api/openapi.bundled.yaml

  generate-cli:
    desc: Generate CLI commands from OpenAPI spec
    deps: [bundle-api]
    cmds:
      - go run ./cmd/cli-gen -spec internal/api/openapi.bundled.yaml -config cli-config.yaml -out pkg/cli/gen/
    sources:
      - internal/api/openapi.yaml
      - internal/api/paths/*.yaml
      - internal/api/schemas/*.yaml
      - cli-config.yaml
      - internal/codegen/cli/**/*.go
      - internal/codegen/cli/templates/*.tmpl
    generates:
      - pkg/cli/gen/*.gen.go

  generate:declarative-schema:
    desc: Generate declarative JSON Schema artifacts
    cmds:
      - go run ./cmd/declarative-schema-gen -outdir schemas/declarative/v1
    sources:
      - internal/declarative/*.go
      - cmd/declarative-schema-gen/*.go
    generates:
      - schemas/declarative/v1/duck.declarative.schema.json
      - schemas/declarative/v1/index.json
      - schemas/declarative/v1/kinds/*.schema.json

  verify:declarative-schema:
    desc: Verify declarative schema artifacts are up to date
    cmds:
      - task generate:declarative-schema
      - git diff --exit-code -- schemas/declarative/v1

  docs:generate:
    desc: Generate docs reference pages from API and schemas
    deps: [bundle-api, generate:declarative-schema]
    cmds:
      - go run ./cmd/docsgen -openapi internal/api/openapi.bundled.yaml -declarative-index schemas/declarative/v1/index.json -declarative-dir schemas/declarative/v1 -outdir docs/reference/generated
    sources:
      - internal/api/openapi.bundled.yaml
      - schemas/declarative/v1/index.json
      - schemas/declarative/v1/kinds/*.schema.json
      - cmd/docsgen/*.go
      - internal/docsgen/**/*.go
    generates:
      - docs/reference/generated/api/index.md
      - docs/reference/generated/api/features.md
      - docs/reference/generated/declarative/index.md

  docs:dev:
    desc: Start VitePress docs dev server
    deps: [docs:generate]
    cmds:
      - npm install --prefix docs
      - npm run docs:dev --prefix docs

  docs:build:
    desc: Build static docs site with VitePress
    deps: [docs:generate]
    cmds:
      - npm ci --prefix docs
      - npm run docs:build --prefix docs

  ui:assets:
    desc: Install web deps and sync UI token assets
    cmds:
      - npm ci --prefix web
      - npm run build --prefix web

  verify:docs-generated:
    desc: Verify generated docs reference pages are up to date
    cmds:
      - task docs:generate
      - git diff --exit-code -- docs/reference/generated

  generate:
    desc: Run all code generation
    deps: [generate-api, sqlc, generate-cli, genduckdb, generate:declarative-schema]

  build:
    desc: Build all packages
    preconditions:
      - sh: test -f internal/api/types.gen.go
        msg: "Generated files missing. Run 'task generate' first."
    cmds:
      - go build ./...

  build-cli:
    desc: Build the CLI binary
    cmds:
      - go build -ldflags "-X main.version={{.GIT_TAG}}" -o bin/duck ./cmd/cli

  build-agent:
    desc: Build the compute agent binary
    cmds:
      - go build -o bin/compute-agent ./cmd/compute-agent

  test:
    desc: Run all tests (unit + integration)
    deps: [test:unit, test:integration]

  test:unit:
    desc: Run unit tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race ./...

  test:arch:
    desc: Run architecture governance tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- ./internal/architecture/...

  test:integration:
    desc: Run integration tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags integration -timeout 120s ./test/integration/... ./internal/api ./internal/service/security ./internal/service/ingestion ./internal/service/storage ./internal/engine

  examples:test:
    desc: Run declarative examples integration suite
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags integration -run TestDeclarativeExamples_ ./test/integration/...

  examples:validate:
    desc: Validate all example declarative config directories
    cmds:
      - for dir in examples/*/config; do go run ./cmd/cli validate --config-dir "$dir"; done

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run all linters (Go + OpenAPI)
    deps: [lint:go, lint:api]

  lint:go:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  lint:api:
    desc: Lint the OpenAPI spec for consistency
    deps: [bundle-api]
    cmds:
      - go run ./cmd/lint-api internal/api/openapi.bundled.yaml

  test-cli:
    desc: Run CLI tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race ./pkg/cli/... ./internal/codegen/cli/...

  integration-test:
    desc: "Run integration tests (alias for test:integration)"
    deps: [test:integration]

  check:
    desc: Run all checks (lint + test) and print a CI-style summary
    silent: true
    cmds:
      - |
        failed=0
        results=""
        for step in lint:go lint:api verify:declarative-schema verify:docs-generated test:arch test:unit test:integration; do
          if task "$step" > /dev/null 2>&1; then
            results="${results}  ${step} ... ok\n"
          else
            results="${results}  ${step} ... FAIL\n"
            failed=1
          fi
        done
        printf "\n=== Check Summary ===\n${results}\n"
        if [ "$failed" -eq 1 ]; then
          echo "Some checks failed. Run the individual task for details."
          exit 1
        else
          echo "All checks passed."
        fi
