# https://taskfile.dev

version: '3'

vars:
  DB_PATH: ./ducklake_meta.sqlite
  MIGRATIONS_DIR: internal/db/migrations

tasks:
  migrate-up:
    desc: Run database migrations up
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} up

  migrate-down:
    desc: Run database migrations down
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} down

  migrate-status:
    desc: Show database migration status
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} status

  new-migration:
    desc: "Create a new migration (usage: task new-migration -- NAME)"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} create {{.CLI_ARGS}} sql

  sqlc:
    desc: Generate sqlc code
    cmds:
      - sqlc generate

  generate-api:
    desc: Generate API types and server from OpenAPI spec
    cmds:
      - oapi-codegen -generate models -package api -o internal/api/types.gen.go internal/api/openapi.yaml
      - oapi-codegen -generate chi-server,strict-server,spec -package api -o internal/api/server.gen.go internal/api/openapi.yaml

  generate-cli:
    desc: Generate CLI commands from OpenAPI spec
    cmds:
      - go run ./cmd/cli-gen -spec internal/api/openapi.yaml -config cli-config.yaml -out pkg/cli/gen/
    sources:
      - internal/api/openapi.yaml
      - cli-config.yaml
      - internal/codegen/cli/**/*.go
      - internal/codegen/cli/templates/*.tmpl
    generates:
      - pkg/cli/gen/*.gen.go

  generate:
    desc: Run all code generation
    deps: [generate-api, sqlc, generate-cli]

  build:
    desc: Build all packages
    cmds:
      - go build ./...

  build-cli:
    desc: Build the CLI binary
    cmds:
      - go build -ldflags "-X main.version={{.GIT_TAG}}" -o bin/duck ./cmd/cli

  build-agent:
    desc: Build the compute agent binary
    cmds:
      - go build -o bin/compute-agent ./cmd/compute-agent

  test:
    desc: Run all tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  lint-api:
    desc: Lint the OpenAPI spec for consistency
    cmds:
      - go run ./cmd/lint-api internal/api/openapi.yaml

  test-cli:
    desc: Run CLI tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race ./pkg/cli/... ./internal/codegen/cli/...

  check-generated:
    desc: Verify all generated files are up to date
    cmds:
      - task generate
      - git diff --exit-code pkg/cli/gen/ internal/api/types.gen.go internal/api/server.gen.go

  integration-test:
    desc: Run integration tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags integration -timeout 120s ./test/integration/...
