# https://taskfile.dev

version: '3'

vars:
  DB_PATH: ./ducklake_meta.sqlite
  MIGRATIONS_DIR: internal/db/migrations

tasks:
  migrate-up:
    desc: Run database migrations up
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} up

  migrate-down:
    desc: Run database migrations down
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} down

  migrate-status:
    desc: Show database migration status
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} sqlite3 {{.DB_PATH}} status

  new-migration:
    desc: "Create a new migration (usage: task new-migration -- NAME)"
    cmds:
      - goose -dir {{.MIGRATIONS_DIR}} create {{.CLI_ARGS}} sql

  sqlc:
    desc: Generate sqlc code
    cmds:
      - sqlc generate

  bundle-api:
    desc: Bundle split OpenAPI files into single resolved spec
    cmds:
      - npx --yes @redocly/cli bundle internal/api/openapi.yaml -o internal/api/openapi.bundled.yaml
    sources:
      - internal/api/openapi.yaml
      - internal/api/paths/*.yaml
      - internal/api/schemas/*.yaml
    generates:
      - internal/api/openapi.bundled.yaml

  generate-api:
    desc: Generate API types and server from OpenAPI spec
    deps: [bundle-api]
    cmds:
      - oapi-codegen -generate models -package api -o internal/api/types.gen.go internal/api/openapi.bundled.yaml
      - oapi-codegen -generate chi-server,strict-server,spec -package api -o internal/api/server.gen.go internal/api/openapi.bundled.yaml

  generate-cli:
    desc: Generate CLI commands from OpenAPI spec
    deps: [bundle-api]
    cmds:
      - go run ./cmd/cli-gen -spec internal/api/openapi.bundled.yaml -config cli-config.yaml -out pkg/cli/gen/
    sources:
      - internal/api/openapi.yaml
      - internal/api/paths/*.yaml
      - internal/api/schemas/*.yaml
      - cli-config.yaml
      - internal/codegen/cli/**/*.go
      - internal/codegen/cli/templates/*.tmpl
    generates:
      - pkg/cli/gen/*.gen.go

  generate:
    desc: Run all code generation
    deps: [generate-api, sqlc, generate-cli]

  build:
    desc: Build all packages
    preconditions:
      - sh: test -f internal/api/types.gen.go
        msg: "Generated files missing. Run 'task generate' first."
    cmds:
      - go build ./...

  build-cli:
    desc: Build the CLI binary
    cmds:
      - go build -ldflags "-X main.version={{.GIT_TAG}}" -o bin/duck ./cmd/cli

  build-agent:
    desc: Build the compute agent binary
    cmds:
      - go build -o bin/compute-agent ./cmd/compute-agent

  test:
    desc: Run all tests (unit + integration)
    deps: [test:unit, test:integration]

  test:unit:
    desc: Run unit tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race ./...

  test:integration:
    desc: Run integration tests (package summary, shows failures inline)
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -tags integration -timeout 120s ./test/integration/...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run all linters (Go + OpenAPI)
    deps: [lint:go, lint:api]

  lint:go:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  lint:api:
    desc: Lint the OpenAPI spec for consistency
    deps: [bundle-api]
    cmds:
      - go run ./cmd/lint-api internal/api/openapi.bundled.yaml

  test-cli:
    desc: Run CLI tests
    cmds:
      - gotestsum --format pkgname-and-test-fails -- -race ./pkg/cli/... ./internal/codegen/cli/...

  integration-test:
    desc: "Run integration tests (alias for test:integration)"
    deps: [test:integration]
