// Code generated by cmd/cue-sql-gen. DO NOT EDIT.
package cuestore

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

type Store struct {
	db DBTX
}

type Queries = Store

func New(db DBTX) *Store {
	return &Store{db: db}
}

func (s *Store) WithTx(tx *sql.Tx) *Store {
	return &Store{db: tx}
}
