// Code generated by cmd/cue-sql-gen. DO NOT EDIT.
package cuestore

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID          string
	KeyHash     string
	PrincipalID string
	Name        string
	ExpiresAt   sql.NullString
	CreatedAt   string
	KeyPrefix   sql.NullString
}

type AuditLog struct {
	ID             string
	PrincipalName  string
	Action         string
	StatementType  sql.NullString
	OriginalSql    sql.NullString
	RewrittenSql   sql.NullString
	TablesAccessed sql.NullString
	Status         string
	ErrorMessage   sql.NullString
	DurationMs     sql.NullInt64
	CreatedAt      string
	RowsReturned   sql.NullInt64
}

type AuthIdentity struct {
	ID            string
	PrincipalID   string
	Provider      string
	Issuer        sql.NullString
	Subject       string
	Email         sql.NullString
	EmailVerified int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AuthProvider struct {
	ID                  int64
	OidcEnabled         int64
	OidcIssuerUrl       sql.NullString
	OidcJwksUrl         sql.NullString
	OidcAudience        sql.NullString
	OidcClientID        sql.NullString
	OidcClientSecretEnc sql.NullString
	OidcScopes          sql.NullString
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type AuthRecoveryCode struct {
	ID          string
	PrincipalID string
	CodeHash    string
	UsedAt      sql.NullTime
	ExpiresAt   time.Time
	CreatedAt   time.Time
}

type Catalog struct {
	ID            string
	Name          string
	MetastoreType string
	Dsn           string
	DataPath      string
	Status        string
	StatusMessage sql.NullString
	IsDefault     int64
	Comment       sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type CatalogMetadatum struct {
	SecurableType string
	SecurableName string
	Comment       sql.NullString
	Properties    sql.NullString
	Owner         sql.NullString
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     sql.NullString
}

type Cell struct {
	ID         string
	NotebookID string
	CellType   string
	Content    string
	Position   int64
	LastResult sql.NullString
	CreatedAt  string
	UpdatedAt  string
	Name       sql.NullString
	Role       string
	Disabled   int64
	TestConfig string
	VisualSpec string
}

type ColumnLineageEdge struct {
	ID            int64
	LineageEdgeID string
	TargetColumn  string
	SourceSchema  string
	SourceTable   string
	SourceColumn  string
	TransformType string
	FunctionName  string
	CreatedAt     time.Time
}

type ColumnMask struct {
	ID             string
	TableID        string
	ColumnName     string
	MaskExpression string
	Description    sql.NullString
	CreatedAt      string
	Name           sql.NullString
}

type ColumnMaskBinding struct {
	ID            string
	ColumnMaskID  string
	PrincipalID   string
	PrincipalType string
	SeeOriginal   int64
}

type ColumnMetadatum struct {
	TableSecurableName string
	ColumnName         string
	Comment            sql.NullString
	Properties         sql.NullString
	UpdatedAt          sql.NullString
}

type ComputeAssignment struct {
	ID            string
	PrincipalID   string
	PrincipalType string
	EndpointID    string
	IsDefault     int64
	FallbackLocal int64
	CreatedAt     time.Time
}

type ComputeEndpoint struct {
	ID                         string
	ExternalID                 string
	Name                       string
	Url                        string
	Type                       string
	Status                     string
	Size                       string
	MaxMemoryGb                sql.NullInt64
	AuthToken                  string
	Owner                      string
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	SelectionPolicy            string
	WorkloadClass              string
	ReadinessStatus            string
	MaxConcurrency             sql.NullInt64
	MaxResultSizeMb            sql.NullInt64
	RecommendedForLargeQueries int64
	IsDraining                 int64
	LastHealthStatus           sql.NullString
	LastHealthCheckedAt        sql.NullTime
	ActiveQueries              sql.NullInt64
	QueuedJobs                 sql.NullInt64
	RunningJobs                sql.NullInt64
	CompletedJobs              sql.NullInt64
	StoredJobs                 sql.NullInt64
	CleanedJobs                sql.NullInt64
	QueryResultTtlSeconds      sql.NullInt64
}

type Dashboard struct {
	ID                   string
	Name                 string
	Description          string
	Owner                string
	CreatedAt            string
	UpdatedAt            string
	FolderID             sql.NullString
	SemanticProjectName  string
	SemanticModelName    string
	ComputeMode          string
	ComputeEndpointName  string
	ComputeFallbackLocal int64
}

type DashboardWidget struct {
	ID              string
	DashboardID     string
	Name            string
	Description     string
	SourceJson      string
	VisualSpec      string
	LayoutX         int64
	LayoutY         int64
	LayoutW         int64
	LayoutH         int64
	CreatedAt       string
	UpdatedAt       string
	FilterOriginKey string
	PageName        string
}

type ExternalLocation struct {
	ID             string
	Name           string
	Url            string
	CredentialName string
	StorageType    string
	Comment        string
	Owner          string
	ReadOnly       int64
	CreatedAt      string
	UpdatedAt      string
}

type ExternalTable struct {
	ID           string
	SchemaName   string
	TableName    string
	FileFormat   string
	SourcePath   string
	LocationName string
	Comment      string
	Owner        string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    sql.NullString
	CatalogName  string
}

type ExternalTableColumn struct {
	ID              string
	ExternalTableID string
	ColumnName      string
	ColumnType      string
	Position        int64
}

type GetAPIKeyByHashRow struct {
	ID            string
	KeyHash       string
	PrincipalID   string
	Name          string
	ExpiresAt     sql.NullString
	CreatedAt     string
	KeyPrefix     sql.NullString
	PrincipalName string
}

type GetColumnMaskBindingsForPrincipalRow struct {
	TableID        string
	ColumnName     string
	MaskExpression string
	SeeOriginal    int64
}

type GetColumnMaskForTableAndPrincipalRow struct {
	ColumnName     string
	MaskExpression string
	SeeOriginal    int64
}

type GetDownstreamLineageRow struct {
	SourceTable   string
	TargetTable   sql.NullString
	EdgeType      string
	PrincipalName string
	CreatedAt     string
	SourceSchema  sql.NullString
	TargetSchema  sql.NullString
}

type GetUpstreamLineageRow struct {
	SourceTable   string
	TargetTable   sql.NullString
	EdgeType      string
	PrincipalName string
	CreatedAt     string
	SourceSchema  sql.NullString
	TargetSchema  sql.NullString
}

type GitRepo struct {
	ID            string
	Url           string
	Branch        string
	Path          string
	AuthToken     string
	WebhookSecret sql.NullString
	Owner         string
	LastSyncAt    sql.NullString
	LastCommit    sql.NullString
	CreatedAt     string
	UpdatedAt     string
}

type Group struct {
	ID          string
	Name        string
	Description sql.NullString
	CreatedAt   string
}

type GroupMember struct {
	GroupID    string
	MemberType string
	MemberID   string
}

type LocalCredential struct {
	PrincipalID        string
	Username           string
	PasswordHash       string
	PasswordChangedAt  time.Time
	MustChangePassword int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Macro struct {
	ID          string
	Name        string
	MacroType   string
	Parameters  string
	Body        string
	Description string
	CreatedBy   string
	CreatedAt   string
	UpdatedAt   string
	CatalogName string
	ProjectName string
	Visibility  string
	Owner       string
	Properties  string
	Tags        string
	Status      string
}

type MacroRevision struct {
	ID          string
	MacroID     string
	MacroName   string
	Version     int64
	ContentHash string
	Parameters  string
	Body        string
	Description string
	Status      string
	CreatedBy   string
	CreatedAt   string
}

type Model struct {
	ID              string
	ProjectName     string
	Name            string
	SqlBody         string
	Materialization string
	Description     string
	Owner           string
	Tags            string
	DependsOn       string
	Config          string
	CreatedBy       string
	CreatedAt       string
	UpdatedAt       string
	Contract        string
	FreshnessMaxLag sql.NullInt64
	FreshnessCron   sql.NullString
}

type ModelRun struct {
	ID                 string
	Status             string
	TriggerType        string
	TriggeredBy        string
	TargetCatalog      string
	TargetSchema       string
	ModelSelector      string
	Variables          string
	StartedAt          sql.NullString
	FinishedAt         sql.NullString
	ErrorMessage       sql.NullString
	CreatedAt          string
	FullRefresh        int64
	CompileManifest    string
	CompileDiagnostics string
	ProjectName        string
	EnvironmentName    string
	BuildID            sql.NullString
}

type ModelRunStep struct {
	ID           string
	RunID        string
	ModelID      string
	ModelName    string
	Status       string
	Tier         int64
	RowsAffected sql.NullInt64
	StartedAt    sql.NullString
	FinishedAt   sql.NullString
	ErrorMessage sql.NullString
	CreatedAt    string
	CompiledSql  sql.NullString
	CompiledHash sql.NullString
	DependsOn    string
	VarsUsed     string
	MacrosUsed   string
}

type ModelTest struct {
	ID         string
	ModelID    string
	Name       string
	TestType   string
	ColumnName string
	Config     string
	CreatedAt  string
}

type ModelTestResult struct {
	ID           string
	RunStepID    string
	TestID       string
	TestName     string
	Status       string
	RowsReturned sql.NullInt64
	ErrorMessage sql.NullString
	CreatedAt    string
}

type Notebook struct {
	ID                    string
	Name                  string
	Description           sql.NullString
	Owner                 string
	CreatedAt             string
	UpdatedAt             string
	GitRepoID             sql.NullString
	GitPath               sql.NullString
	FolderID              sql.NullString
	ProjectOverrideID     sql.NullString
	EnvironmentOverrideID sql.NullString
}

type NotebookJob struct {
	ID         string
	NotebookID string
	SessionID  string
	State      string
	Result     sql.NullString
	Error      sql.NullString
	CreatedAt  string
	UpdatedAt  string
}

type NotebookModelLink struct {
	ID           string
	NotebookID   string
	ModelID      string
	OutputCellID string
	CreatedAt    string
	UpdatedAt    string
}

type Pipeline struct {
	ID               string
	Name             string
	Description      string
	ScheduleCron     sql.NullString
	IsPaused         int64
	ConcurrencyLimit int64
	CreatedBy        string
	CreatedAt        string
	UpdatedAt        string
	FolderID         sql.NullString
}

type PipelineJob struct {
	ID                string
	PipelineID        string
	Name              string
	ComputeEndpointID sql.NullString
	DependsOn         string
	NotebookID        string
	TimeoutSeconds    sql.NullInt64
	RetryCount        int64
	JobOrder          int64
	CreatedAt         string
	JobType           string
	ModelSelector     string
}

type PipelineJobRun struct {
	ID           string
	RunID        string
	JobID        string
	JobName      string
	Status       string
	StartedAt    sql.NullString
	FinishedAt   sql.NullString
	ErrorMessage sql.NullString
	RetryAttempt int64
	CreatedAt    string
}

type PipelineRun struct {
	ID            string
	PipelineID    string
	Status        string
	TriggerType   string
	TriggeredBy   string
	Parameters    string
	GitCommitHash sql.NullString
	StartedAt     sql.NullString
	FinishedAt    sql.NullString
	ErrorMessage  sql.NullString
	CreatedAt     string
}

type Principal struct {
	ID             string
	Name           string
	Type           string
	IsAdmin        int64
	CreatedAt      string
	ExternalID     sql.NullString
	ExternalIssuer sql.NullString
}

type PrivilegeGrant struct {
	ID            string
	PrincipalID   string
	PrincipalType string
	SecurableType string
	SecurableID   string
	Privilege     string
	GrantedBy     sql.NullString
	GrantedAt     string
}

type RowFilter struct {
	ID          string
	TableID     string
	FilterSql   string
	Description sql.NullString
	CreatedAt   string
	Name        sql.NullString
}

type RowFilterBinding struct {
	ID            string
	RowFilterID   string
	PrincipalID   string
	PrincipalType string
}

type SemanticMetric struct {
	ID                 string
	SemanticModelID    string
	Name               string
	Description        string
	MetricType         string
	ExpressionMode     string
	Expression         string
	DefaultTimeGrain   string
	Format             string
	Owner              string
	CertificationState string
	CreatedBy          string
	CreatedAt          string
	UpdatedAt          string
	Label              string
	FilterSql          string
	RelationshipNames  string
}

type SemanticModel struct {
	ID                   string
	Name                 string
	Description          string
	Owner                string
	BaseModelRef         string
	DefaultTimeDimension string
	Tags                 string
	CreatedBy            string
	CreatedAt            string
	UpdatedAt            string
}

type SemanticPreAggregation struct {
	ID              string
	SemanticModelID string
	Name            string
	MetricSet       string
	DimensionSet    string
	Grain           string
	TargetRelation  string
	RefreshPolicy   string
	CreatedBy       string
	CreatedAt       string
	UpdatedAt       string
}

type SemanticRelationship struct {
	ID               string
	Name             string
	FromSemanticID   string
	ToSemanticID     string
	RelationshipType string
	JoinSql          string
	Cost             int64
	MaxHops          int64
	CreatedBy        string
	CreatedAt        string
	UpdatedAt        string
}

type SetupState struct {
	ID                      int64
	SetupCompleted          int64
	SetupCompletedAt        sql.NullTime
	SetupCompletedBy        sql.NullString
	BootstrapTokenHash      sql.NullString
	BootstrapTokenExpiresAt sql.NullTime
	CreatedAt               time.Time
	UpdatedAt               time.Time
}

type StorageCredential struct {
	ID                         string
	Name                       string
	CredentialType             string
	KeyIDEncrypted             string
	SecretEncrypted            string
	Endpoint                   string
	Region                     string
	UrlStyle                   string
	Comment                    string
	Owner                      string
	CreatedAt                  string
	UpdatedAt                  string
	AzureAccountName           string
	AzureAccountKeyEncrypted   string
	AzureClientID              string
	AzureTenantID              string
	AzureClientSecretEncrypted string
	GcsKeyFilePath             string
}

type TableStatistic struct {
	TableSecurableName string
	RowCount           sql.NullInt64
	SizeBytes          sql.NullInt64
	ColumnCount        sql.NullInt64
	LastProfiledAt     sql.NullString
	ProfiledBy         sql.NullString
}

type Tag struct {
	ID        string
	Key       string
	Value     sql.NullString
	CreatedBy string
	CreatedAt string
}

type TagAssignment struct {
	ID            string
	TagID         string
	SecurableType string
	SecurableID   string
	ColumnName    sql.NullString
	AssignedBy    string
	AssignedAt    string
}

type View struct {
	ID             string
	SchemaID       string
	Name           string
	ViewDefinition string
	Comment        sql.NullString
	Properties     sql.NullString
	Owner          string
	SourceTables   sql.NullString
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      sql.NullString
}

type Volume struct {
	ID              string
	Name            string
	SchemaName      string
	CatalogName     string
	VolumeType      string
	StorageLocation string
	Comment         string
	Owner           string
	CreatedAt       string
	UpdatedAt       string
}

type WebSession struct {
	ID            string
	PrincipalID   string
	SessionHash   string
	AuthMethod    string
	UserAgent     sql.NullString
	IpAddress     sql.NullString
	ExpiresAt     time.Time
	IdleExpiresAt time.Time
	LastSeenAt    time.Time
	RevokedAt     sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type WebauthnCredential struct {
	ID             string
	PrincipalID    string
	CredentialID   string
	PublicKey      string
	SignCount      int64
	Transports     sql.NullString
	BackupEligible int64
	BackupState    int64
	CreatedAt      time.Time
	LastUsedAt     sql.NullTime
}
