// Package declarative renders markdown docs for the CUE-native declarative config.
package declarative

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Generate renders declarative reference docs into markdown files.
func Generate(outDir string) error {
	if err := os.RemoveAll(outDir); err != nil {
		return fmt.Errorf("clean output dir: %w", err)
	}
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	var b strings.Builder
	b.WriteString("<!-- Generated by docsgen. DO NOT EDIT. -->\n\n")
	b.WriteString("# Declarative Reference\n\n")
	b.WriteString("QuackStack declarative config is now CUE-native. The supported contract is a unified top-level `platform` value compiled from all `.cue` fragments in a config module.\n\n")
	b.WriteString("## Module Contract\n\n")
	b.WriteString("- Config root must contain `cue.mod/module.cue`\n")
	b.WriteString("- All config files are `.cue`\n")
	b.WriteString("- The compiler recursively loads packages and unifies exported `platform` fragments\n")
	b.WriteString("- `quack validate`, `quack plan`, `quack apply`, and `quack export` all operate on the compiled CUE graph\n\n")
	b.WriteString("## Top-Level Sections\n\n")
	b.WriteString("- `security`\n")
	b.WriteString("- `governance`\n")
	b.WriteString("- `storage`\n")
	b.WriteString("- `compute`\n")
	b.WriteString("- `catalogs`\n")
	b.WriteString("- `domains`\n")
	b.WriteString("- `teams`\n")
	b.WriteString("- `data_products`\n")
	b.WriteString("- `workspaces`\n")
	b.WriteString("- `projects`\n")
	b.WriteString("- `assets`\n\n")
	b.WriteString("## Recommended Layout\n\n")
	b.WriteString("```text\n")
	b.WriteString("quackstack-config/\n")
	b.WriteString("  cue.mod/module.cue\n")
	b.WriteString("  workspaces/<workspace>/workspace.cue\n")
	b.WriteString("  projects/<project>/project.cue\n")
	b.WriteString("  catalogs/<catalog>/catalog.cue\n")
	b.WriteString("  security/*.cue\n")
	b.WriteString("  compute/*.cue\n")
	b.WriteString("  domains/*.cue\n")
	b.WriteString("  teams/*.cue\n")
	b.WriteString("  data-products/*.cue\n")
	b.WriteString("```\n\n")
	b.WriteString("## Authoring Model\n\n")
	b.WriteString("- Workspaces own folder trees and notebooks.\n")
	b.WriteString("- Projects own environments, models, macros, and semantic models.\n")
	b.WriteString("- Catalogs remain hierarchical under a catalog-scoped tree.\n")
	b.WriteString("- Cross-resource validation still runs after compilation for live-state and referential checks.\n")

	return os.WriteFile(filepath.Join(outDir, "index.md"), []byte(b.String()), 0o600)
}
