// Code generated by OpenCode for APIGen transport compatibility aliases. DO NOT EDIT.
//nolint:revive // Exported aliases intentionally omit per-type doc comments.

package api

type GenBadRequestJSONResponse = BadRequestJSONResponse
type GenBadRequestResponseHeaders = BadRequestResponseHeaders
type GenConflictJSONResponse = ConflictJSONResponse
type GenConflictResponseHeaders = ConflictResponseHeaders
type GenForbiddenJSONResponse = ForbiddenJSONResponse
type GenForbiddenResponseHeaders = ForbiddenResponseHeaders
type GenInternalErrorJSONResponse = InternalErrorJSONResponse
type GenInternalErrorResponseHeaders = InternalErrorResponseHeaders
type GenNotFoundJSONResponse = NotFoundJSONResponse
type GenNotFoundResponseHeaders = NotFoundResponseHeaders
