// Code generated by apigen schema model emitter. DO NOT EDIT.
package api

type GenSchemaAPIKeyInfo = APIKeyInfo

type GenSchemaAddWorkspaceMemberRequest = AddWorkspaceMemberRequest

type GenSchemaAsset = Asset

type GenSchemaAssetAutoMaterializePolicy = AssetAutoMaterializePolicy

type GenSchemaAssetBackfillDetails = AssetBackfillDetails

type GenSchemaAssetCheck = AssetCheck

type GenSchemaAssetCheckInput = AssetCheckInput

type GenSchemaAssetCheckList = AssetCheckList

type GenSchemaAssetCheckResult = AssetCheckResult

type GenSchemaAssetCheckSeverity = AssetCheckSeverity

type GenSchemaAssetFreshnessBlocker = AssetFreshnessBlocker

type GenSchemaAssetFreshnessBlockersResponse = AssetFreshnessBlockersResponse

type GenSchemaAssetFreshnessEdge = AssetFreshnessEdge

type GenSchemaAssetFreshnessExplanation = AssetFreshnessExplanation

type GenSchemaAssetFreshnessPolicy = AssetFreshnessPolicy

type GenSchemaAssetFreshnessReconcileResponse = AssetFreshnessReconcileResponse

type GenSchemaAssetFreshnessReconcileTarget = AssetFreshnessReconcileTarget

type GenSchemaAssetFreshnessRequirement = AssetFreshnessRequirement

type GenSchemaAssetFreshnessRequirementsResponse = AssetFreshnessRequirementsResponse

type GenSchemaAssetFreshnessStatus = AssetFreshnessStatus

type GenSchemaAssetGraph = AssetGraph

type GenSchemaAssetMaterialization = AssetMaterialization

type GenSchemaAssetMaterializationPolicy = AssetMaterializationPolicy

type GenSchemaAssetPartition = AssetPartition

type GenSchemaAssetRun = AssetRun

type GenSchemaAssetRunStatus = AssetRunStatus

type GenSchemaAssetTriggerResponse = AssetTriggerResponse

type GenSchemaAssetTriggerType = AssetTriggerType

type GenSchemaAssetType = AssetType

type GenSchemaAuditDecisionStatus = AuditDecisionStatus

type GenSchemaAuditEntry = AuditEntry

type GenSchemaBackfillRequest = BackfillRequest

type GenSchemaBackfillSlice = BackfillSlice

type GenSchemaBuild = Build

type GenSchemaBuildCompareModelDiff = BuildCompareModelDiff

type GenSchemaBuildCompareResult = BuildCompareResult

type GenSchemaBuildImpactResult = BuildImpactResult

type GenSchemaBuildSourceStateSnapshot = BuildSourceStateSnapshot

type GenSchemaBuildState = BuildState

type GenSchemaBuildStateSnapshot = BuildStateSnapshot

type GenSchemaCancelQueryResponse = CancelQueryResponse

type GenSchemaCatalogHistoryEntry = CatalogHistoryEntry

type GenSchemaCatalogHistoryResponse = CatalogHistoryResponse

type GenSchemaCatalogRegistration = CatalogRegistration

type GenSchemaCatalogRegistrationList = CatalogRegistrationList

type GenSchemaCatalogStatus = CatalogStatus

type GenSchemaCatalogVersionSummary = CatalogVersionSummary

type GenSchemaCell = Cell

type GenSchemaCellCellType = CellCellType

type GenSchemaCellExecutionResult = CellExecutionResult

type GenSchemaCellList = CellList

type GenSchemaCellRole = CellRole

type GenSchemaCleanupAPIKeysResponse = CleanupAPIKeysResponse

type GenSchemaColumnDetail = ColumnDetail

type GenSchemaColumnLineageEdge = ColumnLineageEdge

type GenSchemaColumnLineageEdgeTransformType = ColumnLineageEdgeTransformType

type GenSchemaColumnLineageSourceRef = ColumnLineageSourceRef

type GenSchemaColumnMask = ColumnMask

type GenSchemaColumnMaskBinding = ColumnMaskBinding

type GenSchemaColumnMaskBindingRequest = ColumnMaskBindingRequest

type GenSchemaColumnSensitivityInfo = ColumnSensitivityInfo

type GenSchemaCommitIngestionRequest = CommitIngestionRequest

type GenSchemaCompareBuildsRequest = CompareBuildsRequest

type GenSchemaCompilation = Compilation

type GenSchemaCompileDiagnostic = CompileDiagnostic

type GenSchemaCompileDiagnosticLocation = CompileDiagnosticLocation

type GenSchemaCompileDiagnosticSeverity = CompileDiagnosticSeverity

type GenSchemaCompiledColumnLineage = CompiledColumnLineage

type GenSchemaComputeAssignment = ComputeAssignment

type GenSchemaComputeAssignmentPrincipalType = ComputeAssignmentPrincipalType

type GenSchemaComputeEndpoint = ComputeEndpoint

type GenSchemaComputeEndpointHealth = ComputeEndpointHealth

type GenSchemaComputeEndpointSize = ComputeEndpointSize

type GenSchemaComputeEndpointStatus = ComputeEndpointStatus

type GenSchemaComputeEndpointType = ComputeEndpointType

type GenSchemaComputeRoutingDefaults = ComputeRoutingDefaults

type GenSchemaCreateAPIKeyRequest = CreateAPIKeyRequest

type GenSchemaCreateAPIKeyResponse = CreateAPIKeyResponse

type GenSchemaCreateAssetBackfillRequest = CreateAssetBackfillRequest

type GenSchemaCreateAssetBackfillResponse = CreateAssetBackfillResponse

type GenSchemaCreateAssetRequest = CreateAssetRequest

type GenSchemaCreateBuildRequest = CreateBuildRequest

type GenSchemaCreateBuildRunRequest = CreateBuildRunRequest

type GenSchemaCreateCatalogRequest = CreateCatalogRequest

type GenSchemaCreateCellRequest = CreateCellRequest

type GenSchemaCreateColumnMaskRequest = CreateColumnMaskRequest

type GenSchemaCreateColumnRequest = CreateColumnRequest

type GenSchemaCreateCompilationRequest = CreateCompilationRequest

type GenSchemaCreateComputeAssignmentRequest = CreateComputeAssignmentRequest

type GenSchemaCreateComputeEndpointRequest = CreateComputeEndpointRequest

type GenSchemaCreateDashboardRequest = CreateDashboardRequest

type GenSchemaCreateDashboardWidgetRequest = CreateDashboardWidgetRequest

type GenSchemaCreateDataProductRequest = CreateDataProductRequest

type GenSchemaCreateDataProductVersionRequest = CreateDataProductVersionRequest

type GenSchemaCreateEnvironmentRequest = CreateEnvironmentRequest

type GenSchemaCreateExternalLocationRequest = CreateExternalLocationRequest

type GenSchemaCreateFolderRequest = CreateFolderRequest

type GenSchemaCreateGitRepoRequest = CreateGitRepoRequest

type GenSchemaCreateGrantRequest = CreateGrantRequest

type GenSchemaCreateGroupMemberRequest = CreateGroupMemberRequest

type GenSchemaCreateGroupRequest = CreateGroupRequest

type GenSchemaCreateMacroRequest = CreateMacroRequest

type GenSchemaCreateModelRequest = CreateModelRequest

type GenSchemaCreateModelTestRequest = CreateModelTestRequest

type GenSchemaCreateNotebookRequest = CreateNotebookRequest

type GenSchemaCreatePipelineJobRequest = CreatePipelineJobRequest

type GenSchemaCreatePipelineRequest = CreatePipelineRequest

type GenSchemaCreatePrincipalRequest = CreatePrincipalRequest

type GenSchemaCreateProductDependencyRequest = CreateProductDependencyRequest

type GenSchemaCreateProductDomainRequest = CreateProductDomainRequest

type GenSchemaCreateProductSubscriptionRequest = CreateProductSubscriptionRequest

type GenSchemaCreateProductTeamRequest = CreateProductTeamRequest

type GenSchemaCreateProjectDependencyRequest = CreateProjectDependencyRequest

type GenSchemaCreateProjectMacroRequest = CreateProjectMacroRequest

type GenSchemaCreateProjectModelRequest = CreateProjectModelRequest

type GenSchemaCreateProjectReleaseRequest = CreateProjectReleaseRequest

type GenSchemaCreateProjectRequest = CreateProjectRequest

type GenSchemaCreateProjectSeedRequest = CreateProjectSeedRequest

type GenSchemaCreateRowFilterRequest = CreateRowFilterRequest

type GenSchemaCreateSavedResourceRequest = CreateSavedResourceRequest

type GenSchemaCreateSchemaRequest = CreateSchemaRequest

type GenSchemaCreateSemanticMetricRequest = CreateSemanticMetricRequest

type GenSchemaCreateSemanticMetricRequestCertificationState = CreateSemanticMetricRequestCertificationState

type GenSchemaCreateSemanticModelRequest = CreateSemanticModelRequest

type GenSchemaCreateSemanticPreAggregationRequest = CreateSemanticPreAggregationRequest

type GenSchemaCreateSemanticRelationshipRequest = CreateSemanticRelationshipRequest

type GenSchemaCreateSourceDefinitionRequest = CreateSourceDefinitionRequest

type GenSchemaCreateStorageCredentialRequest = CreateStorageCredentialRequest

type GenSchemaCreateTableRequest = CreateTableRequest

type GenSchemaCreateTagAssignmentRequest = CreateTagAssignmentRequest

type GenSchemaCreateTagRequest = CreateTagRequest

type GenSchemaCreateViewRequest = CreateViewRequest

type GenSchemaCreateVolumeRequest = CreateVolumeRequest

type GenSchemaCreateWorkspaceRequest = CreateWorkspaceRequest

type GenSchemaDashboard = Dashboard

type GenSchemaDashboardComputePolicy = DashboardComputePolicy

type GenSchemaDashboardDetail = DashboardDetail

type GenSchemaDashboardNotebookCellSource = DashboardNotebookCellSource

type GenSchemaDashboardNotebookCellSourceUpdate = DashboardNotebookCellSourceUpdate

type GenSchemaDashboardSQLQuerySource = DashboardSQLQuerySource

type GenSchemaDashboardSQLQuerySourceUpdate = DashboardSQLQuerySourceUpdate

type GenSchemaDashboardSemanticQuerySource = DashboardSemanticQuerySource

type GenSchemaDashboardSemanticQuerySourceUpdate = DashboardSemanticQuerySourceUpdate

type GenSchemaDashboardWidget = DashboardWidget

type GenSchemaDashboardWidgetLayout = DashboardWidgetLayout

type GenSchemaDashboardWidgetLayoutUpdate = DashboardWidgetLayoutUpdate

type GenSchemaDashboardWidgetList = DashboardWidgetList

type GenSchemaDashboardWidgetSource = DashboardWidgetSource

type GenSchemaDashboardWidgetSourceKind = DashboardWidgetSourceKind

type GenSchemaDashboardWidgetSourceUpdate = DashboardWidgetSourceUpdate

type GenSchemaDataProduct = DataProduct

type GenSchemaDataProductDetail = DataProductDetail

type GenSchemaDataProductListItem = DataProductListItem

type GenSchemaDataProductStatus = DataProductStatus

type GenSchemaDataProductVersion = DataProductVersion

type GenSchemaDataProductVersionDetail = DataProductVersionDetail

type GenSchemaDataProductVersionList = DataProductVersionList

type GenSchemaDeprecateProductVersionRequest = DeprecateProductVersionRequest

type GenSchemaDuplicateNotebookRequest = DuplicateNotebookRequest

type GenSchemaEnvironment = Environment

type GenSchemaEnvironmentKind = EnvironmentKind

type GenSchemaEnvironmentScopedPlanRebuildRequest = EnvironmentScopedPlanRebuildRequest

type GenSchemaExternalLocation = ExternalLocation

type GenSchemaFolder = Folder

type GenSchemaFolderContentItem = FolderContentItem

type GenSchemaFolderPath = FolderPath

type GenSchemaFolderShare = FolderShare

type GenSchemaFolderShareList = FolderShareList

type GenSchemaFreshnessPolicy = FreshnessPolicy

type GenSchemaFreshnessStatus = FreshnessStatus

type GenSchemaGitRepo = GitRepo

type GenSchemaGitSyncResult = GitSyncResult

type GenSchemaGroup = Group

type GenSchemaGroupMember = GroupMember

type GenSchemaHealthResponse struct {
	Status string `json:"status"`
}

type GenSchemaIngestionOptions = IngestionOptions

type GenSchemaIngestionResult = IngestionResult

type GenSchemaLineageEdge = LineageEdge

type GenSchemaLineageNode = LineageNode

type GenSchemaLoadExternalRequest = LoadExternalRequest

type GenSchemaMacro = Macro

type GenSchemaMacroImpactList = MacroImpactList

type GenSchemaMacroImpactModel = MacroImpactModel

type GenSchemaMacroRevision = MacroRevision

type GenSchemaMacroRevisionDiff = MacroRevisionDiff

type GenSchemaMacroRevisionList = MacroRevisionList

type GenSchemaMacroStatus = MacroStatus

type GenSchemaMacroType = MacroType

type GenSchemaMacroVisibility = MacroVisibility

type GenSchemaManifestColumn = ManifestColumn

type GenSchemaManifestResponse = ManifestResponse

type GenSchemaMetastoreSummary = MetastoreSummary

type GenSchemaMetastoreType = MetastoreType

type GenSchemaMetricFreshnessStatus = MetricFreshnessStatus

type GenSchemaMetricQueryExplainResponse = MetricQueryExplainResponse

type GenSchemaMetricQueryJoinStep = MetricQueryJoinStep

type GenSchemaMetricQueryPlan = MetricQueryPlan

type GenSchemaMetricQueryRequest = MetricQueryRequest

type GenSchemaMetricQueryRunResponse = MetricQueryRunResponse

type GenSchemaModel = Model

type GenSchemaModelConfig = ModelConfig

type GenSchemaModelConfigOnSchemaChange = ModelConfigOnSchemaChange

type GenSchemaModelContract = ModelContract

type GenSchemaModelContractColumn = ModelContractColumn

type GenSchemaModelDAG = ModelDAG

type GenSchemaModelDAGNode = ModelDAGNode

type GenSchemaModelDAGTier = ModelDAGTier

type GenSchemaModelMaterialization = ModelMaterialization

type GenSchemaModelRun = ModelRun

type GenSchemaModelRunCompileDiagnostics = ModelRunCompileDiagnostics

type GenSchemaModelRunStep = ModelRunStep

type GenSchemaModelRunStepList = ModelRunStepList

type GenSchemaModelTest = ModelTest

type GenSchemaModelTestConfig = ModelTestConfig

type GenSchemaModelTestList = ModelTestList

type GenSchemaModelTestResult = ModelTestResult

type GenSchemaModelTestResultList = ModelTestResultList

type GenSchemaModelTestResultStatus = ModelTestResultStatus

type GenSchemaModelTestTestType = ModelTestTestType

type GenSchemaMoveFolderRequest = MoveFolderRequest

type GenSchemaMoveNotebookRequest = MoveNotebookRequest

type GenSchemaNotebook = Notebook

type GenSchemaNotebookCellTestConfig = NotebookCellTestConfig

type GenSchemaNotebookContext = NotebookContext

type GenSchemaNotebookDetail = NotebookDetail

type GenSchemaNotebookJob = NotebookJob

type GenSchemaNotebookJobState = NotebookJobState

type GenSchemaNotebookPublishModel = NotebookPublishModel

type GenSchemaNotebookSession = NotebookSession

type GenSchemaNotebookSessionState = NotebookSessionState

type GenSchemaNotebookShare = NotebookShare

type GenSchemaNotebookShareList = NotebookShareList

type GenSchemaNotebookShareRole = NotebookShareRole

type GenSchemaNotebookTestSeverity = NotebookTestSeverity

type GenSchemaOrphanResource = OrphanResource

type GenSchemaPaginatedAPIKeys = PaginatedAPIKeys

type GenSchemaPaginatedAssetCheckResults = PaginatedAssetCheckResults

type GenSchemaPaginatedAssetMaterializations = PaginatedAssetMaterializations

type GenSchemaPaginatedAssetPartitions = PaginatedAssetPartitions

type GenSchemaPaginatedAssetRuns = PaginatedAssetRuns

type GenSchemaPaginatedAssets = PaginatedAssets

type GenSchemaPaginatedAuditLogs = PaginatedAuditLogs

type GenSchemaPaginatedBackfillRequests = PaginatedBackfillRequests

type GenSchemaPaginatedBuilds = PaginatedBuilds

type GenSchemaPaginatedColumnDetails = PaginatedColumnDetails

type GenSchemaPaginatedColumnLineageEdges = PaginatedColumnLineageEdges

type GenSchemaPaginatedColumnMaskBindings = PaginatedColumnMaskBindings

type GenSchemaPaginatedColumnMasks = PaginatedColumnMasks

type GenSchemaPaginatedCompilations = PaginatedCompilations

type GenSchemaPaginatedCompileDiagnostics = PaginatedCompileDiagnostics

type GenSchemaPaginatedCompiledColumnLineage = PaginatedCompiledColumnLineage

type GenSchemaPaginatedComputeAssignments = PaginatedComputeAssignments

type GenSchemaPaginatedComputeEndpoints = PaginatedComputeEndpoints

type GenSchemaPaginatedDashboards = PaginatedDashboards

type GenSchemaPaginatedDataProducts = PaginatedDataProducts

type GenSchemaPaginatedEnvironments = PaginatedEnvironments

type GenSchemaPaginatedExternalLocations = PaginatedExternalLocations

type GenSchemaPaginatedFolderContents = PaginatedFolderContents

type GenSchemaPaginatedFolders = PaginatedFolders

type GenSchemaPaginatedGitRepos = PaginatedGitRepos

type GenSchemaPaginatedGrants = PaginatedGrants

type GenSchemaPaginatedGroupMembers = PaginatedGroupMembers

type GenSchemaPaginatedGroups = PaginatedGroups

type GenSchemaPaginatedLineageEdges = PaginatedLineageEdges

type GenSchemaPaginatedMacros = PaginatedMacros

type GenSchemaPaginatedModelRuns = PaginatedModelRuns

type GenSchemaPaginatedModels = PaginatedModels

type GenSchemaPaginatedNotebookJobs = PaginatedNotebookJobs

type GenSchemaPaginatedNotebooks = PaginatedNotebooks

type GenSchemaPaginatedPipelineRuns = PaginatedPipelineRuns

type GenSchemaPaginatedPipelines = PaginatedPipelines

type GenSchemaPaginatedPrincipals = PaginatedPrincipals

type GenSchemaPaginatedProductDomains = PaginatedProductDomains

type GenSchemaPaginatedProductTeams = PaginatedProductTeams

type GenSchemaPaginatedProjectDependencies = PaginatedProjectDependencies

type GenSchemaPaginatedProjectReleases = PaginatedProjectReleases

type GenSchemaPaginatedProjectSeeds = PaginatedProjectSeeds

type GenSchemaPaginatedProjectSources = PaginatedProjectSources

type GenSchemaPaginatedProjects = PaginatedProjects

type GenSchemaPaginatedQueryHistoryEntries = PaginatedQueryHistoryEntries

type GenSchemaPaginatedQueryJobs = PaginatedQueryJobs

type GenSchemaPaginatedRecentResources = PaginatedRecentResources

type GenSchemaPaginatedRowFilterBindings = PaginatedRowFilterBindings

type GenSchemaPaginatedRowFilters = PaginatedRowFilters

type GenSchemaPaginatedSavedResources = PaginatedSavedResources

type GenSchemaPaginatedSchemaDetails = PaginatedSchemaDetails

type GenSchemaPaginatedSearchResults = PaginatedSearchResults

type GenSchemaPaginatedSemanticModels = PaginatedSemanticModels

type GenSchemaPaginatedStorageCredentials = PaginatedStorageCredentials

type GenSchemaPaginatedTableDetails = PaginatedTableDetails

type GenSchemaPaginatedTagAssignments = PaginatedTagAssignments

type GenSchemaPaginatedTags = PaginatedTags

type GenSchemaPaginatedViewDetails = PaginatedViewDetails

type GenSchemaPaginatedVolumes = PaginatedVolumes

type GenSchemaPaginatedWorkspaces = PaginatedWorkspaces

type GenSchemaPipeline = Pipeline

type GenSchemaPipelineAdmissionMode = PipelineAdmissionMode

type GenSchemaPipelineJob = PipelineJob

type GenSchemaPipelineJobJobType = PipelineJobJobType

type GenSchemaPipelineJobList = PipelineJobList

type GenSchemaPipelineJobRun = PipelineJobRun

type GenSchemaPipelineJobRunList = PipelineJobRunList

type GenSchemaPipelineJobRunStatus = PipelineJobRunStatus

type GenSchemaPipelineModelProvenance = PipelineModelProvenance

type GenSchemaPipelineNotebookProvenance = PipelineNotebookProvenance

type GenSchemaPipelineNotificationWebhook = PipelineNotificationWebhook

type GenSchemaPipelineRun = PipelineRun

type GenSchemaPipelineRunEvent = PipelineRunEvent

type GenSchemaPipelineRunEventList = PipelineRunEventList

type GenSchemaPipelineRunProvenance = PipelineRunProvenance

type GenSchemaPipelineRunStatus = PipelineRunStatus

type GenSchemaPipelineRunTriggerType = PipelineRunTriggerType

type GenSchemaPlanRebuildRequest = PlanRebuildRequest

type GenSchemaPrincipal = Principal

type GenSchemaPrincipalType = PrincipalType

type GenSchemaPrivilegeGrant = PrivilegeGrant

type GenSchemaProductAdoptionSummary = ProductAdoptionSummary

type GenSchemaProductContract = ProductContract

type GenSchemaProductDependencyList = ProductDependencyList

type GenSchemaProductDomain = ProductDomain

type GenSchemaProductEvent = ProductEvent

type GenSchemaProductEventList = ProductEventList

type GenSchemaProductOutput = ProductOutput

type GenSchemaProductOutputList = ProductOutputList

type GenSchemaProductPortfolioGroup = ProductPortfolioGroup

type GenSchemaProductPortfolioReport = ProductPortfolioReport

type GenSchemaProductSLO = ProductSLO

type GenSchemaProductScorecard = ProductScorecard

type GenSchemaProductScorecardList = ProductScorecardList

type GenSchemaProductSemanticEntrypoint = ProductSemanticEntrypoint

type GenSchemaProductSemanticEntrypointList = ProductSemanticEntrypointList

type GenSchemaProductSubscription = ProductSubscription

type GenSchemaProductSubscriptionList = ProductSubscriptionList

type GenSchemaProductTeam = ProductTeam

type GenSchemaProject = Project

type GenSchemaProjectDependency = ProjectDependency

type GenSchemaProjectKind = ProjectKind

type GenSchemaProjectRelease = ProjectRelease

type GenSchemaProjectSeed = ProjectSeed

type GenSchemaPromoteNotebookRequest = PromoteNotebookRequest

type GenSchemaPurgeLineageRequest = PurgeLineageRequest

type GenSchemaPurgeLineageResponse = PurgeLineageResponse

type GenSchemaQueryHistoryEntry = QueryHistoryEntry

type GenSchemaQueryJob = QueryJob

type GenSchemaQueryJobStatus = QueryJobStatus

type GenSchemaQueryRequest = QueryRequest

type GenSchemaQueryResult = QueryResult

type GenSchemaRebuildPlan = RebuildPlan

type GenSchemaRebuildPlanItem = RebuildPlanItem

type GenSchemaRecentResource = RecentResource

type GenSchemaReorderCellsRequest = ReorderCellsRequest

type GenSchemaRepairPipelineRunRequest = RepairPipelineRunRequest

type GenSchemaResolvedDashboardDetail = ResolvedDashboardDetail

type GenSchemaResolvedDashboardWidget = ResolvedDashboardWidget

type GenSchemaRowFilter = RowFilter

type GenSchemaRowFilterBinding = RowFilterBinding

type GenSchemaRowFilterBindingRequest = RowFilterBindingRequest

type GenSchemaRunAllResult = RunAllResult

type GenSchemaSavedResource = SavedResource

type GenSchemaSchemaDetail = SchemaDetail

type GenSchemaSearchResult = SearchResult

type GenSchemaSeedFormat = SeedFormat

type GenSchemaSemanticMetric = SemanticMetric

type GenSchemaSemanticMetricExpressionMode = SemanticMetricExpressionMode

type GenSchemaSemanticMetricList = SemanticMetricList

type GenSchemaSemanticMetricMetricType = SemanticMetricMetricType

type GenSchemaSemanticModel = SemanticModel

type GenSchemaSemanticPreAggregation = SemanticPreAggregation

type GenSchemaSemanticPreAggregationList = SemanticPreAggregationList

type GenSchemaSemanticRelationship = SemanticRelationship

type GenSchemaSemanticRelationshipList = SemanticRelationshipList

type GenSchemaSemanticRelationshipRelationshipType = SemanticRelationshipRelationshipType

type GenSchemaSetDefaultCatalogRequest = SetDefaultCatalogRequest

type GenSchemaShareFolderRequest = ShareFolderRequest

type GenSchemaShareNotebookRequest = ShareNotebookRequest

type GenSchemaSourceDefinition = SourceDefinition

type GenSchemaSourceFreshnessPolicy = SourceFreshnessPolicy

type GenSchemaSourceFreshnessStatus = SourceFreshnessStatus

type GenSchemaStorageCredential = StorageCredential

type GenSchemaStorageCredentialType = StorageCredentialType

type GenSchemaStorageType = StorageType

type GenSchemaSubmitQueryRequest = SubmitQueryRequest

type GenSchemaSubmitQueryResponse = SubmitQueryResponse

type GenSchemaTableDetail = TableDetail

type GenSchemaTableStatistics = TableStatistics

type GenSchemaTabularColumn = TabularColumn

type GenSchemaTag = Tag

type GenSchemaTagAssignment = TagAssignment

type GenSchemaTagAssignmentSecurableType = TagAssignmentSecurableType

type GenSchemaTriggerAssetMaterializationRequest = TriggerAssetMaterializationRequest

type GenSchemaTriggerModelRunRequest = TriggerModelRunRequest

type GenSchemaTriggerPipelineRunRequest = TriggerPipelineRunRequest

type GenSchemaURLStyle = URLStyle

type GenSchemaUpdateAssetRequest = UpdateAssetRequest

type GenSchemaUpdateCatalogRegistrationRequest = UpdateCatalogRegistrationRequest

type GenSchemaUpdateCellRequest = UpdateCellRequest

type GenSchemaUpdateColumnMaskRequest = UpdateColumnMaskRequest

type GenSchemaUpdateColumnRequest = UpdateColumnRequest

type GenSchemaUpdateComputeEndpointRequest = UpdateComputeEndpointRequest

type GenSchemaUpdateDashboardRequest = UpdateDashboardRequest

type GenSchemaUpdateDashboardWidgetRequest = UpdateDashboardWidgetRequest

type GenSchemaUpdateDataProductRequest = UpdateDataProductRequest

type GenSchemaUpdateEnvironmentRequest = UpdateEnvironmentRequest

type GenSchemaUpdateExternalLocationRequest = UpdateExternalLocationRequest

type GenSchemaUpdateFolderRequest = UpdateFolderRequest

type GenSchemaUpdateGroupRequest = UpdateGroupRequest

type GenSchemaUpdateMacroRequest = UpdateMacroRequest

type GenSchemaUpdateModelRequest = UpdateModelRequest

type GenSchemaUpdateNotebookRequest = UpdateNotebookRequest

type GenSchemaUpdatePipelineJobRequest = UpdatePipelineJobRequest

type GenSchemaUpdatePipelineRequest = UpdatePipelineRequest

type GenSchemaUpdatePrincipalRequest = UpdatePrincipalRequest

type GenSchemaUpdateProductDomainRequest = UpdateProductDomainRequest

type GenSchemaUpdateProductTeamRequest = UpdateProductTeamRequest

type GenSchemaUpdateProjectMacroRequest = UpdateProjectMacroRequest

type GenSchemaUpdateProjectRequest = UpdateProjectRequest

type GenSchemaUpdateProjectSeedRequest = UpdateProjectSeedRequest

type GenSchemaUpdateRowFilterRequest = UpdateRowFilterRequest

type GenSchemaUpdateSchemaRequest = UpdateSchemaRequest

type GenSchemaUpdateSemanticMetricRequest = UpdateSemanticMetricRequest

type GenSchemaUpdateSemanticModelRequest = UpdateSemanticModelRequest

type GenSchemaUpdateSemanticPreAggregationRequest = UpdateSemanticPreAggregationRequest

type GenSchemaUpdateSemanticRelationshipRequest = UpdateSemanticRelationshipRequest

type GenSchemaUpdateSourceDefinitionRequest = UpdateSourceDefinitionRequest

type GenSchemaUpdateStorageCredentialRequest = UpdateStorageCredentialRequest

type GenSchemaUpdateTableRequest = UpdateTableRequest

type GenSchemaUpdateTagRequest = UpdateTagRequest

type GenSchemaUpdateViewRequest = UpdateViewRequest

type GenSchemaUpdateVolumeRequest = UpdateVolumeRequest

type GenSchemaUpdateWorkspaceRequest = UpdateWorkspaceRequest

type GenSchemaUploadUrlRequest = UploadUrlRequest

type GenSchemaUploadUrlResponse = UploadUrlResponse

type GenSchemaVersionedObjectSummary = VersionedObjectSummary

type GenSchemaViewDetail = ViewDetail

type GenSchemaVisualChartType = VisualChartType

type GenSchemaVisualEncodings = VisualEncodings

type GenSchemaVisualEncodingsUpdate = VisualEncodingsUpdate

type GenSchemaVisualFieldBinding = VisualFieldBinding

type GenSchemaVisualFieldBindingUpdate = VisualFieldBindingUpdate

type GenSchemaVisualLegendPosition = VisualLegendPosition

type GenSchemaVisualOutputKind = VisualOutputKind

type GenSchemaVisualSpec = VisualSpec

type GenSchemaVisualSpecUpdate = VisualSpecUpdate

type GenSchemaVolumeDetail = VolumeDetail

type GenSchemaWorkspace = Workspace

type GenSchemaWorkspaceKind = WorkspaceKind

type GenSchemaWorkspaceMember = WorkspaceMember

type GenSchemaWorkspaceMemberList = WorkspaceMemberList
