// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AddGroupMemberRequest defines model for AddGroupMemberRequest.
type AddGroupMemberRequest struct {
	MemberId   int64  `json:"member_id"`
	MemberType string `json:"member_type"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action         *string    `json:"action,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	DurationMs     *int64     `json:"duration_ms"`
	ErrorMessage   *string    `json:"error_message"`
	Id             *int64     `json:"id,omitempty"`
	OriginalSql    *string    `json:"original_sql"`
	PrincipalName  *string    `json:"principal_name,omitempty"`
	RewrittenSql   *string    `json:"rewritten_sql"`
	StatementType  *string    `json:"statement_type"`
	Status         *string    `json:"status,omitempty"`
	TablesAccessed *[]string  `json:"tables_accessed,omitempty"`
}

// BindingRequest defines model for BindingRequest.
type BindingRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
}

// CatalogInfo defines model for CatalogInfo.
type CatalogInfo struct {
	Comment   *string    `json:"comment,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// Column defines model for Column.
type Column struct {
	Id      *int64  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	TableId *int64  `json:"table_id,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// ColumnDetail defines model for ColumnDetail.
type ColumnDetail struct {
	Comment    *string            `json:"comment,omitempty"`
	Name       *string            `json:"name,omitempty"`
	Position   *int               `json:"position,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Type       *string            `json:"type,omitempty"`
}

// ColumnMask defines model for ColumnMask.
type ColumnMask struct {
	ColumnName     *string    `json:"column_name,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Description    *string    `json:"description,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	MaskExpression *string    `json:"mask_expression,omitempty"`
	TableId        *int64     `json:"table_id,omitempty"`
}

// ColumnMaskBindingRequest defines model for ColumnMaskBindingRequest.
type ColumnMaskBindingRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	SeeOriginal   *bool  `json:"see_original,omitempty"`
}

// CommitIngestionRequest defines model for CommitIngestionRequest.
type CommitIngestionRequest struct {
	Options *IngestionOptions `json:"options,omitempty"`

	// S3Keys S3 keys returned from upload-url to register.
	S3Keys []string `json:"s3_keys"`
}

// CreateColumnDef defines model for CreateColumnDef.
type CreateColumnDef struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// CreateColumnMaskRequest defines model for CreateColumnMaskRequest.
type CreateColumnMaskRequest struct {
	ColumnName     string  `json:"column_name"`
	Description    *string `json:"description,omitempty"`
	MaskExpression string  `json:"mask_expression"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreatePrincipalRequest defines model for CreatePrincipalRequest.
type CreatePrincipalRequest struct {
	IsAdmin *bool   `json:"is_admin,omitempty"`
	Name    string  `json:"name"`
	Type    *string `json:"type,omitempty"`
}

// CreateRowFilterRequest defines model for CreateRowFilterRequest.
type CreateRowFilterRequest struct {
	Description *string `json:"description,omitempty"`
	FilterSql   string  `json:"filter_sql"`
}

// CreateSchemaRequest defines model for CreateSchemaRequest.
type CreateSchemaRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Name       string             `json:"name"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// CreateTableApiRequest defines model for CreateTableApiRequest.
type CreateTableApiRequest struct {
	Columns []CreateColumnDef `json:"columns"`
	Comment *string           `json:"comment,omitempty"`
	Name    string            `json:"name"`
}

// CreateTagAssignmentRequest defines model for CreateTagAssignmentRequest.
type CreateTagAssignmentRequest struct {
	ColumnName    *string `json:"column_name,omitempty"`
	SecurableId   int64   `json:"securable_id"`
	SecurableType string  `json:"securable_type"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Key   string  `json:"key"`
	Value *string `json:"value,omitempty"`
}

// CreateViewRequest defines model for CreateViewRequest.
type CreateViewRequest struct {
	Comment        *string `json:"comment,omitempty"`
	Name           string  `json:"name"`
	ViewDefinition string  `json:"view_definition"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GrantRequest defines model for GrantRequest.
type GrantRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	Privilege     string `json:"privilege"`
	SecurableId   int64  `json:"securable_id"`
	SecurableType string `json:"securable_type"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	GroupId    *int64  `json:"group_id,omitempty"`
	MemberId   *int64  `json:"member_id,omitempty"`
	MemberType *string `json:"member_type,omitempty"`
}

// IngestionOptions defines model for IngestionOptions.
type IngestionOptions struct {
	// AllowMissingColumns Allow columns in the table that are missing from the Parquet file.
	AllowMissingColumns *bool `json:"allow_missing_columns,omitempty"`

	// IgnoreExtraColumns Ignore columns in the Parquet file not present in the table.
	IgnoreExtraColumns *bool `json:"ignore_extra_columns,omitempty"`
}

// IngestionResult defines model for IngestionResult.
type IngestionResult struct {
	// FilesRegistered Number of files successfully registered.
	FilesRegistered *int `json:"files_registered,omitempty"`

	// FilesSkipped Number of files skipped (e.g., empty files).
	FilesSkipped *int    `json:"files_skipped,omitempty"`
	Schema       *string `json:"schema,omitempty"`
	Table        *string `json:"table,omitempty"`
}

// LineageEdge defines model for LineageEdge.
type LineageEdge struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EdgeType Edge type: READ, WRITE, READ_WRITE
	EdgeType      *string `json:"edge_type,omitempty"`
	Id            *int64  `json:"id,omitempty"`
	PrincipalName *string `json:"principal_name,omitempty"`
	SourceTable   *string `json:"source_table,omitempty"`
	TargetTable   *string `json:"target_table"`
}

// LineageNode defines model for LineageNode.
type LineageNode struct {
	Downstream *[]LineageEdge `json:"downstream,omitempty"`
	TableName  *string        `json:"table_name,omitempty"`
	Upstream   *[]LineageEdge `json:"upstream,omitempty"`
}

// LoadExternalRequest defines model for LoadExternalRequest.
type LoadExternalRequest struct {
	Options *IngestionOptions `json:"options,omitempty"`

	// Paths S3 paths or globs to register.
	Paths []string `json:"paths"`
}

// ManifestColumn defines model for ManifestColumn.
type ManifestColumn struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// ManifestRequest defines model for ManifestRequest.
type ManifestRequest struct {
	Schema *string `json:"schema,omitempty"`
	Table  string  `json:"table"`
}

// ManifestResponse defines model for ManifestResponse.
type ManifestResponse struct {
	ColumnMasks *map[string]string `json:"column_masks,omitempty"`
	Columns     *[]ManifestColumn  `json:"columns,omitempty"`
	ExpiresAt   *time.Time         `json:"expires_at,omitempty"`
	Files       *[]string          `json:"files,omitempty"`
	RowFilters  *[]string          `json:"row_filters,omitempty"`
	Schema      *string            `json:"schema,omitempty"`
	Table       *string            `json:"table,omitempty"`
}

// MetastoreSummary defines model for MetastoreSummary.
type MetastoreSummary struct {
	CatalogName    *string `json:"catalog_name,omitempty"`
	DataPath       *string `json:"data_path,omitempty"`
	MetastoreType  *string `json:"metastore_type,omitempty"`
	SchemaCount    *int64  `json:"schema_count,omitempty"`
	StorageBackend *string `json:"storage_backend,omitempty"`
	TableCount     *int64  `json:"table_count,omitempty"`
}

// PaginatedAuditLogs defines model for PaginatedAuditLogs.
type PaginatedAuditLogs struct {
	Data          *[]AuditEntry `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// PaginatedColumnDetails defines model for PaginatedColumnDetails.
type PaginatedColumnDetails struct {
	Data          *[]ColumnDetail `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// PaginatedColumnMasks defines model for PaginatedColumnMasks.
type PaginatedColumnMasks struct {
	Data          *[]ColumnMask `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// PaginatedColumns defines model for PaginatedColumns.
type PaginatedColumns struct {
	Data          *[]Column `json:"data,omitempty"`
	NextPageToken *string   `json:"next_page_token,omitempty"`
}

// PaginatedGrants defines model for PaginatedGrants.
type PaginatedGrants struct {
	Data          *[]PrivilegeGrant `json:"data,omitempty"`
	NextPageToken *string           `json:"next_page_token,omitempty"`
}

// PaginatedGroupMembers defines model for PaginatedGroupMembers.
type PaginatedGroupMembers struct {
	Data          *[]GroupMember `json:"data,omitempty"`
	NextPageToken *string        `json:"next_page_token,omitempty"`
}

// PaginatedGroups defines model for PaginatedGroups.
type PaginatedGroups struct {
	Data          *[]Group `json:"data,omitempty"`
	NextPageToken *string  `json:"next_page_token,omitempty"`
}

// PaginatedLineageEdges defines model for PaginatedLineageEdges.
type PaginatedLineageEdges struct {
	Data          *[]LineageEdge `json:"data,omitempty"`
	NextPageToken *string        `json:"next_page_token,omitempty"`
}

// PaginatedPrincipals defines model for PaginatedPrincipals.
type PaginatedPrincipals struct {
	Data          *[]Principal `json:"data,omitempty"`
	NextPageToken *string      `json:"next_page_token,omitempty"`
}

// PaginatedQueryHistory defines model for PaginatedQueryHistory.
type PaginatedQueryHistory struct {
	Data          *[]QueryHistoryEntry `json:"data,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

// PaginatedRowFilters defines model for PaginatedRowFilters.
type PaginatedRowFilters struct {
	Data          *[]RowFilter `json:"data,omitempty"`
	NextPageToken *string      `json:"next_page_token,omitempty"`
}

// PaginatedSchemaDetails defines model for PaginatedSchemaDetails.
type PaginatedSchemaDetails struct {
	Data          *[]SchemaDetail `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// PaginatedSchemas defines model for PaginatedSchemas.
type PaginatedSchemas struct {
	Data          *[]Schema `json:"data,omitempty"`
	NextPageToken *string   `json:"next_page_token,omitempty"`
}

// PaginatedSearchResults defines model for PaginatedSearchResults.
type PaginatedSearchResults struct {
	Data          *[]SearchResult `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// PaginatedTableDetails defines model for PaginatedTableDetails.
type PaginatedTableDetails struct {
	Data          *[]TableDetail `json:"data,omitempty"`
	NextPageToken *string        `json:"next_page_token,omitempty"`
}

// PaginatedTables defines model for PaginatedTables.
type PaginatedTables struct {
	Data          *[]Table `json:"data,omitempty"`
	NextPageToken *string  `json:"next_page_token,omitempty"`
}

// PaginatedTags defines model for PaginatedTags.
type PaginatedTags struct {
	Data          *[]Tag  `json:"data,omitempty"`
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PaginatedViewDetails defines model for PaginatedViewDetails.
type PaginatedViewDetails struct {
	Data          *[]ViewDetail `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// Principal defines model for Principal.
type Principal struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	IsAdmin   *bool      `json:"is_admin,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Type      *string    `json:"type,omitempty"`
}

// PrivilegeGrant defines model for PrivilegeGrant.
type PrivilegeGrant struct {
	GrantedAt     *time.Time `json:"granted_at,omitempty"`
	GrantedBy     *int64     `json:"granted_by"`
	Id            *int64     `json:"id,omitempty"`
	PrincipalId   *int64     `json:"principal_id,omitempty"`
	PrincipalType *string    `json:"principal_type,omitempty"`
	Privilege     *string    `json:"privilege,omitempty"`
	SecurableId   *int64     `json:"securable_id,omitempty"`
	SecurableType *string    `json:"securable_type,omitempty"`
}

// PurgeLineageRequest defines model for PurgeLineageRequest.
type PurgeLineageRequest struct {
	// OlderThanDays Delete lineage edges older than this many days.
	OlderThanDays int `json:"older_than_days"`
}

// PurgeLineageResponse defines model for PurgeLineageResponse.
type PurgeLineageResponse struct {
	DeletedCount *int64 `json:"deleted_count,omitempty"`
}

// QueryHistoryEntry defines model for QueryHistoryEntry.
type QueryHistoryEntry struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	DurationMs     *int64     `json:"duration_ms"`
	ErrorMessage   *string    `json:"error_message"`
	Id             *int64     `json:"id,omitempty"`
	OriginalSql    *string    `json:"original_sql"`
	PrincipalName  *string    `json:"principal_name,omitempty"`
	RewrittenSql   *string    `json:"rewritten_sql"`
	RowsReturned   *int64     `json:"rows_returned"`
	StatementType  *string    `json:"statement_type"`
	Status         *string    `json:"status,omitempty"`
	TablesAccessed *[]string  `json:"tables_accessed,omitempty"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Sql string `json:"sql"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Columns  *[]string        `json:"columns,omitempty"`
	RowCount *int             `json:"row_count,omitempty"`
	Rows     *[][]interface{} `json:"rows,omitempty"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	Privilege     string `json:"privilege"`
	SecurableId   int64  `json:"securable_id"`
	SecurableType string `json:"securable_type"`
}

// RowFilter defines model for RowFilter.
type RowFilter struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	FilterSql   *string    `json:"filter_sql,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	TableId     *int64     `json:"table_id,omitempty"`
}

// Schema defines model for Schema.
type Schema struct {
	Id   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// SchemaDetail defines model for SchemaDetail.
type SchemaDetail struct {
	CatalogName *string            `json:"catalog_name,omitempty"`
	Comment     *string            `json:"comment,omitempty"`
	CreatedAt   *time.Time         `json:"created_at,omitempty"`
	DeletedAt   *time.Time         `json:"deleted_at"`
	Name        *string            `json:"name,omitempty"`
	Owner       *string            `json:"owner,omitempty"`
	Properties  *map[string]string `json:"properties,omitempty"`
	SchemaId    *int64             `json:"schema_id,omitempty"`
	Tags        *[]Tag             `json:"tags,omitempty"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Comment *string `json:"comment"`

	// MatchField Field that matched: name, comment, property, or tag
	MatchField *string `json:"match_field,omitempty"`
	Name       *string `json:"name,omitempty"`
	SchemaName *string `json:"schema_name"`
	TableName  *string `json:"table_name"`

	// Type Object type: schema, table, or column
	Type *string `json:"type,omitempty"`
}

// SetAdminRequest defines model for SetAdminRequest.
type SetAdminRequest struct {
	IsAdmin bool `json:"is_admin"`
}

// Table defines model for Table.
type Table struct {
	Id       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	SchemaId *int64  `json:"schema_id,omitempty"`
}

// TableDetail defines model for TableDetail.
type TableDetail struct {
	CatalogName *string            `json:"catalog_name,omitempty"`
	Columns     *[]ColumnDetail    `json:"columns,omitempty"`
	Comment     *string            `json:"comment,omitempty"`
	CreatedAt   *time.Time         `json:"created_at,omitempty"`
	DeletedAt   *time.Time         `json:"deleted_at"`
	Name        *string            `json:"name,omitempty"`
	Owner       *string            `json:"owner,omitempty"`
	Properties  *map[string]string `json:"properties,omitempty"`
	SchemaName  *string            `json:"schema_name,omitempty"`
	Statistics  *TableStatistics   `json:"statistics,omitempty"`
	TableId     *int64             `json:"table_id,omitempty"`
	TableType   *string            `json:"table_type,omitempty"`
	Tags        *[]Tag             `json:"tags,omitempty"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
}

// TableStatistics defines model for TableStatistics.
type TableStatistics struct {
	ColumnCount    *int64     `json:"column_count"`
	LastProfiledAt *time.Time `json:"last_profiled_at"`
	ProfiledBy     *string    `json:"profiled_by,omitempty"`
	RowCount       *int64     `json:"row_count"`
	SizeBytes      *int64     `json:"size_bytes"`
}

// Tag defines model for Tag.
type Tag struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	CreatedBy *string    `json:"created_by,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Key       *string    `json:"key,omitempty"`
	Value     *string    `json:"value"`
}

// TagAssignment defines model for TagAssignment.
type TagAssignment struct {
	AssignedAt    *time.Time `json:"assigned_at,omitempty"`
	AssignedBy    *string    `json:"assigned_by,omitempty"`
	ColumnName    *string    `json:"column_name"`
	Id            *int64     `json:"id,omitempty"`
	SecurableId   *int64     `json:"securable_id,omitempty"`
	SecurableType *string    `json:"securable_type,omitempty"`
	TagId         *int64     `json:"tag_id,omitempty"`
}

// UpdateCatalogRequest defines model for UpdateCatalogRequest.
type UpdateCatalogRequest struct {
	Comment *string `json:"comment,omitempty"`
}

// UpdateColumnRequest defines model for UpdateColumnRequest.
type UpdateColumnRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// UpdateSchemaRequest defines model for UpdateSchemaRequest.
type UpdateSchemaRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// UpdateTableRequest defines model for UpdateTableRequest.
type UpdateTableRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Owner      *string            `json:"owner,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// UpdateViewRequest defines model for UpdateViewRequest.
type UpdateViewRequest struct {
	Comment        *string            `json:"comment,omitempty"`
	Properties     *map[string]string `json:"properties,omitempty"`
	ViewDefinition *string            `json:"view_definition,omitempty"`
}

// UploadUrlRequest defines model for UploadUrlRequest.
type UploadUrlRequest struct {
	// Filename Optional filename hint for the uploaded file.
	Filename *string `json:"filename,omitempty"`
}

// UploadUrlResponse defines model for UploadUrlResponse.
type UploadUrlResponse struct {
	// ExpiresAt When the presigned URL expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// S3Key The S3 key where the file will be stored.
	S3Key *string `json:"s3_key,omitempty"`

	// UploadUrl Presigned PUT URL for uploading the Parquet file.
	UploadUrl *string `json:"upload_url,omitempty"`
}

// ViewDetail defines model for ViewDetail.
type ViewDetail struct {
	CatalogName    *string            `json:"catalog_name,omitempty"`
	Comment        *string            `json:"comment"`
	CreatedAt      *time.Time         `json:"created_at,omitempty"`
	Id             *int64             `json:"id,omitempty"`
	Name           *string            `json:"name,omitempty"`
	Owner          *string            `json:"owner,omitempty"`
	Properties     *map[string]string `json:"properties,omitempty"`
	SchemaId       *int64             `json:"schema_id,omitempty"`
	SchemaName     *string            `json:"schema_name,omitempty"`
	SourceTables   *[]string          `json:"source_tables,omitempty"`
	UpdatedAt      *time.Time         `json:"updated_at,omitempty"`
	ViewDefinition *string            `json:"view_definition,omitempty"`
}

// MaxResults defines model for MaxResults.
type MaxResults = int

// PageToken defines model for PageToken.
type PageToken = string

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	PrincipalName *string `form:"principal_name,omitempty" json:"principal_name,omitempty"`
	Action        *string `form:"action,omitempty" json:"action,omitempty"`
	Status        *string `form:"status,omitempty" json:"status,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListCatalogSchemasParams defines parameters for ListCatalogSchemas.
type ListCatalogSchemasParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// DeleteSchemaParams defines parameters for DeleteSchema.
type DeleteSchemaParams struct {
	// Force Force deletion even if the schema contains tables.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// ListCatalogTablesParams defines parameters for ListCatalogTables.
type ListCatalogTablesParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListTableColumnsParams defines parameters for ListTableColumns.
type ListTableColumnsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListViewsParams defines parameters for ListViews.
type ListViewsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListGrantsParams defines parameters for ListGrants.
type ListGrantsParams struct {
	PrincipalId   *int64  `form:"principal_id,omitempty" json:"principal_id,omitempty"`
	PrincipalType *string `form:"principal_type,omitempty" json:"principal_type,omitempty"`
	SecurableType *string `form:"securable_type,omitempty" json:"securable_type,omitempty"`
	SecurableId   *int64  `form:"securable_id,omitempty" json:"securable_id,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListGroupMembersParams defines parameters for ListGroupMembers.
type ListGroupMembersParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetTableLineageParams defines parameters for GetTableLineage.
type GetTableLineageParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetDownstreamLineageParams defines parameters for GetDownstreamLineage.
type GetDownstreamLineageParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetUpstreamLineageParams defines parameters for GetUpstreamLineage.
type GetUpstreamLineageParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListPrincipalsParams defines parameters for ListPrincipals.
type ListPrincipalsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListQueryHistoryParams defines parameters for ListQueryHistory.
type ListQueryHistoryParams struct {
	PrincipalName *string    `form:"principal_name,omitempty" json:"principal_name,omitempty"`
	Status        *string    `form:"status,omitempty" json:"status,omitempty"`
	From          *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To            *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListSchemasParams defines parameters for ListSchemas.
type ListSchemasParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListTablesParams defines parameters for ListTables.
type ListTablesParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// SearchCatalogParams defines parameters for SearchCatalog.
type SearchCatalogParams struct {
	Query string `form:"query" json:"query"`

	// Type Filter by object type: schema, table, or column
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListColumnsParams defines parameters for ListColumns.
type ListColumnsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListColumnMasksParams defines parameters for ListColumnMasks.
type ListColumnMasksParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListRowFiltersParams defines parameters for ListRowFilters.
type ListRowFiltersParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// UpdateCatalogJSONRequestBody defines body for UpdateCatalog for application/json ContentType.
type UpdateCatalogJSONRequestBody = UpdateCatalogRequest

// CreateSchemaJSONRequestBody defines body for CreateSchema for application/json ContentType.
type CreateSchemaJSONRequestBody = CreateSchemaRequest

// UpdateSchemaMetadataJSONRequestBody defines body for UpdateSchemaMetadata for application/json ContentType.
type UpdateSchemaMetadataJSONRequestBody = UpdateSchemaRequest

// CreateCatalogTableJSONRequestBody defines body for CreateCatalogTable for application/json ContentType.
type CreateCatalogTableJSONRequestBody = CreateTableApiRequest

// UpdateTableMetadataJSONRequestBody defines body for UpdateTableMetadata for application/json ContentType.
type UpdateTableMetadataJSONRequestBody = UpdateTableRequest

// UpdateColumnMetadataJSONRequestBody defines body for UpdateColumnMetadata for application/json ContentType.
type UpdateColumnMetadataJSONRequestBody = UpdateColumnRequest

// CommitIngestionJSONRequestBody defines body for CommitIngestion for application/json ContentType.
type CommitIngestionJSONRequestBody = CommitIngestionRequest

// LoadExternalFilesJSONRequestBody defines body for LoadExternalFiles for application/json ContentType.
type LoadExternalFilesJSONRequestBody = LoadExternalRequest

// RequestUploadUrlJSONRequestBody defines body for RequestUploadUrl for application/json ContentType.
type RequestUploadUrlJSONRequestBody = UploadUrlRequest

// CreateViewJSONRequestBody defines body for CreateView for application/json ContentType.
type CreateViewJSONRequestBody = CreateViewRequest

// UpdateViewJSONRequestBody defines body for UpdateView for application/json ContentType.
type UpdateViewJSONRequestBody = UpdateViewRequest

// UnbindColumnMaskJSONRequestBody defines body for UnbindColumnMask for application/json ContentType.
type UnbindColumnMaskJSONRequestBody = BindingRequest

// BindColumnMaskJSONRequestBody defines body for BindColumnMask for application/json ContentType.
type BindColumnMaskJSONRequestBody = ColumnMaskBindingRequest

// RevokePrivilegeJSONRequestBody defines body for RevokePrivilege for application/json ContentType.
type RevokePrivilegeJSONRequestBody = RevokeRequest

// GrantPrivilegeJSONRequestBody defines body for GrantPrivilege for application/json ContentType.
type GrantPrivilegeJSONRequestBody = GrantRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// RemoveGroupMemberJSONRequestBody defines body for RemoveGroupMember for application/json ContentType.
type RemoveGroupMemberJSONRequestBody = AddGroupMemberRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddGroupMemberRequest

// PurgeLineageJSONRequestBody defines body for PurgeLineage for application/json ContentType.
type PurgeLineageJSONRequestBody = PurgeLineageRequest

// GetManifestJSONRequestBody defines body for GetManifest for application/json ContentType.
type GetManifestJSONRequestBody = ManifestRequest

// CreatePrincipalJSONRequestBody defines body for CreatePrincipal for application/json ContentType.
type CreatePrincipalJSONRequestBody = CreatePrincipalRequest

// SetAdminJSONRequestBody defines body for SetAdmin for application/json ContentType.
type SetAdminJSONRequestBody = SetAdminRequest

// ExecuteQueryJSONRequestBody defines body for ExecuteQuery for application/json ContentType.
type ExecuteQueryJSONRequestBody = QueryRequest

// UnbindRowFilterJSONRequestBody defines body for UnbindRowFilter for application/json ContentType.
type UnbindRowFilterJSONRequestBody = BindingRequest

// BindRowFilterJSONRequestBody defines body for BindRowFilter for application/json ContentType.
type BindRowFilterJSONRequestBody = BindingRequest

// CreateColumnMaskJSONRequestBody defines body for CreateColumnMask for application/json ContentType.
type CreateColumnMaskJSONRequestBody = CreateColumnMaskRequest

// CreateRowFilterJSONRequestBody defines body for CreateRowFilter for application/json ContentType.
type CreateRowFilterJSONRequestBody = CreateRowFilterRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// AssignTagJSONRequestBody defines body for AssignTag for application/json ContentType.
type AssignTagJSONRequestBody = CreateTagAssignmentRequest
