// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CatalogRegistrationMetastoreType.
const (
	CatalogRegistrationMetastoreTypePostgres CatalogRegistrationMetastoreType = "postgres"
	CatalogRegistrationMetastoreTypeSqlite   CatalogRegistrationMetastoreType = "sqlite"
)

// Defines values for CatalogRegistrationStatus.
const (
	CatalogRegistrationStatusACTIVE   CatalogRegistrationStatus = "ACTIVE"
	CatalogRegistrationStatusDETACHED CatalogRegistrationStatus = "DETACHED"
	CatalogRegistrationStatusERROR    CatalogRegistrationStatus = "ERROR"
)

// Defines values for ComputeAssignmentPrincipalType.
const (
	ComputeAssignmentPrincipalTypeGroup ComputeAssignmentPrincipalType = "group"
	ComputeAssignmentPrincipalTypeUser  ComputeAssignmentPrincipalType = "user"
)

// Defines values for ComputeEndpointSize.
const (
	ComputeEndpointSizeLARGE  ComputeEndpointSize = "LARGE"
	ComputeEndpointSizeMEDIUM ComputeEndpointSize = "MEDIUM"
	ComputeEndpointSizeSMALL  ComputeEndpointSize = "SMALL"
)

// Defines values for ComputeEndpointStatus.
const (
	ComputeEndpointStatusACTIVE   ComputeEndpointStatus = "ACTIVE"
	ComputeEndpointStatusERROR    ComputeEndpointStatus = "ERROR"
	ComputeEndpointStatusINACTIVE ComputeEndpointStatus = "INACTIVE"
	ComputeEndpointStatusSTARTING ComputeEndpointStatus = "STARTING"
	ComputeEndpointStatusSTOPPING ComputeEndpointStatus = "STOPPING"
)

// Defines values for ComputeEndpointType.
const (
	ComputeEndpointTypeLOCAL  ComputeEndpointType = "LOCAL"
	ComputeEndpointTypeREMOTE ComputeEndpointType = "REMOTE"
)

// Defines values for CreateCatalogRequestMetastoreType.
const (
	CreateCatalogRequestMetastoreTypePostgres CreateCatalogRequestMetastoreType = "postgres"
	CreateCatalogRequestMetastoreTypeSqlite   CreateCatalogRequestMetastoreType = "sqlite"
)

// Defines values for CreateComputeAssignmentRequestPrincipalType.
const (
	CreateComputeAssignmentRequestPrincipalTypeGroup CreateComputeAssignmentRequestPrincipalType = "group"
	CreateComputeAssignmentRequestPrincipalTypeUser  CreateComputeAssignmentRequestPrincipalType = "user"
)

// Defines values for CreateComputeEndpointRequestSize.
const (
	CreateComputeEndpointRequestSizeLARGE  CreateComputeEndpointRequestSize = "LARGE"
	CreateComputeEndpointRequestSizeMEDIUM CreateComputeEndpointRequestSize = "MEDIUM"
	CreateComputeEndpointRequestSizeSMALL  CreateComputeEndpointRequestSize = "SMALL"
)

// Defines values for CreateComputeEndpointRequestType.
const (
	CreateComputeEndpointRequestTypeLOCAL  CreateComputeEndpointRequestType = "LOCAL"
	CreateComputeEndpointRequestTypeREMOTE CreateComputeEndpointRequestType = "REMOTE"
)

// Defines values for CreateExternalLocationRequestStorageType.
const (
	CreateExternalLocationRequestStorageTypeS3 CreateExternalLocationRequestStorageType = "S3"
)

// Defines values for CreateStorageCredentialRequestCredentialType.
const (
	CreateStorageCredentialRequestCredentialTypeAZURE CreateStorageCredentialRequestCredentialType = "AZURE"
	CreateStorageCredentialRequestCredentialTypeGCS   CreateStorageCredentialRequestCredentialType = "GCS"
	CreateStorageCredentialRequestCredentialTypeS3    CreateStorageCredentialRequestCredentialType = "S3"
)

// Defines values for CreateTableRequestFileFormat.
const (
	Csv     CreateTableRequestFileFormat = "csv"
	Parquet CreateTableRequestFileFormat = "parquet"
)

// Defines values for CreateTableRequestTableType.
const (
	CreateTableRequestTableTypeEXTERNAL CreateTableRequestTableType = "EXTERNAL"
	CreateTableRequestTableTypeMANAGED  CreateTableRequestTableType = "MANAGED"
)

// Defines values for CreateVolumeRequestVolumeType.
const (
	CreateVolumeRequestVolumeTypeEXTERNAL CreateVolumeRequestVolumeType = "EXTERNAL"
	CreateVolumeRequestVolumeTypeMANAGED  CreateVolumeRequestVolumeType = "MANAGED"
)

// Defines values for StorageCredentialCredentialType.
const (
	AZURE StorageCredentialCredentialType = "AZURE"
	GCS   StorageCredentialCredentialType = "GCS"
	S3    StorageCredentialCredentialType = "S3"
)

// Defines values for UpdateComputeEndpointRequestSize.
const (
	LARGE  UpdateComputeEndpointRequestSize = "LARGE"
	MEDIUM UpdateComputeEndpointRequestSize = "MEDIUM"
	SMALL  UpdateComputeEndpointRequestSize = "SMALL"
)

// Defines values for UpdateComputeEndpointRequestStatus.
const (
	ACTIVE   UpdateComputeEndpointRequestStatus = "ACTIVE"
	ERROR    UpdateComputeEndpointRequestStatus = "ERROR"
	INACTIVE UpdateComputeEndpointRequestStatus = "INACTIVE"
	STARTING UpdateComputeEndpointRequestStatus = "STARTING"
	STOPPING UpdateComputeEndpointRequestStatus = "STOPPING"
)

// Defines values for VolumeDetailVolumeType.
const (
	EXTERNAL VolumeDetailVolumeType = "EXTERNAL"
	MANAGED  VolumeDetailVolumeType = "MANAGED"
)

// APIKeyInfo defines model for APIKeyInfo.
type APIKeyInfo struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	ExpiresAt   *time.Time `json:"expires_at"`
	Id          *int64     `json:"id,omitempty"`
	KeyPrefix   *string    `json:"key_prefix,omitempty"`
	Name        *string    `json:"name,omitempty"`
	PrincipalId *int64     `json:"principal_id,omitempty"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action         *string    `json:"action,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	DurationMs     *int64     `json:"duration_ms"`
	ErrorMessage   *string    `json:"error_message"`
	Id             *int64     `json:"id,omitempty"`
	OriginalSql    *string    `json:"original_sql"`
	PrincipalName  *string    `json:"principal_name,omitempty"`
	RewrittenSql   *string    `json:"rewritten_sql"`
	StatementType  *string    `json:"statement_type"`
	Status         *string    `json:"status,omitempty"`
	TablesAccessed *[]string  `json:"tables_accessed,omitempty"`
}

// CatalogInfo defines model for CatalogInfo.
type CatalogInfo struct {
	Comment   *string    `json:"comment,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Name      *string    `json:"name,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// CatalogRegistration defines model for CatalogRegistration.
type CatalogRegistration struct {
	Comment   *string    `json:"comment,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DataPath Data path (s3://bucket/path/ or local path)
	DataPath string `json:"data_path"`

	// Dsn File path (sqlite) or connection string (postgres)
	Dsn       string `json:"dsn"`
	Id        *int64 `json:"id,omitempty"`
	IsDefault *bool  `json:"is_default,omitempty"`

	// MetastoreType Type of metastore backend
	MetastoreType CatalogRegistrationMetastoreType `json:"metastore_type"`

	// Name DuckDB catalog alias, used in SQL as catalog.schema.table
	Name          string                    `json:"name"`
	Status        CatalogRegistrationStatus `json:"status"`
	StatusMessage *string                   `json:"status_message,omitempty"`
	UpdatedAt     *time.Time                `json:"updated_at,omitempty"`
}

// CatalogRegistrationMetastoreType Type of metastore backend
type CatalogRegistrationMetastoreType string

// CatalogRegistrationStatus defines model for CatalogRegistration.Status.
type CatalogRegistrationStatus string

// CatalogRegistrationList defines model for CatalogRegistrationList.
type CatalogRegistrationList struct {
	Catalogs      *[]CatalogRegistration `json:"catalogs,omitempty"`
	NextPageToken *string                `json:"next_page_token,omitempty"`
	TotalCount    *int64                 `json:"total_count,omitempty"`
}

// CleanupAPIKeysResponse defines model for CleanupAPIKeysResponse.
type CleanupAPIKeysResponse struct {
	DeletedCount *int64 `json:"deleted_count,omitempty"`
}

// ColumnDetail defines model for ColumnDetail.
type ColumnDetail struct {
	Comment *string `json:"comment,omitempty"`
	Name    *string `json:"name,omitempty"`

	// Nullable Whether the column allows NULL values.
	Nullable   *bool              `json:"nullable,omitempty"`
	Position   *int               `json:"position,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
	Type       *string            `json:"type,omitempty"`
}

// ColumnMask defines model for ColumnMask.
type ColumnMask struct {
	ColumnName     *string    `json:"column_name,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Description    *string    `json:"description,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	MaskExpression *string    `json:"mask_expression,omitempty"`
	TableId        *int64     `json:"table_id,omitempty"`
}

// ColumnMaskBindingRequest defines model for ColumnMaskBindingRequest.
type ColumnMaskBindingRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	SeeOriginal   *bool  `json:"see_original,omitempty"`
}

// CommitIngestionRequest defines model for CommitIngestionRequest.
type CommitIngestionRequest struct {
	Options *IngestionOptions `json:"options,omitempty"`

	// S3Keys S3 keys returned from upload-url to register.
	S3Keys []string `json:"s3_keys"`
}

// ComputeAssignment defines model for ComputeAssignment.
type ComputeAssignment struct {
	CreatedAt     *time.Time                      `json:"created_at,omitempty"`
	EndpointId    *int64                          `json:"endpoint_id,omitempty"`
	EndpointName  *string                         `json:"endpoint_name,omitempty"`
	FallbackLocal *bool                           `json:"fallback_local,omitempty"`
	Id            *int64                          `json:"id,omitempty"`
	IsDefault     *bool                           `json:"is_default,omitempty"`
	PrincipalId   *int64                          `json:"principal_id,omitempty"`
	PrincipalType *ComputeAssignmentPrincipalType `json:"principal_type,omitempty"`
}

// ComputeAssignmentPrincipalType defines model for ComputeAssignment.PrincipalType.
type ComputeAssignmentPrincipalType string

// ComputeEndpoint defines model for ComputeEndpoint.
type ComputeEndpoint struct {
	CreatedAt   *time.Time             `json:"created_at,omitempty"`
	ExternalId  *openapi_types.UUID    `json:"external_id,omitempty"`
	Id          *int64                 `json:"id,omitempty"`
	MaxMemoryGb *int64                 `json:"max_memory_gb,omitempty"`
	Name        *string                `json:"name,omitempty"`
	Owner       *string                `json:"owner,omitempty"`
	Size        *ComputeEndpointSize   `json:"size,omitempty"`
	Status      *ComputeEndpointStatus `json:"status,omitempty"`
	Type        *ComputeEndpointType   `json:"type,omitempty"`
	UpdatedAt   *time.Time             `json:"updated_at,omitempty"`
	Url         *string                `json:"url,omitempty"`
}

// ComputeEndpointSize defines model for ComputeEndpoint.Size.
type ComputeEndpointSize string

// ComputeEndpointStatus defines model for ComputeEndpoint.Status.
type ComputeEndpointStatus string

// ComputeEndpointType defines model for ComputeEndpoint.Type.
type ComputeEndpointType string

// ComputeEndpointHealth defines model for ComputeEndpointHealth.
type ComputeEndpointHealth struct {
	// DuckdbVersion DuckDB version running on the agent
	DuckdbVersion *string `json:"duckdb_version,omitempty"`

	// EndpointName Name of the compute endpoint
	EndpointName *string `json:"endpoint_name,omitempty"`

	// MaxMemoryGb Maximum memory limit in GB
	MaxMemoryGb *int `json:"max_memory_gb,omitempty"`

	// MemoryUsedMb Current memory usage in MB
	MemoryUsedMb *int `json:"memory_used_mb,omitempty"`

	// Status Health status (e.g. "ok")
	Status *string `json:"status,omitempty"`

	// UptimeSeconds Agent uptime in seconds
	UptimeSeconds *int `json:"uptime_seconds,omitempty"`
}

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	ExpiresAt   *time.Time `json:"expires_at,omitempty"`
	Name        string     `json:"name"`
	PrincipalId int64      `json:"principal_id"`
}

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	ExpiresAt *time.Time `json:"expires_at"`
	Id        *int64     `json:"id,omitempty"`

	// Key Raw API key (shown only once)
	Key       *string `json:"key,omitempty"`
	KeyPrefix *string `json:"key_prefix,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// CreateCatalogRequest defines model for CreateCatalogRequest.
type CreateCatalogRequest struct {
	Comment       *string                           `json:"comment,omitempty"`
	DataPath      string                            `json:"data_path"`
	Dsn           string                            `json:"dsn"`
	MetastoreType CreateCatalogRequestMetastoreType `json:"metastore_type"`
	Name          string                            `json:"name"`
}

// CreateCatalogRequestMetastoreType defines model for CreateCatalogRequest.MetastoreType.
type CreateCatalogRequestMetastoreType string

// CreateColumnMaskRequest defines model for CreateColumnMaskRequest.
type CreateColumnMaskRequest struct {
	ColumnName     string  `json:"column_name"`
	Description    *string `json:"description,omitempty"`
	MaskExpression string  `json:"mask_expression"`
}

// CreateColumnRequest defines model for CreateColumnRequest.
type CreateColumnRequest struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// CreateComputeAssignmentRequest defines model for CreateComputeAssignmentRequest.
type CreateComputeAssignmentRequest struct {
	FallbackLocal *bool                                       `json:"fallback_local,omitempty"`
	IsDefault     *bool                                       `json:"is_default,omitempty"`
	PrincipalId   int64                                       `json:"principal_id"`
	PrincipalType CreateComputeAssignmentRequestPrincipalType `json:"principal_type"`
}

// CreateComputeAssignmentRequestPrincipalType defines model for CreateComputeAssignmentRequest.PrincipalType.
type CreateComputeAssignmentRequestPrincipalType string

// CreateComputeEndpointRequest defines model for CreateComputeEndpointRequest.
type CreateComputeEndpointRequest struct {
	// AuthToken Pre-shared secret for remote agent authentication.
	AuthToken   *string                           `json:"auth_token,omitempty"`
	MaxMemoryGb *int64                            `json:"max_memory_gb,omitempty"`
	Name        string                            `json:"name"`
	Size        *CreateComputeEndpointRequestSize `json:"size,omitempty"`
	Type        CreateComputeEndpointRequestType  `json:"type"`
	Url         string                            `json:"url"`
}

// CreateComputeEndpointRequestSize defines model for CreateComputeEndpointRequest.Size.
type CreateComputeEndpointRequestSize string

// CreateComputeEndpointRequestType defines model for CreateComputeEndpointRequest.Type.
type CreateComputeEndpointRequestType string

// CreateExternalLocationRequest defines model for CreateExternalLocationRequest.
type CreateExternalLocationRequest struct {
	Comment        *string                                   `json:"comment,omitempty"`
	CredentialName string                                    `json:"credential_name"`
	Name           string                                    `json:"name"`
	ReadOnly       *bool                                     `json:"read_only,omitempty"`
	StorageType    *CreateExternalLocationRequestStorageType `json:"storage_type,omitempty"`
	Url            string                                    `json:"url"`
}

// CreateExternalLocationRequestStorageType defines model for CreateExternalLocationRequest.StorageType.
type CreateExternalLocationRequestStorageType string

// CreateGrantRequest defines model for CreateGrantRequest.
type CreateGrantRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	Privilege     string `json:"privilege"`
	SecurableId   int64  `json:"securable_id"`
	SecurableType string `json:"securable_type"`
}

// CreateGroupMemberRequest defines model for CreateGroupMemberRequest.
type CreateGroupMemberRequest struct {
	MemberId   int64  `json:"member_id"`
	MemberType string `json:"member_type"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreatePrincipalRequest defines model for CreatePrincipalRequest.
type CreatePrincipalRequest struct {
	IsAdmin *bool   `json:"is_admin,omitempty"`
	Name    string  `json:"name"`
	Type    *string `json:"type,omitempty"`
}

// CreateRowFilterRequest defines model for CreateRowFilterRequest.
type CreateRowFilterRequest struct {
	Description *string `json:"description,omitempty"`
	FilterSql   string  `json:"filter_sql"`

	// TableId Table ID (required when creating via top-level POST /row-filters)
	TableId *int64 `json:"table_id,omitempty"`
}

// CreateSchemaRequest defines model for CreateSchemaRequest.
type CreateSchemaRequest struct {
	Comment *string `json:"comment,omitempty"`

	// LocationName Optional external location name to use for schema storage path.
	LocationName *string            `json:"location_name,omitempty"`
	Name         string             `json:"name"`
	Properties   *map[string]string `json:"properties,omitempty"`
}

// CreateStorageCredentialRequest defines model for CreateStorageCredentialRequest.
type CreateStorageCredentialRequest struct {
	AzureAccountKey   *string                                      `json:"azure_account_key,omitempty"`
	AzureAccountName  *string                                      `json:"azure_account_name,omitempty"`
	AzureClientId     *string                                      `json:"azure_client_id,omitempty"`
	AzureClientSecret *string                                      `json:"azure_client_secret,omitempty"`
	AzureTenantId     *string                                      `json:"azure_tenant_id,omitempty"`
	Comment           *string                                      `json:"comment,omitempty"`
	CredentialType    CreateStorageCredentialRequestCredentialType `json:"credential_type"`
	Endpoint          *string                                      `json:"endpoint,omitempty"`
	GcsKeyFilePath    *string                                      `json:"gcs_key_file_path,omitempty"`
	KeyId             *string                                      `json:"key_id,omitempty"`
	Name              string                                       `json:"name"`
	Region            *string                                      `json:"region,omitempty"`
	Secret            *string                                      `json:"secret,omitempty"`
	UrlStyle          *string                                      `json:"url_style,omitempty"`
}

// CreateStorageCredentialRequestCredentialType defines model for CreateStorageCredentialRequest.CredentialType.
type CreateStorageCredentialRequestCredentialType string

// CreateTableRequest defines model for CreateTableRequest.
type CreateTableRequest struct {
	// Columns Required for MANAGED tables; auto-discovered for EXTERNAL if omitted.
	Columns *[]CreateColumnRequest `json:"columns,omitempty"`
	Comment *string                `json:"comment,omitempty"`

	// FileFormat File format of the external data. Required for EXTERNAL tables.
	FileFormat *CreateTableRequestFileFormat `json:"file_format,omitempty"`

	// LocationName Name of the external location that owns the source path. Required for EXTERNAL tables.
	LocationName *string `json:"location_name,omitempty"`
	Name         string  `json:"name"`

	// SourcePath S3/storage path to the data file(s). Required for EXTERNAL tables.
	SourcePath *string `json:"source_path,omitempty"`

	// TableType Type of table. MANAGED (default) or EXTERNAL.
	TableType *CreateTableRequestTableType `json:"table_type,omitempty"`
}

// CreateTableRequestFileFormat File format of the external data. Required for EXTERNAL tables.
type CreateTableRequestFileFormat string

// CreateTableRequestTableType Type of table. MANAGED (default) or EXTERNAL.
type CreateTableRequestTableType string

// CreateTagAssignmentRequest defines model for CreateTagAssignmentRequest.
type CreateTagAssignmentRequest struct {
	ColumnName    *string `json:"column_name,omitempty"`
	SecurableId   int64   `json:"securable_id"`
	SecurableType string  `json:"securable_type"`
}

// CreateTagRequest defines model for CreateTagRequest.
type CreateTagRequest struct {
	Key   string  `json:"key"`
	Value *string `json:"value,omitempty"`
}

// CreateViewRequest defines model for CreateViewRequest.
type CreateViewRequest struct {
	Comment        *string `json:"comment,omitempty"`
	Name           string  `json:"name"`
	ViewDefinition string  `json:"view_definition"`
}

// CreateVolumeRequest defines model for CreateVolumeRequest.
type CreateVolumeRequest struct {
	Comment *string `json:"comment,omitempty"`
	Name    string  `json:"name"`

	// StorageLocation Required for EXTERNAL volumes. Ignored for MANAGED.
	StorageLocation *string                       `json:"storage_location,omitempty"`
	VolumeType      CreateVolumeRequestVolumeType `json:"volume_type"`
}

// CreateVolumeRequestVolumeType defines model for CreateVolumeRequest.VolumeType.
type CreateVolumeRequestVolumeType string

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// ExternalLocation defines model for ExternalLocation.
type ExternalLocation struct {
	Comment        *string    `json:"comment,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	CredentialName *string    `json:"credential_name,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	Name           *string    `json:"name,omitempty"`
	Owner          *string    `json:"owner,omitempty"`
	ReadOnly       *bool      `json:"read_only,omitempty"`
	StorageType    *string    `json:"storage_type,omitempty"`
	UpdatedAt      *time.Time `json:"updated_at,omitempty"`
	Url            *string    `json:"url,omitempty"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	GroupId    *int64  `json:"group_id,omitempty"`
	MemberId   *int64  `json:"member_id,omitempty"`
	MemberType *string `json:"member_type,omitempty"`
}

// IngestionOptions defines model for IngestionOptions.
type IngestionOptions struct {
	// AllowMissingColumns Allow columns in the table that are missing from the Parquet file.
	AllowMissingColumns *bool `json:"allow_missing_columns,omitempty"`

	// IgnoreExtraColumns Ignore columns in the Parquet file not present in the table.
	IgnoreExtraColumns *bool `json:"ignore_extra_columns,omitempty"`
}

// IngestionResult defines model for IngestionResult.
type IngestionResult struct {
	// FilesRegistered Number of files successfully registered.
	FilesRegistered *int `json:"files_registered,omitempty"`

	// FilesSkipped Number of files skipped (e.g., empty files).
	FilesSkipped *int    `json:"files_skipped,omitempty"`
	Schema       *string `json:"schema,omitempty"`
	Table        *string `json:"table,omitempty"`
}

// LineageEdge defines model for LineageEdge.
type LineageEdge struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EdgeType Edge type: READ, WRITE, READ_WRITE
	EdgeType      *string `json:"edge_type,omitempty"`
	Id            *int64  `json:"id,omitempty"`
	PrincipalName *string `json:"principal_name,omitempty"`

	// SourceSchema Schema of the source table
	SourceSchema *string `json:"source_schema,omitempty"`
	SourceTable  *string `json:"source_table,omitempty"`

	// TargetSchema Schema of the target table
	TargetSchema *string `json:"target_schema,omitempty"`
	TargetTable  *string `json:"target_table"`
}

// LineageNode defines model for LineageNode.
type LineageNode struct {
	Downstream *[]LineageEdge `json:"downstream,omitempty"`
	TableName  *string        `json:"table_name,omitempty"`
	Upstream   *[]LineageEdge `json:"upstream,omitempty"`
}

// LoadExternalRequest defines model for LoadExternalRequest.
type LoadExternalRequest struct {
	Options *IngestionOptions `json:"options,omitempty"`

	// Paths S3 paths or globs to register.
	Paths []string `json:"paths"`
}

// ManifestColumn defines model for ManifestColumn.
type ManifestColumn struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// ManifestRequest defines model for ManifestRequest.
type ManifestRequest struct {
	Schema *string `json:"schema,omitempty"`
	Table  string  `json:"table"`
}

// ManifestResponse defines model for ManifestResponse.
type ManifestResponse struct {
	ColumnMasks *map[string]string `json:"column_masks,omitempty"`
	Columns     *[]ManifestColumn  `json:"columns,omitempty"`
	ExpiresAt   *time.Time         `json:"expires_at,omitempty"`
	Files       *[]string          `json:"files,omitempty"`
	RowFilters  *[]string          `json:"row_filters,omitempty"`
	Schema      *string            `json:"schema,omitempty"`
	Table       *string            `json:"table,omitempty"`
}

// MetastoreSummary defines model for MetastoreSummary.
type MetastoreSummary struct {
	CatalogName    *string `json:"catalog_name,omitempty"`
	DataPath       *string `json:"data_path,omitempty"`
	MetastoreType  *string `json:"metastore_type,omitempty"`
	SchemaCount    *int64  `json:"schema_count,omitempty"`
	StorageBackend *string `json:"storage_backend,omitempty"`
	TableCount     *int64  `json:"table_count,omitempty"`
}

// PaginatedAPIKeys defines model for PaginatedAPIKeys.
type PaginatedAPIKeys struct {
	Data          *[]APIKeyInfo `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// PaginatedAuditLogs defines model for PaginatedAuditLogs.
type PaginatedAuditLogs struct {
	Data          *[]AuditEntry `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// PaginatedColumnDetails defines model for PaginatedColumnDetails.
type PaginatedColumnDetails struct {
	Data          *[]ColumnDetail `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// PaginatedColumnMasks defines model for PaginatedColumnMasks.
type PaginatedColumnMasks struct {
	Data          *[]ColumnMask `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// PaginatedComputeAssignments defines model for PaginatedComputeAssignments.
type PaginatedComputeAssignments struct {
	Data          *[]ComputeAssignment `json:"data,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

// PaginatedComputeEndpoints defines model for PaginatedComputeEndpoints.
type PaginatedComputeEndpoints struct {
	Data          *[]ComputeEndpoint `json:"data,omitempty"`
	NextPageToken *string            `json:"next_page_token,omitempty"`
}

// PaginatedExternalLocations defines model for PaginatedExternalLocations.
type PaginatedExternalLocations struct {
	Data          *[]ExternalLocation `json:"data,omitempty"`
	NextPageToken *string             `json:"next_page_token,omitempty"`
}

// PaginatedGrants defines model for PaginatedGrants.
type PaginatedGrants struct {
	Data          *[]PrivilegeGrant `json:"data,omitempty"`
	NextPageToken *string           `json:"next_page_token,omitempty"`
}

// PaginatedGroupMembers defines model for PaginatedGroupMembers.
type PaginatedGroupMembers struct {
	Data          *[]GroupMember `json:"data,omitempty"`
	NextPageToken *string        `json:"next_page_token,omitempty"`
}

// PaginatedGroups defines model for PaginatedGroups.
type PaginatedGroups struct {
	Data          *[]Group `json:"data,omitempty"`
	NextPageToken *string  `json:"next_page_token,omitempty"`
}

// PaginatedLineageEdges defines model for PaginatedLineageEdges.
type PaginatedLineageEdges struct {
	Data          *[]LineageEdge `json:"data,omitempty"`
	NextPageToken *string        `json:"next_page_token,omitempty"`
}

// PaginatedPrincipals defines model for PaginatedPrincipals.
type PaginatedPrincipals struct {
	Data          *[]Principal `json:"data,omitempty"`
	NextPageToken *string      `json:"next_page_token,omitempty"`
}

// PaginatedQueryHistoryEntries defines model for PaginatedQueryHistoryEntries.
type PaginatedQueryHistoryEntries struct {
	Data          *[]QueryHistoryEntry `json:"data,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

// PaginatedRowFilters defines model for PaginatedRowFilters.
type PaginatedRowFilters struct {
	Data          *[]RowFilter `json:"data,omitempty"`
	NextPageToken *string      `json:"next_page_token,omitempty"`
}

// PaginatedSchemaDetails defines model for PaginatedSchemaDetails.
type PaginatedSchemaDetails struct {
	Data          *[]SchemaDetail `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// PaginatedSearchResults defines model for PaginatedSearchResults.
type PaginatedSearchResults struct {
	Data          *[]SearchResult `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// PaginatedStorageCredentials defines model for PaginatedStorageCredentials.
type PaginatedStorageCredentials struct {
	Data          *[]StorageCredential `json:"data,omitempty"`
	NextPageToken *string              `json:"next_page_token,omitempty"`
}

// PaginatedTableDetails defines model for PaginatedTableDetails.
type PaginatedTableDetails struct {
	Data          *[]TableDetail `json:"data,omitempty"`
	NextPageToken *string        `json:"next_page_token,omitempty"`
}

// PaginatedTags defines model for PaginatedTags.
type PaginatedTags struct {
	Data          *[]Tag  `json:"data,omitempty"`
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// PaginatedViewDetails defines model for PaginatedViewDetails.
type PaginatedViewDetails struct {
	Data          *[]ViewDetail `json:"data,omitempty"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// PaginatedVolumes defines model for PaginatedVolumes.
type PaginatedVolumes struct {
	Data          *[]VolumeDetail `json:"data,omitempty"`
	NextPageToken *string         `json:"next_page_token,omitempty"`
}

// Principal defines model for Principal.
type Principal struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	IsAdmin   *bool      `json:"is_admin,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Type      *string    `json:"type,omitempty"`
}

// PrivilegeGrant defines model for PrivilegeGrant.
type PrivilegeGrant struct {
	GrantedAt     *time.Time `json:"granted_at,omitempty"`
	GrantedBy     *int64     `json:"granted_by"`
	Id            *int64     `json:"id,omitempty"`
	PrincipalId   *int64     `json:"principal_id,omitempty"`
	PrincipalType *string    `json:"principal_type,omitempty"`
	Privilege     *string    `json:"privilege,omitempty"`
	SecurableId   *int64     `json:"securable_id,omitempty"`
	SecurableType *string    `json:"securable_type,omitempty"`
}

// PurgeLineageRequest defines model for PurgeLineageRequest.
type PurgeLineageRequest struct {
	// OlderThanDays Delete lineage edges older than this many days.
	OlderThanDays int `json:"older_than_days"`
}

// PurgeLineageResponse defines model for PurgeLineageResponse.
type PurgeLineageResponse struct {
	DeletedCount *int64 `json:"deleted_count,omitempty"`
}

// QueryHistoryEntry defines model for QueryHistoryEntry.
type QueryHistoryEntry struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	DurationMs     *int64     `json:"duration_ms"`
	ErrorMessage   *string    `json:"error_message"`
	Id             *int64     `json:"id,omitempty"`
	OriginalSql    *string    `json:"original_sql"`
	PrincipalName  *string    `json:"principal_name,omitempty"`
	RewrittenSql   *string    `json:"rewritten_sql"`
	RowsReturned   *int64     `json:"rows_returned"`
	StatementType  *string    `json:"statement_type"`
	Status         *string    `json:"status,omitempty"`
	TablesAccessed *[]string  `json:"tables_accessed,omitempty"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Sql string `json:"sql"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Columns  *[]string        `json:"columns,omitempty"`
	RowCount *int             `json:"row_count,omitempty"`
	Rows     *[][]interface{} `json:"rows,omitempty"`
}

// RowFilter defines model for RowFilter.
type RowFilter struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	FilterSql   *string    `json:"filter_sql,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	TableId     *int64     `json:"table_id,omitempty"`
}

// RowFilterBindingRequest defines model for RowFilterBindingRequest.
type RowFilterBindingRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
}

// SchemaDetail defines model for SchemaDetail.
type SchemaDetail struct {
	CatalogName *string            `json:"catalog_name,omitempty"`
	Comment     *string            `json:"comment,omitempty"`
	CreatedAt   *time.Time         `json:"created_at,omitempty"`
	DeletedAt   *time.Time         `json:"deleted_at"`
	Name        *string            `json:"name,omitempty"`
	Owner       *string            `json:"owner,omitempty"`
	Properties  *map[string]string `json:"properties,omitempty"`
	SchemaId    *int64             `json:"schema_id,omitempty"`
	Tags        *[]Tag             `json:"tags,omitempty"`
	UpdatedAt   *time.Time         `json:"updated_at,omitempty"`
}

// SearchResult defines model for SearchResult.
type SearchResult struct {
	Comment *string `json:"comment"`

	// MatchField Field that matched: name, comment, property, or tag
	MatchField *string `json:"match_field,omitempty"`
	Name       *string `json:"name,omitempty"`
	SchemaName *string `json:"schema_name"`
	TableName  *string `json:"table_name"`

	// Type Object type: schema, table, or column
	Type *string `json:"type,omitempty"`
}

// SetDefaultCatalogRequest Empty object, the catalog name is in the URL path
type SetDefaultCatalogRequest = map[string]interface{}

// StorageCredential defines model for StorageCredential.
type StorageCredential struct {
	AzureAccountName *string                          `json:"azure_account_name,omitempty"`
	AzureClientId    *string                          `json:"azure_client_id,omitempty"`
	AzureTenantId    *string                          `json:"azure_tenant_id,omitempty"`
	Comment          *string                          `json:"comment,omitempty"`
	CreatedAt        *time.Time                       `json:"created_at,omitempty"`
	CredentialType   *StorageCredentialCredentialType `json:"credential_type,omitempty"`
	Endpoint         *string                          `json:"endpoint,omitempty"`
	GcsKeyFilePath   *string                          `json:"gcs_key_file_path,omitempty"`
	Id               *int64                           `json:"id,omitempty"`
	Name             *string                          `json:"name,omitempty"`
	Owner            *string                          `json:"owner,omitempty"`
	Region           *string                          `json:"region,omitempty"`
	UpdatedAt        *time.Time                       `json:"updated_at,omitempty"`
	UrlStyle         *string                          `json:"url_style,omitempty"`
}

// StorageCredentialCredentialType defines model for StorageCredential.CredentialType.
type StorageCredentialCredentialType string

// TableDetail defines model for TableDetail.
type TableDetail struct {
	CatalogName *string         `json:"catalog_name,omitempty"`
	Columns     *[]ColumnDetail `json:"columns,omitempty"`
	Comment     *string         `json:"comment,omitempty"`
	CreatedAt   *time.Time      `json:"created_at,omitempty"`
	DeletedAt   *time.Time      `json:"deleted_at"`

	// FileFormat File format for EXTERNAL tables (parquet or csv).
	FileFormat *string `json:"file_format,omitempty"`

	// LocationName External location name for EXTERNAL tables.
	LocationName *string            `json:"location_name,omitempty"`
	Name         *string            `json:"name,omitempty"`
	Owner        *string            `json:"owner,omitempty"`
	Properties   *map[string]string `json:"properties,omitempty"`
	SchemaName   *string            `json:"schema_name,omitempty"`

	// SourcePath S3/storage path for EXTERNAL tables.
	SourcePath *string          `json:"source_path,omitempty"`
	Statistics *TableStatistics `json:"statistics,omitempty"`

	// StoragePath Resolved DuckLake data path for MANAGED tables.
	StoragePath *string    `json:"storage_path,omitempty"`
	TableId     *int64     `json:"table_id,omitempty"`
	TableType   *string    `json:"table_type,omitempty"`
	Tags        *[]Tag     `json:"tags,omitempty"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// TableStatistics defines model for TableStatistics.
type TableStatistics struct {
	ColumnCount    *int64     `json:"column_count"`
	LastProfiledAt *time.Time `json:"last_profiled_at"`
	ProfiledBy     *string    `json:"profiled_by,omitempty"`
	RowCount       *int64     `json:"row_count"`
	SizeBytes      *int64     `json:"size_bytes"`
}

// Tag defines model for Tag.
type Tag struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	CreatedBy *string    `json:"created_by,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	Key       *string    `json:"key,omitempty"`
	Value     *string    `json:"value"`
}

// TagAssignment defines model for TagAssignment.
type TagAssignment struct {
	AssignedAt    *time.Time `json:"assigned_at,omitempty"`
	AssignedBy    *string    `json:"assigned_by,omitempty"`
	ColumnName    *string    `json:"column_name"`
	Id            *int64     `json:"id,omitempty"`
	SecurableId   *int64     `json:"securable_id,omitempty"`
	SecurableType *string    `json:"securable_type,omitempty"`
	TagId         *int64     `json:"tag_id,omitempty"`
}

// UpdateCatalogRegistrationRequest defines model for UpdateCatalogRegistrationRequest.
type UpdateCatalogRegistrationRequest struct {
	Comment  *string `json:"comment,omitempty"`
	DataPath *string `json:"data_path,omitempty"`
	Dsn      *string `json:"dsn,omitempty"`
}

// UpdateColumnRequest defines model for UpdateColumnRequest.
type UpdateColumnRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// UpdateComputeEndpointRequest defines model for UpdateComputeEndpointRequest.
type UpdateComputeEndpointRequest struct {
	AuthToken   *string                             `json:"auth_token,omitempty"`
	MaxMemoryGb *int64                              `json:"max_memory_gb,omitempty"`
	Size        *UpdateComputeEndpointRequestSize   `json:"size,omitempty"`
	Status      *UpdateComputeEndpointRequestStatus `json:"status,omitempty"`
	Url         *string                             `json:"url,omitempty"`
}

// UpdateComputeEndpointRequestSize defines model for UpdateComputeEndpointRequest.Size.
type UpdateComputeEndpointRequestSize string

// UpdateComputeEndpointRequestStatus defines model for UpdateComputeEndpointRequest.Status.
type UpdateComputeEndpointRequestStatus string

// UpdateExternalLocationRequest defines model for UpdateExternalLocationRequest.
type UpdateExternalLocationRequest struct {
	Comment        *string `json:"comment,omitempty"`
	CredentialName *string `json:"credential_name,omitempty"`
	Owner          *string `json:"owner,omitempty"`
	ReadOnly       *bool   `json:"read_only,omitempty"`
	Url            *string `json:"url,omitempty"`
}

// UpdatePrincipalAdminRequest defines model for UpdatePrincipalAdminRequest.
type UpdatePrincipalAdminRequest struct {
	IsAdmin bool `json:"is_admin"`
}

// UpdateSchemaRequest defines model for UpdateSchemaRequest.
type UpdateSchemaRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// UpdateStorageCredentialRequest defines model for UpdateStorageCredentialRequest.
type UpdateStorageCredentialRequest struct {
	AzureAccountKey   *string `json:"azure_account_key,omitempty"`
	AzureAccountName  *string `json:"azure_account_name,omitempty"`
	AzureClientId     *string `json:"azure_client_id,omitempty"`
	AzureClientSecret *string `json:"azure_client_secret,omitempty"`
	AzureTenantId     *string `json:"azure_tenant_id,omitempty"`
	Comment           *string `json:"comment,omitempty"`
	Endpoint          *string `json:"endpoint,omitempty"`
	GcsKeyFilePath    *string `json:"gcs_key_file_path,omitempty"`
	KeyId             *string `json:"key_id,omitempty"`
	Region            *string `json:"region,omitempty"`
	Secret            *string `json:"secret,omitempty"`
	UrlStyle          *string `json:"url_style,omitempty"`
}

// UpdateTableRequest defines model for UpdateTableRequest.
type UpdateTableRequest struct {
	Comment    *string            `json:"comment,omitempty"`
	Owner      *string            `json:"owner,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// UpdateViewRequest defines model for UpdateViewRequest.
type UpdateViewRequest struct {
	Comment        *string            `json:"comment,omitempty"`
	Properties     *map[string]string `json:"properties,omitempty"`
	ViewDefinition *string            `json:"view_definition,omitempty"`
}

// UpdateVolumeRequest defines model for UpdateVolumeRequest.
type UpdateVolumeRequest struct {
	Comment *string `json:"comment,omitempty"`
	NewName *string `json:"new_name,omitempty"`
	Owner   *string `json:"owner,omitempty"`
}

// UploadUrlRequest defines model for UploadUrlRequest.
type UploadUrlRequest struct {
	// Filename Optional filename hint for the uploaded file.
	Filename *string `json:"filename,omitempty"`
}

// UploadUrlResponse defines model for UploadUrlResponse.
type UploadUrlResponse struct {
	// ExpiresAt When the presigned URL expires.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// S3Key The S3 key where the file will be stored.
	S3Key *string `json:"s3_key,omitempty"`

	// UploadUrl Presigned PUT URL for uploading the Parquet file.
	UploadUrl *string `json:"upload_url,omitempty"`
}

// ViewDetail defines model for ViewDetail.
type ViewDetail struct {
	CatalogName    *string            `json:"catalog_name,omitempty"`
	Comment        *string            `json:"comment"`
	CreatedAt      *time.Time         `json:"created_at,omitempty"`
	Id             *int64             `json:"id,omitempty"`
	Name           *string            `json:"name,omitempty"`
	Owner          *string            `json:"owner,omitempty"`
	Properties     *map[string]string `json:"properties,omitempty"`
	SchemaId       *int64             `json:"schema_id,omitempty"`
	SchemaName     *string            `json:"schema_name,omitempty"`
	SourceTables   *[]string          `json:"source_tables,omitempty"`
	UpdatedAt      *time.Time         `json:"updated_at,omitempty"`
	ViewDefinition *string            `json:"view_definition,omitempty"`
}

// VolumeDetail defines model for VolumeDetail.
type VolumeDetail struct {
	CatalogName     *string                 `json:"catalog_name,omitempty"`
	Comment         *string                 `json:"comment,omitempty"`
	CreatedAt       *time.Time              `json:"created_at,omitempty"`
	Id              *int64                  `json:"id,omitempty"`
	Name            *string                 `json:"name,omitempty"`
	Owner           *string                 `json:"owner,omitempty"`
	SchemaName      *string                 `json:"schema_name,omitempty"`
	StorageLocation *string                 `json:"storage_location,omitempty"`
	UpdatedAt       *time.Time              `json:"updated_at,omitempty"`
	VolumeType      *VolumeDetailVolumeType `json:"volume_type,omitempty"`
}

// VolumeDetailVolumeType defines model for VolumeDetail.VolumeType.
type VolumeDetailVolumeType string

// MaxResults defines model for MaxResults.
type MaxResults = int

// PageToken defines model for PageToken.
type PageToken = string

// CatalogName defines model for catalogName.
type CatalogName = string

// ListAPIKeysParams defines parameters for ListAPIKeys.
type ListAPIKeysParams struct {
	PrincipalId int64 `form:"principal_id" json:"principal_id"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	PrincipalName *string `form:"principal_name,omitempty" json:"principal_name,omitempty"`
	Action        *string `form:"action,omitempty" json:"action,omitempty"`
	Status        *string `form:"status,omitempty" json:"status,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListCatalogsParams defines parameters for ListCatalogs.
type ListCatalogsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListSchemasParams defines parameters for ListSchemas.
type ListSchemasParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// DeleteSchemaParams defines parameters for DeleteSchema.
type DeleteSchemaParams struct {
	// Force Force deletion even if the schema contains tables.
	Force *bool `form:"force,omitempty" json:"force,omitempty"`
}

// ListTablesParams defines parameters for ListTables.
type ListTablesParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListTableColumnsParams defines parameters for ListTableColumns.
type ListTableColumnsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListViewsParams defines parameters for ListViews.
type ListViewsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListVolumesParams defines parameters for ListVolumes.
type ListVolumesParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListClassificationsParams defines parameters for ListClassifications.
type ListClassificationsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// UnbindColumnMaskParams defines parameters for UnbindColumnMask.
type UnbindColumnMaskParams struct {
	PrincipalId   int64  `form:"principal_id" json:"principal_id"`
	PrincipalType string `form:"principal_type" json:"principal_type"`
}

// ListComputeEndpointsParams defines parameters for ListComputeEndpoints.
type ListComputeEndpointsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListComputeAssignmentsParams defines parameters for ListComputeAssignments.
type ListComputeAssignmentsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListExternalLocationsParams defines parameters for ListExternalLocations.
type ListExternalLocationsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListGrantsParams defines parameters for ListGrants.
type ListGrantsParams struct {
	PrincipalId   *int64  `form:"principal_id,omitempty" json:"principal_id,omitempty"`
	PrincipalType *string `form:"principal_type,omitempty" json:"principal_type,omitempty"`
	SecurableType *string `form:"securable_type,omitempty" json:"securable_type,omitempty"`
	SecurableId   *int64  `form:"securable_id,omitempty" json:"securable_id,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// DeleteGroupMemberParams defines parameters for DeleteGroupMember.
type DeleteGroupMemberParams struct {
	MemberType string `form:"member_type" json:"member_type"`
	MemberId   int64  `form:"member_id" json:"member_id"`
}

// ListGroupMembersParams defines parameters for ListGroupMembers.
type ListGroupMembersParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetTableLineageParams defines parameters for GetTableLineage.
type GetTableLineageParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetDownstreamLineageParams defines parameters for GetDownstreamLineage.
type GetDownstreamLineageParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// GetUpstreamLineageParams defines parameters for GetUpstreamLineage.
type GetUpstreamLineageParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListPrincipalsParams defines parameters for ListPrincipals.
type ListPrincipalsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListQueryHistoryParams defines parameters for ListQueryHistory.
type ListQueryHistoryParams struct {
	PrincipalName *string    `form:"principal_name,omitempty" json:"principal_name,omitempty"`
	Status        *string    `form:"status,omitempty" json:"status,omitempty"`
	From          *time.Time `form:"from,omitempty" json:"from,omitempty"`
	To            *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// UnbindRowFilterParams defines parameters for UnbindRowFilter.
type UnbindRowFilterParams struct {
	PrincipalId   int64  `form:"principal_id" json:"principal_id"`
	PrincipalType string `form:"principal_type" json:"principal_type"`
}

// SearchCatalogParams defines parameters for SearchCatalog.
type SearchCatalogParams struct {
	Query string `form:"query" json:"query"`

	// Type Filter by object type: schema, table, or column
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Catalog Scope search to a specific catalog (defaults to the default catalog)
	Catalog *string `form:"catalog,omitempty" json:"catalog,omitempty"`

	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListStorageCredentialsParams defines parameters for ListStorageCredentials.
type ListStorageCredentialsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListColumnMasksParams defines parameters for ListColumnMasks.
type ListColumnMasksParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListRowFiltersParams defines parameters for ListRowFilters.
type ListRowFiltersParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListTagsParams defines parameters for ListTags.
type ListTagsParams struct {
	// MaxResults Maximum number of results to return per page.
	MaxResults *MaxResults `form:"max_results,omitempty" json:"max_results,omitempty"`

	// PageToken Opaque pagination token from a previous response.
	PageToken *PageToken `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// CreateAPIKeyJSONRequestBody defines body for CreateAPIKey for application/json ContentType.
type CreateAPIKeyJSONRequestBody = CreateAPIKeyRequest

// RegisterCatalogJSONRequestBody defines body for RegisterCatalog for application/json ContentType.
type RegisterCatalogJSONRequestBody = CreateCatalogRequest

// UpdateCatalogRegistrationJSONRequestBody defines body for UpdateCatalogRegistration for application/json ContentType.
type UpdateCatalogRegistrationJSONRequestBody = UpdateCatalogRegistrationRequest

// CreateSchemaJSONRequestBody defines body for CreateSchema for application/json ContentType.
type CreateSchemaJSONRequestBody = CreateSchemaRequest

// UpdateSchemaJSONRequestBody defines body for UpdateSchema for application/json ContentType.
type UpdateSchemaJSONRequestBody = UpdateSchemaRequest

// CreateTableJSONRequestBody defines body for CreateTable for application/json ContentType.
type CreateTableJSONRequestBody = CreateTableRequest

// UpdateTableJSONRequestBody defines body for UpdateTable for application/json ContentType.
type UpdateTableJSONRequestBody = UpdateTableRequest

// UpdateColumnJSONRequestBody defines body for UpdateColumn for application/json ContentType.
type UpdateColumnJSONRequestBody = UpdateColumnRequest

// CommitTableIngestionJSONRequestBody defines body for CommitTableIngestion for application/json ContentType.
type CommitTableIngestionJSONRequestBody = CommitIngestionRequest

// LoadTableExternalFilesJSONRequestBody defines body for LoadTableExternalFiles for application/json ContentType.
type LoadTableExternalFilesJSONRequestBody = LoadExternalRequest

// CreateUploadUrlJSONRequestBody defines body for CreateUploadUrl for application/json ContentType.
type CreateUploadUrlJSONRequestBody = UploadUrlRequest

// CreateViewJSONRequestBody defines body for CreateView for application/json ContentType.
type CreateViewJSONRequestBody = CreateViewRequest

// UpdateViewJSONRequestBody defines body for UpdateView for application/json ContentType.
type UpdateViewJSONRequestBody = UpdateViewRequest

// CreateVolumeJSONRequestBody defines body for CreateVolume for application/json ContentType.
type CreateVolumeJSONRequestBody = CreateVolumeRequest

// UpdateVolumeJSONRequestBody defines body for UpdateVolume for application/json ContentType.
type UpdateVolumeJSONRequestBody = UpdateVolumeRequest

// SetDefaultCatalogJSONRequestBody defines body for SetDefaultCatalog for application/json ContentType.
type SetDefaultCatalogJSONRequestBody = SetDefaultCatalogRequest

// BindColumnMaskJSONRequestBody defines body for BindColumnMask for application/json ContentType.
type BindColumnMaskJSONRequestBody = ColumnMaskBindingRequest

// CreateComputeEndpointJSONRequestBody defines body for CreateComputeEndpoint for application/json ContentType.
type CreateComputeEndpointJSONRequestBody = CreateComputeEndpointRequest

// UpdateComputeEndpointJSONRequestBody defines body for UpdateComputeEndpoint for application/json ContentType.
type UpdateComputeEndpointJSONRequestBody = UpdateComputeEndpointRequest

// CreateComputeAssignmentJSONRequestBody defines body for CreateComputeAssignment for application/json ContentType.
type CreateComputeAssignmentJSONRequestBody = CreateComputeAssignmentRequest

// CreateExternalLocationJSONRequestBody defines body for CreateExternalLocation for application/json ContentType.
type CreateExternalLocationJSONRequestBody = CreateExternalLocationRequest

// UpdateExternalLocationJSONRequestBody defines body for UpdateExternalLocation for application/json ContentType.
type UpdateExternalLocationJSONRequestBody = UpdateExternalLocationRequest

// CreateGrantJSONRequestBody defines body for CreateGrant for application/json ContentType.
type CreateGrantJSONRequestBody = CreateGrantRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// CreateGroupMemberJSONRequestBody defines body for CreateGroupMember for application/json ContentType.
type CreateGroupMemberJSONRequestBody = CreateGroupMemberRequest

// PurgeLineageJSONRequestBody defines body for PurgeLineage for application/json ContentType.
type PurgeLineageJSONRequestBody = PurgeLineageRequest

// CreateManifestJSONRequestBody defines body for CreateManifest for application/json ContentType.
type CreateManifestJSONRequestBody = ManifestRequest

// CreatePrincipalJSONRequestBody defines body for CreatePrincipal for application/json ContentType.
type CreatePrincipalJSONRequestBody = CreatePrincipalRequest

// UpdatePrincipalAdminJSONRequestBody defines body for UpdatePrincipalAdmin for application/json ContentType.
type UpdatePrincipalAdminJSONRequestBody = UpdatePrincipalAdminRequest

// ExecuteQueryJSONRequestBody defines body for ExecuteQuery for application/json ContentType.
type ExecuteQueryJSONRequestBody = QueryRequest

// CreateRowFilterTopLevelJSONRequestBody defines body for CreateRowFilterTopLevel for application/json ContentType.
type CreateRowFilterTopLevelJSONRequestBody = CreateRowFilterRequest

// BindRowFilterJSONRequestBody defines body for BindRowFilter for application/json ContentType.
type BindRowFilterJSONRequestBody = RowFilterBindingRequest

// CreateStorageCredentialJSONRequestBody defines body for CreateStorageCredential for application/json ContentType.
type CreateStorageCredentialJSONRequestBody = CreateStorageCredentialRequest

// UpdateStorageCredentialJSONRequestBody defines body for UpdateStorageCredential for application/json ContentType.
type UpdateStorageCredentialJSONRequestBody = UpdateStorageCredentialRequest

// CreateColumnMaskJSONRequestBody defines body for CreateColumnMask for application/json ContentType.
type CreateColumnMaskJSONRequestBody = CreateColumnMaskRequest

// CreateRowFilterJSONRequestBody defines body for CreateRowFilter for application/json ContentType.
type CreateRowFilterJSONRequestBody = CreateRowFilterRequest

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = CreateTagRequest

// CreateTagAssignmentJSONRequestBody defines body for CreateTagAssignment for application/json ContentType.
type CreateTagAssignmentJSONRequestBody = CreateTagAssignmentRequest
