// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// AddGroupMemberRequest defines model for AddGroupMemberRequest.
type AddGroupMemberRequest struct {
	MemberId   int64  `json:"member_id"`
	MemberType string `json:"member_type"`
}

// AuditEntry defines model for AuditEntry.
type AuditEntry struct {
	Action         *string    `json:"action,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	DurationMs     *int64     `json:"duration_ms"`
	ErrorMessage   *string    `json:"error_message"`
	Id             *int64     `json:"id,omitempty"`
	OriginalSql    *string    `json:"original_sql"`
	PrincipalName  *string    `json:"principal_name,omitempty"`
	RewrittenSql   *string    `json:"rewritten_sql"`
	StatementType  *string    `json:"statement_type"`
	Status         *string    `json:"status,omitempty"`
	TablesAccessed *[]string  `json:"tables_accessed,omitempty"`
}

// AuditLogResponse defines model for AuditLogResponse.
type AuditLogResponse struct {
	Data   *[]AuditEntry `json:"data,omitempty"`
	Limit  *int          `json:"limit,omitempty"`
	Offset *int          `json:"offset,omitempty"`
	Total  *int64        `json:"total,omitempty"`
}

// BindingRequest defines model for BindingRequest.
type BindingRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
}

// Column defines model for Column.
type Column struct {
	Id      *int64  `json:"id,omitempty"`
	Name    *string `json:"name,omitempty"`
	TableId *int64  `json:"table_id,omitempty"`
	Type    *string `json:"type,omitempty"`
}

// ColumnMask defines model for ColumnMask.
type ColumnMask struct {
	ColumnName     *string    `json:"column_name,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Description    *string    `json:"description,omitempty"`
	Id             *int64     `json:"id,omitempty"`
	MaskExpression *string    `json:"mask_expression,omitempty"`
	TableId        *int64     `json:"table_id,omitempty"`
}

// ColumnMaskBindingRequest defines model for ColumnMaskBindingRequest.
type ColumnMaskBindingRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	SeeOriginal   *bool  `json:"see_original,omitempty"`
}

// CreateColumnMaskRequest defines model for CreateColumnMaskRequest.
type CreateColumnMaskRequest struct {
	ColumnName     string  `json:"column_name"`
	Description    *string `json:"description,omitempty"`
	MaskExpression string  `json:"mask_expression"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// CreatePrincipalRequest defines model for CreatePrincipalRequest.
type CreatePrincipalRequest struct {
	IsAdmin *bool   `json:"is_admin,omitempty"`
	Name    string  `json:"name"`
	Type    *string `json:"type,omitempty"`
}

// CreateRowFilterRequest defines model for CreateRowFilterRequest.
type CreateRowFilterRequest struct {
	Description *string `json:"description,omitempty"`
	FilterSql   string  `json:"filter_sql"`
}

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GrantRequest defines model for GrantRequest.
type GrantRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	Privilege     string `json:"privilege"`
	SecurableId   int64  `json:"securable_id"`
	SecurableType string `json:"securable_type"`
}

// Group defines model for Group.
type Group struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	Name        *string    `json:"name,omitempty"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	GroupId    *int64  `json:"group_id,omitempty"`
	MemberId   *int64  `json:"member_id,omitempty"`
	MemberType *string `json:"member_type,omitempty"`
}

// ManifestColumn defines model for ManifestColumn.
type ManifestColumn struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// ManifestRequest defines model for ManifestRequest.
type ManifestRequest struct {
	Schema *string `json:"schema,omitempty"`
	Table  string  `json:"table"`
}

// ManifestResponse defines model for ManifestResponse.
type ManifestResponse struct {
	ColumnMasks *map[string]string `json:"column_masks,omitempty"`
	Columns     *[]ManifestColumn  `json:"columns,omitempty"`
	ExpiresAt   *time.Time         `json:"expires_at,omitempty"`
	Files       *[]string          `json:"files,omitempty"`
	RowFilters  *[]string          `json:"row_filters,omitempty"`
	Schema      *string            `json:"schema,omitempty"`
	Table       *string            `json:"table,omitempty"`
}

// Principal defines model for Principal.
type Principal struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int64     `json:"id,omitempty"`
	IsAdmin   *bool      `json:"is_admin,omitempty"`
	Name      *string    `json:"name,omitempty"`
	Type      *string    `json:"type,omitempty"`
}

// PrivilegeGrant defines model for PrivilegeGrant.
type PrivilegeGrant struct {
	GrantedAt     *time.Time `json:"granted_at,omitempty"`
	GrantedBy     *int64     `json:"granted_by"`
	Id            *int64     `json:"id,omitempty"`
	PrincipalId   *int64     `json:"principal_id,omitempty"`
	PrincipalType *string    `json:"principal_type,omitempty"`
	Privilege     *string    `json:"privilege,omitempty"`
	SecurableId   *int64     `json:"securable_id,omitempty"`
	SecurableType *string    `json:"securable_type,omitempty"`
}

// QueryRequest defines model for QueryRequest.
type QueryRequest struct {
	Sql string `json:"sql"`
}

// QueryResult defines model for QueryResult.
type QueryResult struct {
	Columns  *[]string        `json:"columns,omitempty"`
	RowCount *int             `json:"row_count,omitempty"`
	Rows     *[][]interface{} `json:"rows,omitempty"`
}

// RevokeRequest defines model for RevokeRequest.
type RevokeRequest struct {
	PrincipalId   int64  `json:"principal_id"`
	PrincipalType string `json:"principal_type"`
	Privilege     string `json:"privilege"`
	SecurableId   int64  `json:"securable_id"`
	SecurableType string `json:"securable_type"`
}

// RowFilter defines model for RowFilter.
type RowFilter struct {
	CreatedAt   *time.Time `json:"created_at,omitempty"`
	Description *string    `json:"description,omitempty"`
	FilterSql   *string    `json:"filter_sql,omitempty"`
	Id          *int64     `json:"id,omitempty"`
	TableId     *int64     `json:"table_id,omitempty"`
}

// Schema defines model for Schema.
type Schema struct {
	Id   *int64  `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// SetAdminRequest defines model for SetAdminRequest.
type SetAdminRequest struct {
	IsAdmin bool `json:"is_admin"`
}

// Table defines model for Table.
type Table struct {
	Id       *int64  `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	SchemaId *int64  `json:"schema_id,omitempty"`
}

// ListAuditLogsParams defines parameters for ListAuditLogs.
type ListAuditLogsParams struct {
	PrincipalName *string `form:"principal_name,omitempty" json:"principal_name,omitempty"`
	Action        *string `form:"action,omitempty" json:"action,omitempty"`
	Status        *string `form:"status,omitempty" json:"status,omitempty"`
	Limit         *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset        *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListGrantsParams defines parameters for ListGrants.
type ListGrantsParams struct {
	PrincipalId   *int64  `form:"principal_id,omitempty" json:"principal_id,omitempty"`
	PrincipalType *string `form:"principal_type,omitempty" json:"principal_type,omitempty"`
	SecurableType *string `form:"securable_type,omitempty" json:"securable_type,omitempty"`
	SecurableId   *int64  `form:"securable_id,omitempty" json:"securable_id,omitempty"`
}

// UnbindColumnMaskJSONRequestBody defines body for UnbindColumnMask for application/json ContentType.
type UnbindColumnMaskJSONRequestBody = BindingRequest

// BindColumnMaskJSONRequestBody defines body for BindColumnMask for application/json ContentType.
type BindColumnMaskJSONRequestBody = ColumnMaskBindingRequest

// RevokePrivilegeJSONRequestBody defines body for RevokePrivilege for application/json ContentType.
type RevokePrivilegeJSONRequestBody = RevokeRequest

// GrantPrivilegeJSONRequestBody defines body for GrantPrivilege for application/json ContentType.
type GrantPrivilegeJSONRequestBody = GrantRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// RemoveGroupMemberJSONRequestBody defines body for RemoveGroupMember for application/json ContentType.
type RemoveGroupMemberJSONRequestBody = AddGroupMemberRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddGroupMemberRequest

// GetManifestJSONRequestBody defines body for GetManifest for application/json ContentType.
type GetManifestJSONRequestBody = ManifestRequest

// CreatePrincipalJSONRequestBody defines body for CreatePrincipal for application/json ContentType.
type CreatePrincipalJSONRequestBody = CreatePrincipalRequest

// SetAdminJSONRequestBody defines body for SetAdmin for application/json ContentType.
type SetAdminJSONRequestBody = SetAdminRequest

// ExecuteQueryJSONRequestBody defines body for ExecuteQuery for application/json ContentType.
type ExecuteQueryJSONRequestBody = QueryRequest

// UnbindRowFilterJSONRequestBody defines body for UnbindRowFilter for application/json ContentType.
type UnbindRowFilterJSONRequestBody = BindingRequest

// BindRowFilterJSONRequestBody defines body for BindRowFilter for application/json ContentType.
type BindRowFilterJSONRequestBody = BindingRequest

// CreateColumnMaskJSONRequestBody defines body for CreateColumnMask for application/json ContentType.
type CreateColumnMaskJSONRequestBody = CreateColumnMaskRequest

// CreateRowFilterJSONRequestBody defines body for CreateRowFilter for application/json ContentType.
type CreateRowFilterJSONRequestBody = CreateRowFilterRequest
