// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbstore

import (
	"database/sql"
)

type ApiKey struct {
	ID          int64
	KeyHash     string
	PrincipalID int64
	Name        string
	ExpiresAt   sql.NullString
	CreatedAt   string
}

type AuditLog struct {
	ID             int64
	PrincipalName  string
	Action         string
	StatementType  sql.NullString
	OriginalSql    sql.NullString
	RewrittenSql   sql.NullString
	TablesAccessed sql.NullString
	Status         string
	ErrorMessage   sql.NullString
	DurationMs     sql.NullInt64
	CreatedAt      string
}

type ColumnMask struct {
	ID             int64
	TableID        int64
	ColumnName     string
	MaskExpression string
	Description    sql.NullString
	CreatedAt      string
}

type ColumnMaskBinding struct {
	ID            int64
	ColumnMaskID  int64
	PrincipalID   int64
	PrincipalType string
	SeeOriginal   int64
}

type Group struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   string
}

type GroupMember struct {
	GroupID    int64
	MemberType string
	MemberID   int64
}

type Principal struct {
	ID        int64
	Name      string
	Type      string
	IsAdmin   int64
	CreatedAt string
}

type PrivilegeGrant struct {
	ID            int64
	PrincipalID   int64
	PrincipalType string
	SecurableType string
	SecurableID   int64
	Privilege     string
	GrantedBy     sql.NullInt64
	GrantedAt     string
}

type RowFilter struct {
	ID          int64
	TableID     int64
	FilterSql   string
	Description sql.NullString
	CreatedAt   string
}

type RowFilterBinding struct {
	ID            int64
	RowFilterID   int64
	PrincipalID   int64
	PrincipalType string
}
