// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: principals.sql

package dbstore

import (
	"context"
)

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO principals (name, type, is_admin)
VALUES (?, ?, ?)
RETURNING id, name, type, is_admin, created_at
`

type CreatePrincipalParams struct {
	Name    string
	Type    string
	IsAdmin int64
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, createPrincipal, arg.Name, arg.Type, arg.IsAdmin)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deletePrincipal = `-- name: DeletePrincipal :exec
DELETE FROM principals WHERE id = ?
`

func (q *Queries) DeletePrincipal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePrincipal, id)
	return err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, name, type, is_admin, created_at FROM principals WHERE id = ?
`

func (q *Queries) GetPrincipal(ctx context.Context, id int64) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getPrincipalByName = `-- name: GetPrincipalByName :one
SELECT id, name, type, is_admin, created_at FROM principals WHERE name = ?
`

func (q *Queries) GetPrincipalByName(ctx context.Context, name string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByName, name)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT id, name, type, is_admin, created_at FROM principals ORDER BY name
`

func (q *Queries) ListPrincipals(ctx context.Context) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IsAdmin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE principals SET is_admin = ? WHERE id = ?
`

type SetAdminParams struct {
	IsAdmin int64
	ID      int64
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.ExecContext(ctx, setAdmin, arg.IsAdmin, arg.ID)
	return err
}
