name: Security Vulnerability
description: Report a suspected security vulnerability. For confirmed critical issues, use GitHub Security Advisories instead.
title: "[security] "
labels: ["security", "triage", "confidential"]
body:
  - type: markdown
    attributes:
      value: |
        **This template is for suspected security issues that need triage.**

        For confirmed critical vulnerabilities (authentication bypass, privilege
        escalation, data exfiltration), prefer
        [GitHub Security Advisories](https://github.com/Yacobolo/ducklake-dataplatform/security/advisories/new)
        for private disclosure.

        Do NOT include working exploits, credentials, or customer data in this issue.

  # ── Classification ──────────────────────────────────────────

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      options:
        - "Authentication bypass (JWT validation, API key verification)"
        - "Authorization / privilege escalation (RBAC grant enforcement)"
        - "Row-level security bypass (RLS filter evasion)"
        - "Column masking bypass (masked data exposure)"
        - "SQL injection (via sqlrewrite or engine)"
        - "Information disclosure (error messages, metadata leakage)"
        - "Denial of service (resource exhaustion, crash)"
        - "Insecure defaults (permissive config, missing validation)"
        - "Dependency vulnerability (Go module, DuckDB, C++ extension)"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Primary architecture layer involved.
      options:
        - "middleware (internal/middleware — JWT, API key auth)"
        - "engine (internal/engine — SecureEngine, RBAC enforcement)"
        - "sqlrewrite (internal/sqlrewrite — SQL parsing, RLS/mask injection)"
        - "api (internal/api — input validation, HTTP handlers)"
        - "service (internal/service — authorization logic)"
        - "repository (internal/db/repository — data access)"
        - "extension (extension/duck_access — C++ DuckDB extension)"
        - "domain (internal/domain — error information leakage)"
        - "cmd (cmd/server — configuration, TLS, startup)"
        - "other / cross-cutting"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity (CVSS-like)
      description: Your best estimate. The security team will assign the final rating.
      options:
        - "Critical — unauthenticated remote exploit, data exfiltration"
        - "High — authenticated privilege escalation, RLS/masking bypass"
        - "Medium — information disclosure, partial bypass with constraints"
        - "Low — defense-in-depth improvement, hardening"
    validations:
      required: true

  # ── Attack Description ─────────────────────────────────────

  - type: textarea
    id: summary
    attributes:
      label: Vulnerability Summary
      description: |
        One-paragraph description of the vulnerability, its root cause, and
        what an attacker can achieve. Do NOT include a working exploit.
      placeholder: |
        A principal with SELECT on `catalog.schema.table` can craft a SQL
        query using a CTE that references the table before the RLS filter
        is injected by sqlrewrite, allowing them to read rows that should
        be filtered by their row-level security policy.
    validations:
      required: true

  - type: textarea
    id: attack-vector
    attributes:
      label: Attack Vector
      description: |
        Describe the preconditions and steps an attacker would take.
        Do NOT include a fully weaponized exploit. Focus on the logical
        sequence and required access level.
      placeholder: |
        Preconditions:
        - Attacker has a valid JWT for a non-admin principal
        - Principal has SELECT grant on the target table
        - Table has an RLS row filter bound to the principal's group

        Steps:
        1. Craft a CTE-based query: `WITH leaked AS (SELECT * FROM ...) SELECT ...`
        2. Send via POST /query
        3. sqlrewrite applies RLS to the outer SELECT but not the CTE subquery
        4. Attacker reads unfiltered rows via the CTE
    validations:
      required: true

  - type: dropdown
    id: auth-required
    attributes:
      label: Authentication Required?
      description: What level of access does the attacker need?
      options:
        - "None — unauthenticated"
        - "Any valid principal (non-admin)"
        - "Principal with specific grants"
        - "Admin principal"
        - "Physical / network access only"
    validations:
      required: true

  # ── Impact ─────────────────────────────────────────────────

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      description: Select all that apply.
      options:
        - label: "Confidentiality — unauthorized data access"
        - label: "Integrity — unauthorized data modification"
        - label: "Availability — denial of service or crash"
        - label: "Audit evasion — actions not logged"

  - type: textarea
    id: affected-data
    attributes:
      label: Affected Data / Resources
      description: |
        What data or resources are exposed? Be specific about the scope
        (single table, all tables, metadata, credentials, etc.).
      placeholder: |
        All rows in any table that has an RLS policy bound to the attacker's
        group. Column masks are correctly applied; only row filtering is bypassed.

  # ── Mitigation ─────────────────────────────────────────────

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: |
        If you have a proposed fix or mitigation, describe it. Reference
        specific functions, files, or architectural changes.
      placeholder: |
        In `internal/sqlrewrite/rewriter.go`, the `applyRowFilters` function
        should recursively traverse CTEs and subqueries, not just the top-level
        FROM clause. Add a `walkAllTableRefs()` helper that visits every
        `RangeVar` node in the parse tree.

  - type: textarea
    id: workaround
    attributes:
      label: Temporary Workaround
      description: Any mitigation that can be applied before a fix is released.
      placeholder: |
        Disable CTE support by rejecting queries containing WITH clauses
        at the API layer via input validation. This blocks the attack vector
        but limits legitimate CTE usage.

  # ── Environment ─────────────────────────────────────────────

  - type: input
    id: commit-sha
    attributes:
      label: Commit SHA or Version
      placeholder: "abc1234"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        References to related CVEs, similar vulnerabilities in other projects,
        or relevant security research. Do NOT include customer data or secrets.
