// Code generated by cli-gen. DO NOT EDIT.
package gen

import (
	"encoding/json"
	"fmt"
	"net/url"
)

// PaginatedResponse is the generic shape of a paginated API response.
type PaginatedResponse struct {
	Data          []interface{} `json:"data"`
	NextPageToken string        `json:"next_page_token"`
}

// FetchAllPages fetches all pages of a paginated endpoint.
func FetchAllPages(client *Client, method, path string, baseQuery url.Values) ([]interface{}, error) {
	var allItems []interface{}
	query := url.Values{}
	for k, v := range baseQuery {
		query[k] = v
	}

	for {
		resp, err := client.Do(method, path, query, nil)
		if err != nil {
			return nil, err
		}
		if err := CheckError(resp); err != nil {
			return nil, err
		}

		body, err := ReadBody(resp)
		if err != nil {
			return nil, fmt.Errorf("read response: %w", err)
		}

		var page PaginatedResponse
		if err := json.Unmarshal(body, &page); err != nil {
			return nil, fmt.Errorf("parse response: %w", err)
		}

		allItems = append(allItems, page.Data...)

		if page.NextPageToken == "" {
			break
		}
		query.Set("page_token", page.NextPageToken)
	}

	return allItems, nil
}
