package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"duck-demo/pkg/cli/gen"
)

func newConfigInitCmd() *cobra.Command {
	var (
		mode    string
		env     string
		outPath string
		force   bool
	)

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Generate a starter .env file",
		RunE: func(cmd *cobra.Command, _ []string) error {
			mode = strings.ToLower(strings.TrimSpace(mode))
			env = strings.ToLower(strings.TrimSpace(env))
			if err := validateConfigInitInputs(mode, env); err != nil {
				return err
			}

			if !force {
				if _, err := os.Stat(outPath); err == nil {
					return fmt.Errorf("%s already exists; use --force to overwrite", outPath)
				} else if !os.IsNotExist(err) {
					return fmt.Errorf("stat %s: %w", outPath, err)
				}
			}

			content := renderEnvTemplate(mode, env)
			if err := os.WriteFile(outPath, []byte(content), 0o600); err != nil {
				return fmt.Errorf("write %s: %w", outPath, err)
			}

			absPath, err := filepath.Abs(outPath)
			if err != nil {
				absPath = outPath
			}

			if getOutputFormat(cmd) == "json" {
				return gen.PrintJSON(os.Stdout, map[string]string{
					"status": "ok",
					"path":   absPath,
					"mode":   mode,
					"env":    env,
				})
			}

			_, _ = fmt.Fprintf(os.Stdout, "Wrote %s (%s, %s)\n", absPath, mode, env)
			return nil
		},
	}

	cmd.Flags().StringVar(&mode, "mode", "hybrid", "Auth mode (hybrid, oidc_only, local_only, api_key_only)")
	cmd.Flags().StringVar(&env, "env", "development", "Environment profile (development, production)")
	cmd.Flags().StringVar(&outPath, "output", ".env", "Output path")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite output file if it exists")

	return cmd
}

func validateConfigInitInputs(mode, env string) error {
	switch mode {
	case "hybrid", "oidc_only", "local_only", "api_key_only":
	default:
		return fmt.Errorf("invalid --mode %q (expected hybrid, oidc_only, local_only, api_key_only)", mode)
	}

	switch env {
	case "development", "production":
	default:
		return fmt.Errorf("invalid --env %q (expected development or production)", env)
	}

	return nil
}

func renderEnvTemplate(mode, env string) string {
	base := []string{
		"# Generated by: duck config init",
		fmt.Sprintf("ENV=%s", env),
		"LISTEN_ADDR=:8080",
		"META_DB_PATH=ducklake_meta.sqlite",
		"LOG_LEVEL=info",
		"",
		fmt.Sprintf("AUTH_MODE=%s", mode),
	}

	switch mode {
	case "oidc_only":
		base = append(base,
			"AUTH_ISSUER_URL=https://issuer.example.com",
			"AUTH_AUDIENCE=duck-demo",
			"# AUTH_JWKS_URL=https://issuer.example.com/.well-known/jwks.json",
			"AUTH_API_KEY_ENABLED=false",
		)
	case "local_only":
		base = append(base,
			"JWT_SECRET=replace-with-long-random-local-secret",
			"AUTH_API_KEY_ENABLED=true",
			"AUTH_API_KEY_HEADER=X-API-Key",
		)
	case "api_key_only":
		base = append(base,
			"AUTH_API_KEY_ENABLED=true",
			"AUTH_API_KEY_HEADER=X-API-Key",
		)
	default:
		base = append(base,
			"AUTH_ISSUER_URL=https://issuer.example.com",
			"AUTH_AUDIENCE=duck-demo",
			"# AUTH_JWKS_URL=https://issuer.example.com/.well-known/jwks.json",
			"JWT_SECRET=replace-with-long-random-fallback-secret",
			"AUTH_API_KEY_ENABLED=true",
			"AUTH_API_KEY_HEADER=X-API-Key",
		)
	}

	base = append(base, "")
	if env == "production" {
		base = append(base,
			"TLS_CERT_FILE=/etc/duck/tls/server.crt",
			"TLS_KEY_FILE=/etc/duck/tls/server.key",
			"# ALLOW_INSECURE_HTTP=false",
			"ENCRYPTION_KEY=replace-with-64-char-hex-key",
			"CORS_ALLOWED_ORIGINS=https://app.example.com",
		)
	} else {
		base = append(base,
			"ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000",
			"CORS_ALLOWED_ORIGINS=*",
		)
	}

	base = append(base,
		"",
		"# Optional S3 config (preferred names)",
		"# S3_KEY_ID=",
		"# S3_SECRET=",
		"# S3_ENDPOINT=",
		"# S3_REGION=",
		"# S3_BUCKET=duck-demo",
	)

	return strings.Join(base, "\n") + "\n"
}
