// Package catalog provides DuckDB syntax metadata (keywords, types, functions)
// generated from DuckDB's system catalog tables.
//
// All files named *_gen.go are generated by scripts/genduckdb and should not
// be edited by hand.
//
//go:generate go run ../../../scripts/genduckdb -gen=all -outdir=.
package catalog
