// Package requestmodelgo emits APIGen-owned schema model clones from legacy oapi types.
package requestmodelgo

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"sort"
	"strings"

	"duck-demo/internal/apigen/ir"
)

// Emit renders APIGen-owned request schema types derived from legacy oapi models.
func Emit(doc ir.Document, legacyTypesPath string) ([]byte, error) {
	return emit(doc, legacyTypesPath)
}

// EmitWithResponseRoots renders APIGen-owned request and safe response schema
// types using IR-declared response schemas.
func EmitWithResponseRoots(doc ir.Document, legacyTypesPath string) ([]byte, error) {
	return emit(doc, legacyTypesPath)
}

func emit(doc ir.Document, legacyTypesPath string) ([]byte, error) {
	typesByName, err := loadLegacyTypes(legacyTypesPath)
	if err != nil {
		return nil, err
	}

	rootNames, err := schemaRoots(doc)
	if err != nil {
		return nil, err
	}
	cloneSet := collectCloneSet(rootNames, typesByName)

	allNames := make([]string, 0, len(cloneSet))
	for name := range cloneSet {
		allNames = append(allNames, name)
	}
	sort.Strings(allNames)

	usesTime := false
	for _, name := range allNames {
		if structType, ok := typesByName[name].Type.(*ast.StructType); ok && structUsesTime(structType, cloneSet) {
			usesTime = true
			break
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by apigen schema model emitter. DO NOT EDIT.\n")
	b.WriteString("package api\n\n")
	if usesTime {
		b.WriteString("import \"time\"\n\n")
	}

	for _, rootName := range rootNames {
		spec, ok := typesByName[rootName]
		if !ok {
			return nil, fmt.Errorf("request model %q not found in %s", rootName, legacyTypesPath)
		}
		if _, isCloned := cloneSet[rootName]; isCloned {
			b.WriteString(renderClonedStruct(genSchemaTypeName(rootName), spec.Type.(*ast.StructType), cloneSet))
			continue
		}
		b.WriteString("type ")
		b.WriteString(genSchemaTypeName(rootName))
		b.WriteString(" = ")
		b.WriteString(rootName)
		b.WriteString("\n\n")
	}

	for _, name := range allNames {
		if contains(rootNames, name) {
			continue
		}
		b.WriteString(renderClonedStruct(genSchemaTypeName(name), typesByName[name].Type.(*ast.StructType), cloneSet))
	}

	return []byte(b.String()), nil
}

func schemaRoots(doc ir.Document) ([]string, error) {
	seen := make(map[string]struct{})
	for _, name := range requestSchemaRoots(doc) {
		seen[name] = struct{}{}
	}

	for _, name := range safeResponseSchemaRoots(doc) {
		seen[name] = struct{}{}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames, nil
}

func loadLegacyTypes(path string) (map[string]*ast.TypeSpec, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse legacy request models: %w", err)
	}

	typesByName := make(map[string]*ast.TypeSpec)
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			typesByName[typeSpec.Name.Name] = typeSpec
		}
	}

	return typesByName, nil
}

func requestSchemaRoots(doc ir.Document) []string {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		if endpoint.RequestBody == nil {
			continue
		}
		if schemaName, ok := resolveRequestSchemaName(doc, endpoint); ok {
			seen[schemaName] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames
}

func safeResponseSchemaRoots(doc ir.Document) []string {
	seen := make(map[string]struct{})
	for _, endpoint := range doc.Endpoints {
		for _, response := range endpoint.Responses {
			if shape, ok, err := ir.ResponseShapeMetadata(response); err == nil && ok {
				if shape.BodyType != "" {
					seen[shape.BodyType] = struct{}{}
				}
				continue
			}
			if response.Schema == nil || isErrorSchemaRef(*response.Schema) {
				continue
			}
			bodyTypeName, ok := normalizedSchemaRefName(*response.Schema)
			if !ok {
				continue
			}
			seen[bodyTypeName] = struct{}{}
		}
	}

	rootNames := make([]string, 0, len(seen))
	for name := range seen {
		rootNames = append(rootNames, name)
	}
	sort.Strings(rootNames)
	return rootNames
}

func normalizedSchemaRefName(schema ir.SchemaRef) (string, bool) {
	if schema.Ref == "" {
		return "", false
	}
	ref := strings.TrimSpace(schema.Ref)
	ref = strings.TrimPrefix(ref, "#/components/schemas/")
	ref = strings.TrimPrefix(ref, "#/schemas/")
	if idx := strings.LastIndex(ref, "/"); idx >= 0 {
		ref = ref[idx+1:]
	}
	if ref == "" {
		return "", false
	}
	return ref, true
}

func isErrorSchemaRef(schema ir.SchemaRef) bool {
	ref, ok := normalizedSchemaRefName(schema)
	if !ok {
		return false
	}
	return exportedName(ref) == "Error"
}

func resolveRequestSchemaName(doc ir.Document, endpoint ir.Endpoint) (string, bool) {
	if endpoint.RequestBody == nil {
		return "", false
	}

	schema := endpoint.RequestBody.Schema
	if schema.Ref != "" && schema.Ref != "GenericRequest" {
		return schema.Ref, true
	}
	if schema.Ref == "GenericRequest" {
		if schemaName, ok := resolveGenericRequestBodySchemaName(doc, endpoint.OperationID); ok {
			return schemaName, true
		}
	}
	return "", false
}

func resolveGenericRequestBodySchemaName(doc ir.Document, operationID string) (string, bool) {
	if schemaName, ok := genericRequestBodySchemaOverrides[operationID]; ok {
		return schemaName, true
	}
	for _, candidate := range genericRequestBodySchemaCandidates(operationID) {
		if _, ok := doc.Schemas[candidate]; ok {
			return candidate, true
		}
	}
	return "", false
}

func genericRequestBodySchemaCandidates(operationID string) []string {
	return []string{exportedName(operationID) + "Request"}
}

var genericRequestBodySchemaOverrides = map[string]string{
	"bindColumnMask":               "ColumnMaskBindingRequest",
	"bindRowFilter":                "RowFilterBindingRequest",
	"commitTableIngestion":         "CommitIngestionRequest",
	"createCell":                   "CreateCellRequest",
	"createComputeAssignment":      "CreateComputeAssignmentRequest",
	"createComputeEndpoint":        "CreateComputeEndpointRequest",
	"createGitRepo":                "CreateGitRepoRequest",
	"createMacro":                  "CreateMacroRequest",
	"createManifest":               "ManifestRequest",
	"createModelTest":              "CreateModelTestRequest",
	"createNotebook":               "CreateNotebookRequest",
	"createPipeline":               "CreatePipelineRequest",
	"createPipelineJob":            "CreatePipelineJobRequest",
	"createSemanticMetric":         "CreateSemanticMetricRequest",
	"createSemanticModel":          "CreateSemanticModelRequest",
	"createSemanticPreAggregation": "CreateSemanticPreAggregationRequest",
	"createSemanticRelationship":   "CreateSemanticRelationshipRequest",
	"createTag":                    "CreateTagRequest",
	"createTagAssignment":          "CreateTagAssignmentRequest",
	"createUploadUrl":              "UploadUrlRequest",
	"executeQuery":                 "QueryRequest",
	"explainMetricQuery":           "MetricQueryRequest",
	"loadTableExternalFiles":       "LoadExternalRequest",
	"promoteNotebookToModel":       "PromoteNotebookRequest",
	"purgeLineage":                 "PurgeLineageRequest",
	"reorderCells":                 "ReorderCellsRequest",
	"runMetricQuery":               "MetricQueryRequest",
	"triggerModelRun":              "TriggerModelRunRequest",
	"triggerPipelineRun":           "TriggerPipelineRunRequest",
	"updateCell":                   "UpdateCellRequest",
	"updateComputeEndpoint":        "UpdateComputeEndpointRequest",
	"updateMacro":                  "UpdateMacroRequest",
	"updateModel":                  "UpdateModelRequest",
	"updateNotebook":               "UpdateNotebookRequest",
	"updatePipeline":               "UpdatePipelineRequest",
	"updateSemanticMetric":         "UpdateSemanticMetricRequest",
	"updateSemanticModel":          "UpdateSemanticModelRequest",
	"updateSemanticPreAggregation": "UpdateSemanticPreAggregationRequest",
	"updateSemanticRelationship":   "UpdateSemanticRelationshipRequest",
}

func exportedName(operationID string) string {
	parts := splitIdentifier(operationID)
	if len(parts) == 0 {
		return "Operation"
	}
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func splitIdentifier(value string) []string {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	replacer := strings.NewReplacer("-", " ", "_", " ", ".", " ", "/", " ")
	value = replacer.Replace(value)
	chunks := strings.Fields(value)
	if len(chunks) > 0 {
		return chunks
	}
	return []string{value}
}

func collectCloneSet(rootNames []string, typesByName map[string]*ast.TypeSpec) map[string]struct{} {
	cloneSet := make(map[string]struct{})
	queue := append([]string(nil), rootNames...)

	for len(queue) > 0 {
		name := queue[0]
		queue = queue[1:]
		if _, seen := cloneSet[name]; seen {
			continue
		}
		spec, ok := typesByName[name]
		if !ok {
			continue
		}
		structType, ok := spec.Type.(*ast.StructType)
		if !ok {
			continue
		}
		cloneSet[name] = struct{}{}
		for _, depName := range referencedCloneableTypes(structType, typesByName) {
			queue = append(queue, depName)
		}
	}

	return cloneSet
}

func referencedCloneableTypes(structType *ast.StructType, typesByName map[string]*ast.TypeSpec) []string {
	seen := make(map[string]struct{})
	ast.Inspect(structType, func(node ast.Node) bool {
		ident, ok := node.(*ast.Ident)
		if !ok {
			return true
		}
		spec, ok := typesByName[ident.Name]
		if !ok {
			return true
		}
		if _, ok := spec.Type.(*ast.StructType); ok {
			seen[ident.Name] = struct{}{}
		}
		return true
	})

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func renderClonedStruct(name string, structType *ast.StructType, cloneSet map[string]struct{}) string {
	var b strings.Builder
	b.WriteString("type ")
	b.WriteString(name)
	b.WriteString(" struct {\n")
	for _, field := range structType.Fields.List {
		if len(field.Names) == 0 {
			b.WriteString("\t")
			b.WriteString(renderExpr(rewriteExpr(field.Type, cloneSet)))
			if field.Tag != nil {
				b.WriteString(" ")
				b.WriteString(field.Tag.Value)
			}
			b.WriteString("\n")
			continue
		}
		for i, fieldName := range field.Names {
			if i == 0 {
				b.WriteString("\t")
			} else {
				b.WriteString(", ")
			}
			b.WriteString(fieldName.Name)
		}
		b.WriteString(" ")
		b.WriteString(renderExpr(rewriteExpr(field.Type, cloneSet)))
		if field.Tag != nil {
			b.WriteString(" ")
			b.WriteString(field.Tag.Value)
		}
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

func rewriteExpr(expr ast.Expr, cloneSet map[string]struct{}) ast.Expr {
	switch e := expr.(type) {
	case *ast.Ident:
		if _, ok := cloneSet[e.Name]; ok {
			return ast.NewIdent(genSchemaTypeName(e.Name))
		}
		return ast.NewIdent(e.Name)
	case *ast.StarExpr:
		return &ast.StarExpr{X: rewriteExpr(e.X, cloneSet)}
	case *ast.ArrayType:
		return &ast.ArrayType{Len: e.Len, Elt: rewriteExpr(e.Elt, cloneSet)}
	case *ast.MapType:
		return &ast.MapType{Key: rewriteExpr(e.Key, cloneSet), Value: rewriteExpr(e.Value, cloneSet)}
	case *ast.SelectorExpr:
		return &ast.SelectorExpr{X: rewriteExpr(e.X, cloneSet), Sel: ast.NewIdent(e.Sel.Name)}
	case *ast.InterfaceType:
		return &ast.InterfaceType{Methods: e.Methods, Incomplete: e.Incomplete}
	default:
		return e
	}
}

func renderExpr(expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, token.NewFileSet(), expr)
	return buf.String()
}

func structUsesTime(structType *ast.StructType, cloneSet map[string]struct{}) bool {
	for _, field := range structType.Fields.List {
		if containsClonedTimeRef(rewriteExpr(field.Type, cloneSet)) {
			return true
		}
	}
	return false
}

func containsClonedTimeRef(expr ast.Expr) bool {
	usesTime := false
	ast.Inspect(expr, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		ident, ok := selector.X.(*ast.Ident)
		if ok && ident.Name == "time" && selector.Sel.Name == "Time" {
			usesTime = true
			return false
		}
		return true
	})
	return usesTime
}

func genSchemaTypeName(name string) string {
	return "GenSchema" + name
}

func contains(values []string, target string) bool {
	for _, value := range values {
		if value == target {
			return true
		}
	}
	return false
}
