// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog_metadata.sql

package dbstore

import (
	"context"
	"database/sql"
)

const deleteCatalogMetadataByTypeAndName = `-- name: DeleteCatalogMetadataByTypeAndName :exec
DELETE FROM catalog_metadata
WHERE securable_type = ? AND securable_name = ?
`

type DeleteCatalogMetadataByTypeAndNameParams struct {
	SecurableType string
	SecurableName string
}

func (q *Queries) DeleteCatalogMetadataByTypeAndName(ctx context.Context, arg DeleteCatalogMetadataByTypeAndNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteCatalogMetadataByTypeAndName, arg.SecurableType, arg.SecurableName)
	return err
}

const deleteCatalogMetadataByTypeAndPattern = `-- name: DeleteCatalogMetadataByTypeAndPattern :exec
DELETE FROM catalog_metadata
WHERE securable_type = ? AND securable_name LIKE ?
`

type DeleteCatalogMetadataByTypeAndPatternParams struct {
	SecurableType string
	SecurableName string
}

func (q *Queries) DeleteCatalogMetadataByTypeAndPattern(ctx context.Context, arg DeleteCatalogMetadataByTypeAndPatternParams) error {
	_, err := q.db.ExecContext(ctx, deleteCatalogMetadataByTypeAndPattern, arg.SecurableType, arg.SecurableName)
	return err
}

const getCatalogMetadata = `-- name: GetCatalogMetadata :one
SELECT securable_type, securable_name, comment, properties, owner, created_at, updated_at, deleted_at FROM catalog_metadata
WHERE securable_type = ? AND securable_name = ?
`

type GetCatalogMetadataParams struct {
	SecurableType string
	SecurableName string
}

func (q *Queries) GetCatalogMetadata(ctx context.Context, arg GetCatalogMetadataParams) (CatalogMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getCatalogMetadata, arg.SecurableType, arg.SecurableName)
	var i CatalogMetadatum
	err := row.Scan(
		&i.SecurableType,
		&i.SecurableName,
		&i.Comment,
		&i.Properties,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertOrReplaceCatalogMetadata = `-- name: InsertOrReplaceCatalogMetadata :exec
INSERT OR REPLACE INTO catalog_metadata (securable_type, securable_name, comment, owner)
VALUES (?, ?, ?, ?)
`

type InsertOrReplaceCatalogMetadataParams struct {
	SecurableType string
	SecurableName string
	Comment       sql.NullString
	Owner         sql.NullString
}

func (q *Queries) InsertOrReplaceCatalogMetadata(ctx context.Context, arg InsertOrReplaceCatalogMetadataParams) error {
	_, err := q.db.ExecContext(ctx, insertOrReplaceCatalogMetadata,
		arg.SecurableType,
		arg.SecurableName,
		arg.Comment,
		arg.Owner,
	)
	return err
}

const softDeleteCatalogMetadata = `-- name: SoftDeleteCatalogMetadata :exec
UPDATE catalog_metadata SET deleted_at = datetime('now')
WHERE securable_type = ? AND securable_name = ?
`

type SoftDeleteCatalogMetadataParams struct {
	SecurableType string
	SecurableName string
}

func (q *Queries) SoftDeleteCatalogMetadata(ctx context.Context, arg SoftDeleteCatalogMetadataParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCatalogMetadata, arg.SecurableType, arg.SecurableName)
	return err
}

const softDeleteCatalogMetadataByPattern = `-- name: SoftDeleteCatalogMetadataByPattern :exec
UPDATE catalog_metadata SET deleted_at = datetime('now')
WHERE securable_type = ? AND securable_name LIKE ?
`

type SoftDeleteCatalogMetadataByPatternParams struct {
	SecurableType string
	SecurableName string
}

func (q *Queries) SoftDeleteCatalogMetadataByPattern(ctx context.Context, arg SoftDeleteCatalogMetadataByPatternParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCatalogMetadataByPattern, arg.SecurableType, arg.SecurableName)
	return err
}

const upsertCatalogMetadata = `-- name: UpsertCatalogMetadata :exec
INSERT INTO catalog_metadata (securable_type, securable_name, comment, properties, owner)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(securable_type, securable_name)
DO UPDATE SET comment = COALESCE(excluded.comment, comment),
              properties = COALESCE(excluded.properties, properties),
              owner = COALESCE(excluded.owner, owner),
              updated_at = datetime('now')
`

type UpsertCatalogMetadataParams struct {
	SecurableType string
	SecurableName string
	Comment       sql.NullString
	Properties    sql.NullString
	Owner         sql.NullString
}

func (q *Queries) UpsertCatalogMetadata(ctx context.Context, arg UpsertCatalogMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertCatalogMetadata,
		arg.SecurableType,
		arg.SecurableName,
		arg.Comment,
		arg.Properties,
		arg.Owner,
	)
	return err
}
