// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: column_metadata.sql

package dbstore

import (
	"context"
	"database/sql"
)

const deleteColumnMetadataByTable = `-- name: DeleteColumnMetadataByTable :exec
DELETE FROM column_metadata WHERE table_securable_name = ?
`

func (q *Queries) DeleteColumnMetadataByTable(ctx context.Context, tableSecurableName string) error {
	_, err := q.db.ExecContext(ctx, deleteColumnMetadataByTable, tableSecurableName)
	return err
}

const deleteColumnMetadataByTablePattern = `-- name: DeleteColumnMetadataByTablePattern :exec
DELETE FROM column_metadata WHERE table_securable_name LIKE ?
`

func (q *Queries) DeleteColumnMetadataByTablePattern(ctx context.Context, tableSecurableName string) error {
	_, err := q.db.ExecContext(ctx, deleteColumnMetadataByTablePattern, tableSecurableName)
	return err
}

const getColumnMetadata = `-- name: GetColumnMetadata :one
SELECT table_securable_name, column_name, comment, properties, updated_at FROM column_metadata
WHERE table_securable_name = ? AND column_name = ?
`

type GetColumnMetadataParams struct {
	TableSecurableName string
	ColumnName         string
}

func (q *Queries) GetColumnMetadata(ctx context.Context, arg GetColumnMetadataParams) (ColumnMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getColumnMetadata, arg.TableSecurableName, arg.ColumnName)
	var i ColumnMetadatum
	err := row.Scan(
		&i.TableSecurableName,
		&i.ColumnName,
		&i.Comment,
		&i.Properties,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertColumnMetadata = `-- name: UpsertColumnMetadata :exec
INSERT INTO column_metadata (table_securable_name, column_name, comment, properties)
VALUES (?, ?, ?, ?)
ON CONFLICT(table_securable_name, column_name)
DO UPDATE SET comment = COALESCE(excluded.comment, comment),
              properties = COALESCE(excluded.properties, properties),
              updated_at = datetime('now')
`

type UpsertColumnMetadataParams struct {
	TableSecurableName string
	ColumnName         string
	Comment            sql.NullString
	Properties         sql.NullString
}

func (q *Queries) UpsertColumnMetadata(ctx context.Context, arg UpsertColumnMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertColumnMetadata,
		arg.TableSecurableName,
		arg.ColumnName,
		arg.Comment,
		arg.Properties,
	)
	return err
}
