// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: external_locations.sql

package dbstore

import (
	"context"
)

const countExternalLocations = `-- name: CountExternalLocations :one
SELECT COUNT(*) FROM external_locations
`

func (q *Queries) CountExternalLocations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExternalLocations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalLocation = `-- name: CreateExternalLocation :one
INSERT INTO external_locations (name, url, credential_name, storage_type, comment, owner, read_only)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, url, credential_name, storage_type, comment, owner, read_only, created_at, updated_at
`

type CreateExternalLocationParams struct {
	Name           string
	Url            string
	CredentialName string
	StorageType    string
	Comment        string
	Owner          string
	ReadOnly       int64
}

func (q *Queries) CreateExternalLocation(ctx context.Context, arg CreateExternalLocationParams) (ExternalLocation, error) {
	row := q.db.QueryRowContext(ctx, createExternalLocation,
		arg.Name,
		arg.Url,
		arg.CredentialName,
		arg.StorageType,
		arg.Comment,
		arg.Owner,
		arg.ReadOnly,
	)
	var i ExternalLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CredentialName,
		&i.StorageType,
		&i.Comment,
		&i.Owner,
		&i.ReadOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExternalLocation = `-- name: DeleteExternalLocation :exec
DELETE FROM external_locations WHERE id = ?
`

func (q *Queries) DeleteExternalLocation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExternalLocation, id)
	return err
}

const getExternalLocation = `-- name: GetExternalLocation :one
SELECT id, name, url, credential_name, storage_type, comment, owner, read_only, created_at, updated_at FROM external_locations WHERE id = ?
`

func (q *Queries) GetExternalLocation(ctx context.Context, id int64) (ExternalLocation, error) {
	row := q.db.QueryRowContext(ctx, getExternalLocation, id)
	var i ExternalLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CredentialName,
		&i.StorageType,
		&i.Comment,
		&i.Owner,
		&i.ReadOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalLocationByName = `-- name: GetExternalLocationByName :one
SELECT id, name, url, credential_name, storage_type, comment, owner, read_only, created_at, updated_at FROM external_locations WHERE name = ?
`

func (q *Queries) GetExternalLocationByName(ctx context.Context, name string) (ExternalLocation, error) {
	row := q.db.QueryRowContext(ctx, getExternalLocationByName, name)
	var i ExternalLocation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.CredentialName,
		&i.StorageType,
		&i.Comment,
		&i.Owner,
		&i.ReadOnly,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExternalLocations = `-- name: ListExternalLocations :many
SELECT id, name, url, credential_name, storage_type, comment, owner, read_only, created_at, updated_at FROM external_locations ORDER BY name LIMIT ? OFFSET ?
`

type ListExternalLocationsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListExternalLocations(ctx context.Context, arg ListExternalLocationsParams) ([]ExternalLocation, error) {
	rows, err := q.db.QueryContext(ctx, listExternalLocations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExternalLocation
	for rows.Next() {
		var i ExternalLocation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.CredentialName,
			&i.StorageType,
			&i.Comment,
			&i.Owner,
			&i.ReadOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExternalLocation = `-- name: UpdateExternalLocation :exec
UPDATE external_locations
SET url = COALESCE(?, url),
    credential_name = COALESCE(?, credential_name),
    comment = COALESCE(?, comment),
    owner = COALESCE(?, owner),
    read_only = COALESCE(?, read_only),
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateExternalLocationParams struct {
	Url            string
	CredentialName string
	Comment        string
	Owner          string
	ReadOnly       int64
	ID             int64
}

func (q *Queries) UpdateExternalLocation(ctx context.Context, arg UpdateExternalLocationParams) error {
	_, err := q.db.ExecContext(ctx, updateExternalLocation,
		arg.Url,
		arg.CredentialName,
		arg.Comment,
		arg.Owner,
		arg.ReadOnly,
		arg.ID,
	)
	return err
}
