// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package dbstore

import (
	"context"
	"database/sql"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT OR IGNORE INTO group_members (group_id, member_type, member_id)
VALUES (?, ?, ?)
`

type AddGroupMemberParams struct {
	GroupID    string
	MemberType string
	MemberID   string
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, addGroupMember, arg.GroupID, arg.MemberType, arg.MemberID)
	return err
}

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT COUNT(*) as cnt FROM group_members WHERE group_id = ?
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countGroups = `-- name: CountGroups :one
SELECT COUNT(*) as cnt FROM groups
`

func (q *Queries) CountGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroups)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, description)
VALUES (?, ?, ?)
RETURNING id, name, description, created_at
`

type CreateGroupParams struct {
	ID          string
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.ID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGroup, id)
	return err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, created_at FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, created_at FROM groups WHERE name = ?
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupsForMember = `-- name: GetGroupsForMember :many
SELECT g.id, g.name, g.description, g.created_at FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.member_type = ? AND gm.member_id = ?
`

type GetGroupsForMemberParams struct {
	MemberType string
	MemberID   string
}

func (q *Queries) GetGroupsForMember(ctx context.Context, arg GetGroupsForMemberParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsForMember, arg.MemberType, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT group_id, member_type, member_id FROM group_members WHERE group_id = ?
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(&i.GroupID, &i.MemberType, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembersPaginated = `-- name: ListGroupMembersPaginated :many
SELECT group_id, member_type, member_id FROM group_members WHERE group_id = ? ORDER BY member_id LIMIT ? OFFSET ?
`

type ListGroupMembersPaginatedParams struct {
	GroupID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListGroupMembersPaginated(ctx context.Context, arg ListGroupMembersPaginatedParams) ([]GroupMember, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembersPaginated, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(&i.GroupID, &i.MemberType, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, created_at FROM groups ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsPaginated = `-- name: ListGroupsPaginated :many
SELECT id, name, description, created_at FROM groups ORDER BY id LIMIT ? OFFSET ?
`

type ListGroupsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListGroupsPaginated(ctx context.Context, arg ListGroupsPaginatedParams) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroupsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = ? AND member_type = ? AND member_id = ?
`

type RemoveGroupMemberParams struct {
	GroupID    string
	MemberType string
	MemberID   string
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeGroupMember, arg.GroupID, arg.MemberType, arg.MemberID)
	return err
}
