// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lineage.sql

package dbstore

import (
	"context"
	"database/sql"
)

const countDownstreamLineage = `-- name: CountDownstreamLineage :one
SELECT COUNT(DISTINCT source_table || '->' || COALESCE(target_table, '')) as cnt FROM lineage_edges WHERE source_table = ?
`

func (q *Queries) CountDownstreamLineage(ctx context.Context, sourceTable string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDownstreamLineage, sourceTable)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countUpstreamLineage = `-- name: CountUpstreamLineage :one
SELECT COUNT(DISTINCT source_table) as cnt FROM lineage_edges WHERE target_table = ?
`

func (q *Queries) CountUpstreamLineage(ctx context.Context, targetTable sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpstreamLineage, targetTable)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const getDownstreamLineage = `-- name: GetDownstreamLineage :many
SELECT DISTINCT source_table, target_table, edge_type, principal_name, created_at, source_schema, target_schema
FROM lineage_edges
WHERE source_table = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetDownstreamLineageParams struct {
	SourceTable string
	Limit       int64
	Offset      int64
}

type GetDownstreamLineageRow struct {
	SourceTable   string
	TargetTable   sql.NullString
	EdgeType      string
	PrincipalName string
	CreatedAt     string
	SourceSchema  sql.NullString
	TargetSchema  sql.NullString
}

func (q *Queries) GetDownstreamLineage(ctx context.Context, arg GetDownstreamLineageParams) ([]GetDownstreamLineageRow, error) {
	rows, err := q.db.QueryContext(ctx, getDownstreamLineage, arg.SourceTable, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDownstreamLineageRow
	for rows.Next() {
		var i GetDownstreamLineageRow
		if err := rows.Scan(
			&i.SourceTable,
			&i.TargetTable,
			&i.EdgeType,
			&i.PrincipalName,
			&i.CreatedAt,
			&i.SourceSchema,
			&i.TargetSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpstreamLineage = `-- name: GetUpstreamLineage :many
SELECT DISTINCT source_table, target_table, edge_type, principal_name, created_at, source_schema, target_schema
FROM lineage_edges
WHERE target_table = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetUpstreamLineageParams struct {
	TargetTable sql.NullString
	Limit       int64
	Offset      int64
}

type GetUpstreamLineageRow struct {
	SourceTable   string
	TargetTable   sql.NullString
	EdgeType      string
	PrincipalName string
	CreatedAt     string
	SourceSchema  sql.NullString
	TargetSchema  sql.NullString
}

func (q *Queries) GetUpstreamLineage(ctx context.Context, arg GetUpstreamLineageParams) ([]GetUpstreamLineageRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpstreamLineage, arg.TargetTable, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpstreamLineageRow
	for rows.Next() {
		var i GetUpstreamLineageRow
		if err := rows.Scan(
			&i.SourceTable,
			&i.TargetTable,
			&i.EdgeType,
			&i.PrincipalName,
			&i.CreatedAt,
			&i.SourceSchema,
			&i.TargetSchema,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLineageEdge = `-- name: InsertLineageEdge :exec
INSERT INTO lineage_edges (source_table, target_table, edge_type, principal_name, query_hash, source_schema, target_schema)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertLineageEdgeParams struct {
	SourceTable   string
	TargetTable   sql.NullString
	EdgeType      string
	PrincipalName string
	QueryHash     sql.NullString
	SourceSchema  sql.NullString
	TargetSchema  sql.NullString
}

func (q *Queries) InsertLineageEdge(ctx context.Context, arg InsertLineageEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertLineageEdge,
		arg.SourceTable,
		arg.TargetTable,
		arg.EdgeType,
		arg.PrincipalName,
		arg.QueryHash,
		arg.SourceSchema,
		arg.TargetSchema,
	)
	return err
}
