// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbstore

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID          int64
	KeyHash     string
	PrincipalID int64
	Name        string
	ExpiresAt   sql.NullString
	CreatedAt   string
}

type AuditLog struct {
	ID             int64
	PrincipalName  string
	Action         string
	StatementType  sql.NullString
	OriginalSql    sql.NullString
	RewrittenSql   sql.NullString
	TablesAccessed sql.NullString
	Status         string
	ErrorMessage   sql.NullString
	DurationMs     sql.NullInt64
	CreatedAt      string
	RowsReturned   sql.NullInt64
}

type CatalogMetadatum struct {
	SecurableType string
	SecurableName string
	Comment       sql.NullString
	Properties    sql.NullString
	Owner         sql.NullString
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     sql.NullString
}

type ColumnMask struct {
	ID             int64
	TableID        int64
	ColumnName     string
	MaskExpression string
	Description    sql.NullString
	CreatedAt      string
}

type ColumnMaskBinding struct {
	ID            int64
	ColumnMaskID  int64
	PrincipalID   int64
	PrincipalType string
	SeeOriginal   int64
}

type ColumnMetadatum struct {
	TableSecurableName string
	ColumnName         string
	Comment            sql.NullString
	Properties         sql.NullString
	UpdatedAt          sql.NullString
}

type ComputeAssignment struct {
	ID            int64
	PrincipalID   int64
	PrincipalType string
	EndpointID    int64
	IsDefault     int64
	FallbackLocal int64
	CreatedAt     time.Time
}

type ComputeEndpoint struct {
	ID          int64
	ExternalID  string
	Name        string
	Url         string
	Type        string
	Status      string
	Size        string
	MaxMemoryGb sql.NullInt64
	AuthToken   string
	Owner       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ExternalLocation struct {
	ID             int64
	Name           string
	Url            string
	CredentialName string
	StorageType    string
	Comment        string
	Owner          string
	ReadOnly       int64
	CreatedAt      string
	UpdatedAt      string
}

type ExternalTable struct {
	ID           int64
	SchemaName   string
	TableName    string
	FileFormat   string
	SourcePath   string
	LocationName string
	Comment      string
	Owner        string
	CreatedAt    string
	UpdatedAt    string
	DeletedAt    sql.NullString
}

type ExternalTableColumn struct {
	ID              int64
	ExternalTableID int64
	ColumnName      string
	ColumnType      string
	Position        int64
}

type Group struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   string
}

type GroupMember struct {
	GroupID    int64
	MemberType string
	MemberID   int64
}

type LineageEdge struct {
	ID            int64
	SourceTable   string
	TargetTable   sql.NullString
	EdgeType      string
	PrincipalName string
	QueryHash     sql.NullString
	CreatedAt     string
	SourceSchema  sql.NullString
	TargetSchema  sql.NullString
}

type Principal struct {
	ID             int64
	Name           string
	Type           string
	IsAdmin        int64
	CreatedAt      string
	ExternalID     sql.NullString
	ExternalIssuer sql.NullString
}

type PrivilegeGrant struct {
	ID            int64
	PrincipalID   int64
	PrincipalType string
	SecurableType string
	SecurableID   int64
	Privilege     string
	GrantedBy     sql.NullInt64
	GrantedAt     string
}

type RowFilter struct {
	ID          int64
	TableID     int64
	FilterSql   string
	Description sql.NullString
	CreatedAt   string
}

type RowFilterBinding struct {
	ID            int64
	RowFilterID   int64
	PrincipalID   int64
	PrincipalType string
}

type StorageCredential struct {
	ID                         int64
	Name                       string
	CredentialType             string
	KeyIDEncrypted             string
	SecretEncrypted            string
	Endpoint                   string
	Region                     string
	UrlStyle                   string
	Comment                    string
	Owner                      string
	CreatedAt                  string
	UpdatedAt                  string
	AzureAccountName           string
	AzureAccountKeyEncrypted   string
	AzureClientID              string
	AzureTenantID              string
	AzureClientSecretEncrypted string
	GcsKeyFilePath             string
}

type TableStatistic struct {
	TableSecurableName string
	RowCount           sql.NullInt64
	SizeBytes          sql.NullInt64
	ColumnCount        sql.NullInt64
	LastProfiledAt     sql.NullString
	ProfiledBy         sql.NullString
}

type Tag struct {
	ID        int64
	Key       string
	Value     sql.NullString
	CreatedBy string
	CreatedAt string
}

type TagAssignment struct {
	ID            int64
	TagID         int64
	SecurableType string
	SecurableID   int64
	ColumnName    sql.NullString
	AssignedBy    string
	AssignedAt    string
}

type View struct {
	ID             int64
	SchemaID       int64
	Name           string
	ViewDefinition string
	Comment        sql.NullString
	Properties     sql.NullString
	Owner          string
	SourceTables   sql.NullString
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      sql.NullString
}

type Volume struct {
	ID              int64
	Name            string
	SchemaName      string
	CatalogName     string
	VolumeType      string
	StorageLocation string
	Comment         string
	Owner           string
	CreatedAt       string
	UpdatedAt       string
}
