// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notebook_jobs.sql

package dbstore

import (
	"context"
	"database/sql"
)

const countNotebookJobs = `-- name: CountNotebookJobs :one
SELECT COUNT(*) FROM notebook_jobs WHERE notebook_id = ?
`

func (q *Queries) CountNotebookJobs(ctx context.Context, notebookID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotebookJobs, notebookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotebookJob = `-- name: CreateNotebookJob :one
INSERT INTO notebook_jobs (id, notebook_id, session_id, state)
VALUES (?, ?, ?, ?)
RETURNING id, notebook_id, session_id, state, result, error, created_at, updated_at
`

type CreateNotebookJobParams struct {
	ID         string
	NotebookID string
	SessionID  string
	State      string
}

func (q *Queries) CreateNotebookJob(ctx context.Context, arg CreateNotebookJobParams) (NotebookJob, error) {
	row := q.db.QueryRowContext(ctx, createNotebookJob,
		arg.ID,
		arg.NotebookID,
		arg.SessionID,
		arg.State,
	)
	var i NotebookJob
	err := row.Scan(
		&i.ID,
		&i.NotebookID,
		&i.SessionID,
		&i.State,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotebookJob = `-- name: GetNotebookJob :one
SELECT id, notebook_id, session_id, state, result, error, created_at, updated_at FROM notebook_jobs WHERE id = ?
`

func (q *Queries) GetNotebookJob(ctx context.Context, id string) (NotebookJob, error) {
	row := q.db.QueryRowContext(ctx, getNotebookJob, id)
	var i NotebookJob
	err := row.Scan(
		&i.ID,
		&i.NotebookID,
		&i.SessionID,
		&i.State,
		&i.Result,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotebookJobs = `-- name: ListNotebookJobs :many
SELECT id, notebook_id, session_id, state, result, error, created_at, updated_at FROM notebook_jobs
WHERE notebook_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListNotebookJobsParams struct {
	NotebookID string
	Limit      int64
	Offset     int64
}

func (q *Queries) ListNotebookJobs(ctx context.Context, arg ListNotebookJobsParams) ([]NotebookJob, error) {
	rows, err := q.db.QueryContext(ctx, listNotebookJobs, arg.NotebookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotebookJob
	for rows.Next() {
		var i NotebookJob
		if err := rows.Scan(
			&i.ID,
			&i.NotebookID,
			&i.SessionID,
			&i.State,
			&i.Result,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotebookJobState = `-- name: UpdateNotebookJobState :exec
UPDATE notebook_jobs
SET state = ?, result = ?, error = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateNotebookJobStateParams struct {
	State  string
	Result sql.NullString
	Error  sql.NullString
	ID     string
}

func (q *Queries) UpdateNotebookJobState(ctx context.Context, arg UpdateNotebookJobStateParams) error {
	_, err := q.db.ExecContext(ctx, updateNotebookJobState,
		arg.State,
		arg.Result,
		arg.Error,
		arg.ID,
	)
	return err
}
