// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: principals.sql

package dbstore

import (
	"context"
	"database/sql"
)

const countPrincipals = `-- name: CountPrincipals :one
SELECT COUNT(*) as cnt FROM principals
`

func (q *Queries) CountPrincipals(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrincipals)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createPrincipal = `-- name: CreatePrincipal :one
INSERT INTO principals (name, type, is_admin)
VALUES (?, ?, ?)
RETURNING id, name, type, is_admin, created_at, external_id, external_issuer
`

type CreatePrincipalParams struct {
	Name    string
	Type    string
	IsAdmin int64
}

func (q *Queries) CreatePrincipal(ctx context.Context, arg CreatePrincipalParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, createPrincipal, arg.Name, arg.Type, arg.IsAdmin)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExternalID,
		&i.ExternalIssuer,
	)
	return i, err
}

const createPrincipalWithExternalID = `-- name: CreatePrincipalWithExternalID :one
INSERT INTO principals (name, type, is_admin, external_id, external_issuer)
VALUES (?, ?, ?, ?, ?)
RETURNING id, name, type, is_admin, created_at, external_id, external_issuer
`

type CreatePrincipalWithExternalIDParams struct {
	Name           string
	Type           string
	IsAdmin        int64
	ExternalID     sql.NullString
	ExternalIssuer sql.NullString
}

func (q *Queries) CreatePrincipalWithExternalID(ctx context.Context, arg CreatePrincipalWithExternalIDParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, createPrincipalWithExternalID,
		arg.Name,
		arg.Type,
		arg.IsAdmin,
		arg.ExternalID,
		arg.ExternalIssuer,
	)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExternalID,
		&i.ExternalIssuer,
	)
	return i, err
}

const deletePrincipal = `-- name: DeletePrincipal :exec
DELETE FROM principals WHERE id = ?
`

func (q *Queries) DeletePrincipal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePrincipal, id)
	return err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, name, type, is_admin, created_at, external_id, external_issuer FROM principals WHERE id = ?
`

func (q *Queries) GetPrincipal(ctx context.Context, id int64) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipal, id)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExternalID,
		&i.ExternalIssuer,
	)
	return i, err
}

const getPrincipalByExternalID = `-- name: GetPrincipalByExternalID :one
SELECT id, name, type, is_admin, created_at, external_id, external_issuer FROM principals
WHERE external_issuer = ? AND external_id = ?
LIMIT 1
`

type GetPrincipalByExternalIDParams struct {
	ExternalIssuer sql.NullString
	ExternalID     sql.NullString
}

func (q *Queries) GetPrincipalByExternalID(ctx context.Context, arg GetPrincipalByExternalIDParams) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByExternalID, arg.ExternalIssuer, arg.ExternalID)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExternalID,
		&i.ExternalIssuer,
	)
	return i, err
}

const getPrincipalByName = `-- name: GetPrincipalByName :one
SELECT id, name, type, is_admin, created_at, external_id, external_issuer FROM principals WHERE name = ?
`

func (q *Queries) GetPrincipalByName(ctx context.Context, name string) (Principal, error) {
	row := q.db.QueryRowContext(ctx, getPrincipalByName, name)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.ExternalID,
		&i.ExternalIssuer,
	)
	return i, err
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT id, name, type, is_admin, created_at, external_id, external_issuer FROM principals ORDER BY name
`

func (q *Queries) ListPrincipals(ctx context.Context) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ExternalID,
			&i.ExternalIssuer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipalsPaginated = `-- name: ListPrincipalsPaginated :many
SELECT id, name, type, is_admin, created_at, external_id, external_issuer FROM principals ORDER BY id LIMIT ? OFFSET ?
`

type ListPrincipalsPaginatedParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPrincipalsPaginated(ctx context.Context, arg ListPrincipalsPaginatedParams) ([]Principal, error) {
	rows, err := q.db.QueryContext(ctx, listPrincipalsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Principal
	for rows.Next() {
		var i Principal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.ExternalID,
			&i.ExternalIssuer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdmin = `-- name: SetAdmin :exec
UPDATE principals SET is_admin = ? WHERE id = ?
`

type SetAdminParams struct {
	IsAdmin int64
	ID      int64
}

func (q *Queries) SetAdmin(ctx context.Context, arg SetAdminParams) error {
	_, err := q.db.ExecContext(ctx, setAdmin, arg.IsAdmin, arg.ID)
	return err
}
