// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privileges.sql

package dbstore

import (
	"context"
	"database/sql"
)

const checkDirectGrant = `-- name: CheckDirectGrant :one
SELECT COUNT(*) as cnt FROM privilege_grants
WHERE principal_id = ? AND principal_type = ? AND securable_type = ? AND securable_id = ? AND privilege = ?
`

type CheckDirectGrantParams struct {
	PrincipalID   string
	PrincipalType string
	SecurableType string
	SecurableID   string
	Privilege     string
}

func (q *Queries) CheckDirectGrant(ctx context.Context, arg CheckDirectGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDirectGrant,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.SecurableType,
		arg.SecurableID,
		arg.Privilege,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const checkDirectGrantAny = `-- name: CheckDirectGrantAny :one
SELECT COUNT(*) as cnt FROM privilege_grants
WHERE principal_id = ? AND principal_type = ? AND securable_type = ? AND securable_id = ?
  AND privilege IN ('ALL_PRIVILEGES', ?)
`

type CheckDirectGrantAnyParams struct {
	PrincipalID   string
	PrincipalType string
	SecurableType string
	SecurableID   string
	Privilege     string
}

func (q *Queries) CheckDirectGrantAny(ctx context.Context, arg CheckDirectGrantAnyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkDirectGrantAny,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.SecurableType,
		arg.SecurableID,
		arg.Privilege,
	)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countGrantsForPrincipal = `-- name: CountGrantsForPrincipal :one
SELECT COUNT(*) as cnt FROM privilege_grants
WHERE principal_id = ? AND principal_type = ?
`

type CountGrantsForPrincipalParams struct {
	PrincipalID   string
	PrincipalType string
}

func (q *Queries) CountGrantsForPrincipal(ctx context.Context, arg CountGrantsForPrincipalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGrantsForPrincipal, arg.PrincipalID, arg.PrincipalType)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const countGrantsForSecurable = `-- name: CountGrantsForSecurable :one
SELECT COUNT(*) as cnt FROM privilege_grants
WHERE securable_type = ? AND securable_id = ?
`

type CountGrantsForSecurableParams struct {
	SecurableType string
	SecurableID   string
}

func (q *Queries) CountGrantsForSecurable(ctx context.Context, arg CountGrantsForSecurableParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGrantsForSecurable, arg.SecurableType, arg.SecurableID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const grantPrivilege = `-- name: GrantPrivilege :one
INSERT INTO privilege_grants (id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at
`

type GrantPrivilegeParams struct {
	ID            string
	PrincipalID   string
	PrincipalType string
	SecurableType string
	SecurableID   string
	Privilege     string
	GrantedBy     sql.NullString
}

func (q *Queries) GrantPrivilege(ctx context.Context, arg GrantPrivilegeParams) (PrivilegeGrant, error) {
	row := q.db.QueryRowContext(ctx, grantPrivilege,
		arg.ID,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.SecurableType,
		arg.SecurableID,
		arg.Privilege,
		arg.GrantedBy,
	)
	var i PrivilegeGrant
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.PrincipalType,
		&i.SecurableType,
		&i.SecurableID,
		&i.Privilege,
		&i.GrantedBy,
		&i.GrantedAt,
	)
	return i, err
}

const listAllGrantsForIdentities = `-- name: ListAllGrantsForIdentities :many
SELECT id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at FROM privilege_grants
WHERE (principal_type = 'user' AND principal_id = ?)
   OR (principal_type = 'group' AND principal_id IN (
       SELECT group_id FROM group_members WHERE member_type = 'user' AND member_id = ?
   ))
`

type ListAllGrantsForIdentitiesParams struct {
	PrincipalID string
	MemberID    string
}

func (q *Queries) ListAllGrantsForIdentities(ctx context.Context, arg ListAllGrantsForIdentitiesParams) ([]PrivilegeGrant, error) {
	rows, err := q.db.QueryContext(ctx, listAllGrantsForIdentities, arg.PrincipalID, arg.MemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivilegeGrant
	for rows.Next() {
		var i PrivilegeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.SecurableType,
			&i.SecurableID,
			&i.Privilege,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForPrincipal = `-- name: ListGrantsForPrincipal :many
SELECT id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at FROM privilege_grants
WHERE principal_id = ? AND principal_type = ?
`

type ListGrantsForPrincipalParams struct {
	PrincipalID   string
	PrincipalType string
}

func (q *Queries) ListGrantsForPrincipal(ctx context.Context, arg ListGrantsForPrincipalParams) ([]PrivilegeGrant, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForPrincipal, arg.PrincipalID, arg.PrincipalType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivilegeGrant
	for rows.Next() {
		var i PrivilegeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.SecurableType,
			&i.SecurableID,
			&i.Privilege,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForPrincipalOnSecurable = `-- name: ListGrantsForPrincipalOnSecurable :many
SELECT id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at FROM privilege_grants
WHERE principal_id = ? AND principal_type = ? AND securable_type = ? AND securable_id = ?
`

type ListGrantsForPrincipalOnSecurableParams struct {
	PrincipalID   string
	PrincipalType string
	SecurableType string
	SecurableID   string
}

func (q *Queries) ListGrantsForPrincipalOnSecurable(ctx context.Context, arg ListGrantsForPrincipalOnSecurableParams) ([]PrivilegeGrant, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForPrincipalOnSecurable,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.SecurableType,
		arg.SecurableID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivilegeGrant
	for rows.Next() {
		var i PrivilegeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.SecurableType,
			&i.SecurableID,
			&i.Privilege,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForPrincipalPaginated = `-- name: ListGrantsForPrincipalPaginated :many
SELECT id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at FROM privilege_grants
WHERE principal_id = ? AND principal_type = ?
ORDER BY id LIMIT ? OFFSET ?
`

type ListGrantsForPrincipalPaginatedParams struct {
	PrincipalID   string
	PrincipalType string
	Limit         int64
	Offset        int64
}

func (q *Queries) ListGrantsForPrincipalPaginated(ctx context.Context, arg ListGrantsForPrincipalPaginatedParams) ([]PrivilegeGrant, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForPrincipalPaginated,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivilegeGrant
	for rows.Next() {
		var i PrivilegeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.SecurableType,
			&i.SecurableID,
			&i.Privilege,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForSecurable = `-- name: ListGrantsForSecurable :many
SELECT id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at FROM privilege_grants
WHERE securable_type = ? AND securable_id = ?
`

type ListGrantsForSecurableParams struct {
	SecurableType string
	SecurableID   string
}

func (q *Queries) ListGrantsForSecurable(ctx context.Context, arg ListGrantsForSecurableParams) ([]PrivilegeGrant, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForSecurable, arg.SecurableType, arg.SecurableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivilegeGrant
	for rows.Next() {
		var i PrivilegeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.SecurableType,
			&i.SecurableID,
			&i.Privilege,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForSecurablePaginated = `-- name: ListGrantsForSecurablePaginated :many
SELECT id, principal_id, principal_type, securable_type, securable_id, privilege, granted_by, granted_at FROM privilege_grants
WHERE securable_type = ? AND securable_id = ?
ORDER BY id LIMIT ? OFFSET ?
`

type ListGrantsForSecurablePaginatedParams struct {
	SecurableType string
	SecurableID   string
	Limit         int64
	Offset        int64
}

func (q *Queries) ListGrantsForSecurablePaginated(ctx context.Context, arg ListGrantsForSecurablePaginatedParams) ([]PrivilegeGrant, error) {
	rows, err := q.db.QueryContext(ctx, listGrantsForSecurablePaginated,
		arg.SecurableType,
		arg.SecurableID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivilegeGrant
	for rows.Next() {
		var i PrivilegeGrant
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.PrincipalType,
			&i.SecurableType,
			&i.SecurableID,
			&i.Privilege,
			&i.GrantedBy,
			&i.GrantedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePrivilege = `-- name: RevokePrivilege :exec
DELETE FROM privilege_grants
WHERE principal_id = ? AND principal_type = ? AND securable_type = ? AND securable_id = ? AND privilege = ?
`

type RevokePrivilegeParams struct {
	PrincipalID   string
	PrincipalType string
	SecurableType string
	SecurableID   string
	Privilege     string
}

func (q *Queries) RevokePrivilege(ctx context.Context, arg RevokePrivilegeParams) error {
	_, err := q.db.ExecContext(ctx, revokePrivilege,
		arg.PrincipalID,
		arg.PrincipalType,
		arg.SecurableType,
		arg.SecurableID,
		arg.Privilege,
	)
	return err
}

const revokePrivilegeByID = `-- name: RevokePrivilegeByID :exec
DELETE FROM privilege_grants WHERE id = ?
`

func (q *Queries) RevokePrivilegeByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokePrivilegeByID, id)
	return err
}
