// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: row_filters.sql

package dbstore

import (
	"context"
	"database/sql"
)

const bindRowFilter = `-- name: BindRowFilter :exec
INSERT OR IGNORE INTO row_filter_bindings (id, row_filter_id, principal_id, principal_type)
VALUES (?, ?, ?, ?)
`

type BindRowFilterParams struct {
	ID            string
	RowFilterID   string
	PrincipalID   string
	PrincipalType string
}

func (q *Queries) BindRowFilter(ctx context.Context, arg BindRowFilterParams) error {
	_, err := q.db.ExecContext(ctx, bindRowFilter,
		arg.ID,
		arg.RowFilterID,
		arg.PrincipalID,
		arg.PrincipalType,
	)
	return err
}

const countRowFiltersForTable = `-- name: CountRowFiltersForTable :one
SELECT COUNT(*) as cnt FROM row_filters WHERE table_id = ?
`

func (q *Queries) CountRowFiltersForTable(ctx context.Context, tableID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRowFiltersForTable, tableID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createRowFilter = `-- name: CreateRowFilter :one
INSERT INTO row_filters (id, table_id, filter_sql, description)
VALUES (?, ?, ?, ?)
RETURNING id, table_id, filter_sql, description, created_at
`

type CreateRowFilterParams struct {
	ID          string
	TableID     string
	FilterSql   string
	Description sql.NullString
}

func (q *Queries) CreateRowFilter(ctx context.Context, arg CreateRowFilterParams) (RowFilter, error) {
	row := q.db.QueryRowContext(ctx, createRowFilter,
		arg.ID,
		arg.TableID,
		arg.FilterSql,
		arg.Description,
	)
	var i RowFilter
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.FilterSql,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRowFilter = `-- name: DeleteRowFilter :exec
DELETE FROM row_filters WHERE id = ?
`

func (q *Queries) DeleteRowFilter(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRowFilter, id)
	return err
}

const deleteRowFiltersByTable = `-- name: DeleteRowFiltersByTable :exec
DELETE FROM row_filters WHERE table_id = ?
`

func (q *Queries) DeleteRowFiltersByTable(ctx context.Context, tableID string) error {
	_, err := q.db.ExecContext(ctx, deleteRowFiltersByTable, tableID)
	return err
}

const getRowFilterBindingsForFilter = `-- name: GetRowFilterBindingsForFilter :many
SELECT id, row_filter_id, principal_id, principal_type FROM row_filter_bindings WHERE row_filter_id = ?
`

func (q *Queries) GetRowFilterBindingsForFilter(ctx context.Context, rowFilterID string) ([]RowFilterBinding, error) {
	rows, err := q.db.QueryContext(ctx, getRowFilterBindingsForFilter, rowFilterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowFilterBinding
	for rows.Next() {
		var i RowFilterBinding
		if err := rows.Scan(
			&i.ID,
			&i.RowFilterID,
			&i.PrincipalID,
			&i.PrincipalType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRowFiltersForPrincipal = `-- name: GetRowFiltersForPrincipal :many
SELECT rf.id, rf.table_id, rf.filter_sql, rf.description, rf.created_at FROM row_filters rf
JOIN row_filter_bindings rfb ON rf.id = rfb.row_filter_id
WHERE rfb.principal_id = ? AND rfb.principal_type = ?
`

type GetRowFiltersForPrincipalParams struct {
	PrincipalID   string
	PrincipalType string
}

func (q *Queries) GetRowFiltersForPrincipal(ctx context.Context, arg GetRowFiltersForPrincipalParams) ([]RowFilter, error) {
	rows, err := q.db.QueryContext(ctx, getRowFiltersForPrincipal, arg.PrincipalID, arg.PrincipalType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowFilter
	for rows.Next() {
		var i RowFilter
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.FilterSql,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRowFiltersForTable = `-- name: GetRowFiltersForTable :many
SELECT id, table_id, filter_sql, description, created_at FROM row_filters WHERE table_id = ?
`

func (q *Queries) GetRowFiltersForTable(ctx context.Context, tableID string) ([]RowFilter, error) {
	rows, err := q.db.QueryContext(ctx, getRowFiltersForTable, tableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowFilter
	for rows.Next() {
		var i RowFilter
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.FilterSql,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRowFiltersForTableAndPrincipal = `-- name: GetRowFiltersForTableAndPrincipal :many
SELECT rf.id, rf.table_id, rf.filter_sql, rf.description, rf.created_at FROM row_filters rf
JOIN row_filter_bindings rfb ON rf.id = rfb.row_filter_id
WHERE rf.table_id = ? AND rfb.principal_id = ? AND rfb.principal_type = ?
`

type GetRowFiltersForTableAndPrincipalParams struct {
	TableID       string
	PrincipalID   string
	PrincipalType string
}

func (q *Queries) GetRowFiltersForTableAndPrincipal(ctx context.Context, arg GetRowFiltersForTableAndPrincipalParams) ([]RowFilter, error) {
	rows, err := q.db.QueryContext(ctx, getRowFiltersForTableAndPrincipal, arg.TableID, arg.PrincipalID, arg.PrincipalType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowFilter
	for rows.Next() {
		var i RowFilter
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.FilterSql,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRowFiltersForTablePaginated = `-- name: ListRowFiltersForTablePaginated :many
SELECT id, table_id, filter_sql, description, created_at FROM row_filters WHERE table_id = ? ORDER BY id LIMIT ? OFFSET ?
`

type ListRowFiltersForTablePaginatedParams struct {
	TableID string
	Limit   int64
	Offset  int64
}

func (q *Queries) ListRowFiltersForTablePaginated(ctx context.Context, arg ListRowFiltersForTablePaginatedParams) ([]RowFilter, error) {
	rows, err := q.db.QueryContext(ctx, listRowFiltersForTablePaginated, arg.TableID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RowFilter
	for rows.Next() {
		var i RowFilter
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.FilterSql,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindRowFilter = `-- name: UnbindRowFilter :exec
DELETE FROM row_filter_bindings
WHERE row_filter_id = ? AND principal_id = ? AND principal_type = ?
`

type UnbindRowFilterParams struct {
	RowFilterID   string
	PrincipalID   string
	PrincipalType string
}

func (q *Queries) UnbindRowFilter(ctx context.Context, arg UnbindRowFilterParams) error {
	_, err := q.db.ExecContext(ctx, unbindRowFilter, arg.RowFilterID, arg.PrincipalID, arg.PrincipalType)
	return err
}
