// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage_credentials.sql

package dbstore

import (
	"context"
)

const countStorageCredentials = `-- name: CountStorageCredentials :one
SELECT COUNT(*) FROM storage_credentials
`

func (q *Queries) CountStorageCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStorageCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStorageCredential = `-- name: CreateStorageCredential :one
INSERT INTO storage_credentials (name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at
`

type CreateStorageCredentialParams struct {
	Name            string
	CredentialType  string
	KeyIDEncrypted  string
	SecretEncrypted string
	Endpoint        string
	Region          string
	UrlStyle        string
	Comment         string
	Owner           string
}

func (q *Queries) CreateStorageCredential(ctx context.Context, arg CreateStorageCredentialParams) (StorageCredential, error) {
	row := q.db.QueryRowContext(ctx, createStorageCredential,
		arg.Name,
		arg.CredentialType,
		arg.KeyIDEncrypted,
		arg.SecretEncrypted,
		arg.Endpoint,
		arg.Region,
		arg.UrlStyle,
		arg.Comment,
		arg.Owner,
	)
	var i StorageCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialType,
		&i.KeyIDEncrypted,
		&i.SecretEncrypted,
		&i.Endpoint,
		&i.Region,
		&i.UrlStyle,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStorageCredential = `-- name: DeleteStorageCredential :exec
DELETE FROM storage_credentials WHERE id = ?
`

func (q *Queries) DeleteStorageCredential(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStorageCredential, id)
	return err
}

const getStorageCredential = `-- name: GetStorageCredential :one
SELECT id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at FROM storage_credentials WHERE id = ?
`

func (q *Queries) GetStorageCredential(ctx context.Context, id int64) (StorageCredential, error) {
	row := q.db.QueryRowContext(ctx, getStorageCredential, id)
	var i StorageCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialType,
		&i.KeyIDEncrypted,
		&i.SecretEncrypted,
		&i.Endpoint,
		&i.Region,
		&i.UrlStyle,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStorageCredentialByName = `-- name: GetStorageCredentialByName :one
SELECT id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at FROM storage_credentials WHERE name = ?
`

func (q *Queries) GetStorageCredentialByName(ctx context.Context, name string) (StorageCredential, error) {
	row := q.db.QueryRowContext(ctx, getStorageCredentialByName, name)
	var i StorageCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialType,
		&i.KeyIDEncrypted,
		&i.SecretEncrypted,
		&i.Endpoint,
		&i.Region,
		&i.UrlStyle,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStorageCredentials = `-- name: ListStorageCredentials :many
SELECT id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at FROM storage_credentials ORDER BY name LIMIT ? OFFSET ?
`

type ListStorageCredentialsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListStorageCredentials(ctx context.Context, arg ListStorageCredentialsParams) ([]StorageCredential, error) {
	rows, err := q.db.QueryContext(ctx, listStorageCredentials, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageCredential
	for rows.Next() {
		var i StorageCredential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CredentialType,
			&i.KeyIDEncrypted,
			&i.SecretEncrypted,
			&i.Endpoint,
			&i.Region,
			&i.UrlStyle,
			&i.Comment,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageCredential = `-- name: UpdateStorageCredential :exec
UPDATE storage_credentials
SET key_id_encrypted = COALESCE(?, key_id_encrypted),
    secret_encrypted = COALESCE(?, secret_encrypted),
    endpoint = COALESCE(?, endpoint),
    region = COALESCE(?, region),
    url_style = COALESCE(?, url_style),
    comment = COALESCE(?, comment),
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateStorageCredentialParams struct {
	KeyIDEncrypted  string
	SecretEncrypted string
	Endpoint        string
	Region          string
	UrlStyle        string
	Comment         string
	ID              int64
}

func (q *Queries) UpdateStorageCredential(ctx context.Context, arg UpdateStorageCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateStorageCredential,
		arg.KeyIDEncrypted,
		arg.SecretEncrypted,
		arg.Endpoint,
		arg.Region,
		arg.UrlStyle,
		arg.Comment,
		arg.ID,
	)
	return err
}
