// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage_credentials.sql

package dbstore

import (
	"context"
)

const countStorageCredentials = `-- name: CountStorageCredentials :one
SELECT COUNT(*) FROM storage_credentials
`

func (q *Queries) CountStorageCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStorageCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStorageCredential = `-- name: CreateStorageCredential :one
INSERT INTO storage_credentials (
    name, credential_type,
    key_id_encrypted, secret_encrypted, endpoint, region, url_style,
    azure_account_name, azure_account_key_encrypted, azure_client_id, azure_tenant_id, azure_client_secret_encrypted,
    gcs_key_file_path,
    comment, owner
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at, azure_account_name, azure_account_key_encrypted, azure_client_id, azure_tenant_id, azure_client_secret_encrypted, gcs_key_file_path
`

type CreateStorageCredentialParams struct {
	Name                       string
	CredentialType             string
	KeyIDEncrypted             string
	SecretEncrypted            string
	Endpoint                   string
	Region                     string
	UrlStyle                   string
	AzureAccountName           string
	AzureAccountKeyEncrypted   string
	AzureClientID              string
	AzureTenantID              string
	AzureClientSecretEncrypted string
	GcsKeyFilePath             string
	Comment                    string
	Owner                      string
}

func (q *Queries) CreateStorageCredential(ctx context.Context, arg CreateStorageCredentialParams) (StorageCredential, error) {
	row := q.db.QueryRowContext(ctx, createStorageCredential,
		arg.Name,
		arg.CredentialType,
		arg.KeyIDEncrypted,
		arg.SecretEncrypted,
		arg.Endpoint,
		arg.Region,
		arg.UrlStyle,
		arg.AzureAccountName,
		arg.AzureAccountKeyEncrypted,
		arg.AzureClientID,
		arg.AzureTenantID,
		arg.AzureClientSecretEncrypted,
		arg.GcsKeyFilePath,
		arg.Comment,
		arg.Owner,
	)
	var i StorageCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialType,
		&i.KeyIDEncrypted,
		&i.SecretEncrypted,
		&i.Endpoint,
		&i.Region,
		&i.UrlStyle,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AzureAccountName,
		&i.AzureAccountKeyEncrypted,
		&i.AzureClientID,
		&i.AzureTenantID,
		&i.AzureClientSecretEncrypted,
		&i.GcsKeyFilePath,
	)
	return i, err
}

const deleteStorageCredential = `-- name: DeleteStorageCredential :exec
DELETE FROM storage_credentials WHERE id = ?
`

func (q *Queries) DeleteStorageCredential(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStorageCredential, id)
	return err
}

const getStorageCredential = `-- name: GetStorageCredential :one
SELECT id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at, azure_account_name, azure_account_key_encrypted, azure_client_id, azure_tenant_id, azure_client_secret_encrypted, gcs_key_file_path FROM storage_credentials WHERE id = ?
`

func (q *Queries) GetStorageCredential(ctx context.Context, id int64) (StorageCredential, error) {
	row := q.db.QueryRowContext(ctx, getStorageCredential, id)
	var i StorageCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialType,
		&i.KeyIDEncrypted,
		&i.SecretEncrypted,
		&i.Endpoint,
		&i.Region,
		&i.UrlStyle,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AzureAccountName,
		&i.AzureAccountKeyEncrypted,
		&i.AzureClientID,
		&i.AzureTenantID,
		&i.AzureClientSecretEncrypted,
		&i.GcsKeyFilePath,
	)
	return i, err
}

const getStorageCredentialByName = `-- name: GetStorageCredentialByName :one
SELECT id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at, azure_account_name, azure_account_key_encrypted, azure_client_id, azure_tenant_id, azure_client_secret_encrypted, gcs_key_file_path FROM storage_credentials WHERE name = ?
`

func (q *Queries) GetStorageCredentialByName(ctx context.Context, name string) (StorageCredential, error) {
	row := q.db.QueryRowContext(ctx, getStorageCredentialByName, name)
	var i StorageCredential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CredentialType,
		&i.KeyIDEncrypted,
		&i.SecretEncrypted,
		&i.Endpoint,
		&i.Region,
		&i.UrlStyle,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AzureAccountName,
		&i.AzureAccountKeyEncrypted,
		&i.AzureClientID,
		&i.AzureTenantID,
		&i.AzureClientSecretEncrypted,
		&i.GcsKeyFilePath,
	)
	return i, err
}

const listStorageCredentials = `-- name: ListStorageCredentials :many
SELECT id, name, credential_type, key_id_encrypted, secret_encrypted, endpoint, region, url_style, comment, owner, created_at, updated_at, azure_account_name, azure_account_key_encrypted, azure_client_id, azure_tenant_id, azure_client_secret_encrypted, gcs_key_file_path FROM storage_credentials ORDER BY name LIMIT ? OFFSET ?
`

type ListStorageCredentialsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListStorageCredentials(ctx context.Context, arg ListStorageCredentialsParams) ([]StorageCredential, error) {
	rows, err := q.db.QueryContext(ctx, listStorageCredentials, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StorageCredential
	for rows.Next() {
		var i StorageCredential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CredentialType,
			&i.KeyIDEncrypted,
			&i.SecretEncrypted,
			&i.Endpoint,
			&i.Region,
			&i.UrlStyle,
			&i.Comment,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AzureAccountName,
			&i.AzureAccountKeyEncrypted,
			&i.AzureClientID,
			&i.AzureTenantID,
			&i.AzureClientSecretEncrypted,
			&i.GcsKeyFilePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStorageCredential = `-- name: UpdateStorageCredential :exec
UPDATE storage_credentials
SET key_id_encrypted = COALESCE(?, key_id_encrypted),
    secret_encrypted = COALESCE(?, secret_encrypted),
    endpoint = COALESCE(?, endpoint),
    region = COALESCE(?, region),
    url_style = COALESCE(?, url_style),
    azure_account_name = COALESCE(?, azure_account_name),
    azure_account_key_encrypted = COALESCE(?, azure_account_key_encrypted),
    azure_client_id = COALESCE(?, azure_client_id),
    azure_tenant_id = COALESCE(?, azure_tenant_id),
    azure_client_secret_encrypted = COALESCE(?, azure_client_secret_encrypted),
    gcs_key_file_path = COALESCE(?, gcs_key_file_path),
    comment = COALESCE(?, comment),
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateStorageCredentialParams struct {
	KeyIDEncrypted             string
	SecretEncrypted            string
	Endpoint                   string
	Region                     string
	UrlStyle                   string
	AzureAccountName           string
	AzureAccountKeyEncrypted   string
	AzureClientID              string
	AzureTenantID              string
	AzureClientSecretEncrypted string
	GcsKeyFilePath             string
	Comment                    string
	ID                         int64
}

func (q *Queries) UpdateStorageCredential(ctx context.Context, arg UpdateStorageCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateStorageCredential,
		arg.KeyIDEncrypted,
		arg.SecretEncrypted,
		arg.Endpoint,
		arg.Region,
		arg.UrlStyle,
		arg.AzureAccountName,
		arg.AzureAccountKeyEncrypted,
		arg.AzureClientID,
		arg.AzureTenantID,
		arg.AzureClientSecretEncrypted,
		arg.GcsKeyFilePath,
		arg.Comment,
		arg.ID,
	)
	return err
}
