// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: table_statistics.sql

package dbstore

import (
	"context"
	"database/sql"
)

const deleteTableStatistics = `-- name: DeleteTableStatistics :exec
DELETE FROM table_statistics WHERE table_securable_name = ?
`

func (q *Queries) DeleteTableStatistics(ctx context.Context, tableSecurableName string) error {
	_, err := q.db.ExecContext(ctx, deleteTableStatistics, tableSecurableName)
	return err
}

const deleteTableStatisticsByPattern = `-- name: DeleteTableStatisticsByPattern :exec
DELETE FROM table_statistics WHERE table_securable_name LIKE ?
`

func (q *Queries) DeleteTableStatisticsByPattern(ctx context.Context, tableSecurableName string) error {
	_, err := q.db.ExecContext(ctx, deleteTableStatisticsByPattern, tableSecurableName)
	return err
}

const getTableStatistics = `-- name: GetTableStatistics :one
SELECT table_securable_name, row_count, size_bytes, column_count, last_profiled_at, profiled_by FROM table_statistics WHERE table_securable_name = ?
`

func (q *Queries) GetTableStatistics(ctx context.Context, tableSecurableName string) (TableStatistic, error) {
	row := q.db.QueryRowContext(ctx, getTableStatistics, tableSecurableName)
	var i TableStatistic
	err := row.Scan(
		&i.TableSecurableName,
		&i.RowCount,
		&i.SizeBytes,
		&i.ColumnCount,
		&i.LastProfiledAt,
		&i.ProfiledBy,
	)
	return i, err
}

const upsertTableStatistics = `-- name: UpsertTableStatistics :exec
INSERT INTO table_statistics (table_securable_name, row_count, size_bytes, column_count, last_profiled_at, profiled_by)
VALUES (?, ?, ?, ?, datetime('now'), ?)
ON CONFLICT(table_securable_name)
DO UPDATE SET row_count = excluded.row_count,
              size_bytes = excluded.size_bytes,
              column_count = excluded.column_count,
              last_profiled_at = datetime('now'),
              profiled_by = excluded.profiled_by
`

type UpsertTableStatisticsParams struct {
	TableSecurableName string
	RowCount           sql.NullInt64
	SizeBytes          sql.NullInt64
	ColumnCount        sql.NullInt64
	ProfiledBy         sql.NullString
}

func (q *Queries) UpsertTableStatistics(ctx context.Context, arg UpsertTableStatisticsParams) error {
	_, err := q.db.ExecContext(ctx, upsertTableStatistics,
		arg.TableSecurableName,
		arg.RowCount,
		arg.SizeBytes,
		arg.ColumnCount,
		arg.ProfiledBy,
	)
	return err
}
