// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package dbstore

import (
	"context"
	"database/sql"
)

const countViews = `-- name: CountViews :one
SELECT COUNT(*) as cnt FROM views WHERE schema_id = ?
`

func (q *Queries) CountViews(ctx context.Context, schemaID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countViews, schemaID)
	var cnt int64
	err := row.Scan(&cnt)
	return cnt, err
}

const createView = `-- name: CreateView :one
INSERT INTO views (schema_id, name, view_definition, comment, properties, owner, source_tables)
VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id, schema_id, name, view_definition, comment, properties, owner, source_tables, created_at, updated_at
`

type CreateViewParams struct {
	SchemaID       int64
	Name           string
	ViewDefinition string
	Comment        sql.NullString
	Properties     sql.NullString
	Owner          string
	SourceTables   sql.NullString
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) (View, error) {
	row := q.db.QueryRowContext(ctx, createView,
		arg.SchemaID,
		arg.Name,
		arg.ViewDefinition,
		arg.Comment,
		arg.Properties,
		arg.Owner,
		arg.SourceTables,
	)
	var i View
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Name,
		&i.ViewDefinition,
		&i.Comment,
		&i.Properties,
		&i.Owner,
		&i.SourceTables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM views WHERE schema_id = ? AND name = ?
`

type DeleteViewParams struct {
	SchemaID int64
	Name     string
}

func (q *Queries) DeleteView(ctx context.Context, arg DeleteViewParams) error {
	_, err := q.db.ExecContext(ctx, deleteView, arg.SchemaID, arg.Name)
	return err
}

const getViewByName = `-- name: GetViewByName :one
SELECT id, schema_id, name, view_definition, comment, properties, owner, source_tables, created_at, updated_at FROM views WHERE schema_id = ? AND name = ?
`

type GetViewByNameParams struct {
	SchemaID int64
	Name     string
}

func (q *Queries) GetViewByName(ctx context.Context, arg GetViewByNameParams) (View, error) {
	row := q.db.QueryRowContext(ctx, getViewByName, arg.SchemaID, arg.Name)
	var i View
	err := row.Scan(
		&i.ID,
		&i.SchemaID,
		&i.Name,
		&i.ViewDefinition,
		&i.Comment,
		&i.Properties,
		&i.Owner,
		&i.SourceTables,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listViews = `-- name: ListViews :many
SELECT id, schema_id, name, view_definition, comment, properties, owner, source_tables, created_at, updated_at FROM views WHERE schema_id = ? ORDER BY name LIMIT ? OFFSET ?
`

type ListViewsParams struct {
	SchemaID int64
	Limit    int64
	Offset   int64
}

func (q *Queries) ListViews(ctx context.Context, arg ListViewsParams) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listViews, arg.SchemaID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.SchemaID,
			&i.Name,
			&i.ViewDefinition,
			&i.Comment,
			&i.Properties,
			&i.Owner,
			&i.SourceTables,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
