// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: volumes.sql

package dbstore

import (
	"context"
)

const countVolumes = `-- name: CountVolumes :one
SELECT COUNT(*) FROM volumes WHERE schema_name = ?
`

func (q *Queries) CountVolumes(ctx context.Context, schemaName string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVolumes, schemaName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVolume = `-- name: CreateVolume :one
INSERT INTO volumes (name, schema_name, catalog_name, volume_type, storage_location, comment, owner)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, schema_name, catalog_name, volume_type, storage_location, comment, owner, created_at, updated_at
`

type CreateVolumeParams struct {
	Name            string
	SchemaName      string
	CatalogName     string
	VolumeType      string
	StorageLocation string
	Comment         string
	Owner           string
}

func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, createVolume,
		arg.Name,
		arg.SchemaName,
		arg.CatalogName,
		arg.VolumeType,
		arg.StorageLocation,
		arg.Comment,
		arg.Owner,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaName,
		&i.CatalogName,
		&i.VolumeType,
		&i.StorageLocation,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM volumes WHERE id = ?
`

func (q *Queries) DeleteVolume(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVolume, id)
	return err
}

const deleteVolumesBySchema = `-- name: DeleteVolumesBySchema :exec
DELETE FROM volumes WHERE schema_name = ?
`

func (q *Queries) DeleteVolumesBySchema(ctx context.Context, schemaName string) error {
	_, err := q.db.ExecContext(ctx, deleteVolumesBySchema, schemaName)
	return err
}

const getVolumeByName = `-- name: GetVolumeByName :one
SELECT id, name, schema_name, catalog_name, volume_type, storage_location, comment, owner, created_at, updated_at FROM volumes WHERE schema_name = ? AND name = ?
`

type GetVolumeByNameParams struct {
	SchemaName string
	Name       string
}

func (q *Queries) GetVolumeByName(ctx context.Context, arg GetVolumeByNameParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, getVolumeByName, arg.SchemaName, arg.Name)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SchemaName,
		&i.CatalogName,
		&i.VolumeType,
		&i.StorageLocation,
		&i.Comment,
		&i.Owner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVolumes = `-- name: ListVolumes :many
SELECT id, name, schema_name, catalog_name, volume_type, storage_location, comment, owner, created_at, updated_at FROM volumes WHERE schema_name = ? ORDER BY name LIMIT ? OFFSET ?
`

type ListVolumesParams struct {
	SchemaName string
	Limit      int64
	Offset     int64
}

func (q *Queries) ListVolumes(ctx context.Context, arg ListVolumesParams) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumes, arg.SchemaName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SchemaName,
			&i.CatalogName,
			&i.VolumeType,
			&i.StorageLocation,
			&i.Comment,
			&i.Owner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVolume = `-- name: UpdateVolume :exec
UPDATE volumes
SET name = COALESCE(?, name),
    comment = COALESCE(?, comment),
    owner = COALESCE(?, owner),
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateVolumeParams struct {
	Name    string
	Comment string
	Owner   string
	ID      int64
}

func (q *Queries) UpdateVolume(ctx context.Context, arg UpdateVolumeParams) error {
	_, err := q.db.ExecContext(ctx, updateVolume,
		arg.Name,
		arg.Comment,
		arg.Owner,
		arg.ID,
	)
	return err
}
