// Code generated by cli-gen. DO NOT EDIT.
package gen

import "github.com/spf13/cobra"

// AddGeneratedCommands adds all generated command groups to the root command.
func AddGeneratedCommands(rootCmd *cobra.Command, client *Client) {
	rootCmd.AddCommand(newItemsCmd(client))
	rootCmd.AddCommand(newTasksCmd(client))
}
