package security

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

type Routes interface {
	SecurityHome(http.ResponseWriter, *http.Request)
	SecurityPrincipalsList(http.ResponseWriter, *http.Request)
	SecurityPrincipalsNew(http.ResponseWriter, *http.Request)
	SecurityPrincipalsCreate(http.ResponseWriter, *http.Request)
	SecurityPrincipalsDetail(http.ResponseWriter, *http.Request)
	SecurityPrincipalsDelete(http.ResponseWriter, *http.Request)
	SecurityPrincipalsSetAdmin(http.ResponseWriter, *http.Request)
	SecurityGroupsList(http.ResponseWriter, *http.Request)
	SecurityGroupsNew(http.ResponseWriter, *http.Request)
	SecurityGroupsCreate(http.ResponseWriter, *http.Request)
	SecurityGroupsDetail(http.ResponseWriter, *http.Request)
	SecurityGroupsDelete(http.ResponseWriter, *http.Request)
	SecurityGroupsAddMember(http.ResponseWriter, *http.Request)
	SecurityGroupsRemoveMember(http.ResponseWriter, *http.Request)
	SecurityGrantsList(http.ResponseWriter, *http.Request)
	SecurityGrantsCreate(http.ResponseWriter, *http.Request)
	SecurityGrantsDelete(http.ResponseWriter, *http.Request)
	SecurityRowFiltersList(http.ResponseWriter, *http.Request)
	SecurityRowFiltersCreate(http.ResponseWriter, *http.Request)
	SecurityRowFiltersDelete(http.ResponseWriter, *http.Request)
	SecurityRowFiltersBind(http.ResponseWriter, *http.Request)
	SecurityRowFiltersUnbind(http.ResponseWriter, *http.Request)
	SecurityColumnMasksList(http.ResponseWriter, *http.Request)
	SecurityColumnMasksCreate(http.ResponseWriter, *http.Request)
	SecurityColumnMasksDelete(http.ResponseWriter, *http.Request)
	SecurityColumnMasksBind(http.ResponseWriter, *http.Request)
	SecurityColumnMasksUnbind(http.ResponseWriter, *http.Request)
	SecurityAPIKeysList(http.ResponseWriter, *http.Request)
	SecurityAPIKeysCreate(http.ResponseWriter, *http.Request)
	SecurityAPIKeysDelete(http.ResponseWriter, *http.Request)
	SecurityAPIKeysCleanup(http.ResponseWriter, *http.Request)
}

func MountRoutes(r chi.Router, h Routes) {
	r.Get("/security", h.SecurityHome)
	r.Get("/security/principals", h.SecurityPrincipalsList)
	r.Get("/security/principals/new", h.SecurityPrincipalsNew)
	r.Post("/security/principals", h.SecurityPrincipalsCreate)
	r.Get("/security/principals/{principalID}", h.SecurityPrincipalsDetail)
	r.Post("/security/principals/{principalID}/delete", h.SecurityPrincipalsDelete)
	r.Post("/security/principals/{principalID}/admin", h.SecurityPrincipalsSetAdmin)
	r.Get("/security/groups", h.SecurityGroupsList)
	r.Get("/security/groups/new", h.SecurityGroupsNew)
	r.Post("/security/groups", h.SecurityGroupsCreate)
	r.Get("/security/groups/{groupID}", h.SecurityGroupsDetail)
	r.Post("/security/groups/{groupID}/delete", h.SecurityGroupsDelete)
	r.Post("/security/groups/{groupID}/members", h.SecurityGroupsAddMember)
	r.Post("/security/groups/{groupID}/members/delete", h.SecurityGroupsRemoveMember)
	r.Get("/security/grants", h.SecurityGrantsList)
	r.Post("/security/grants", h.SecurityGrantsCreate)
	r.Post("/security/grants/{grantID}/delete", h.SecurityGrantsDelete)
	r.Get("/security/row-filters", h.SecurityRowFiltersList)
	r.Post("/security/row-filters", h.SecurityRowFiltersCreate)
	r.Post("/security/row-filters/{filterID}/delete", h.SecurityRowFiltersDelete)
	r.Post("/security/row-filters/bindings", h.SecurityRowFiltersBind)
	r.Post("/security/row-filters/bindings/delete", h.SecurityRowFiltersUnbind)
	r.Get("/security/column-masks", h.SecurityColumnMasksList)
	r.Post("/security/column-masks", h.SecurityColumnMasksCreate)
	r.Post("/security/column-masks/{maskID}/delete", h.SecurityColumnMasksDelete)
	r.Post("/security/column-masks/bindings", h.SecurityColumnMasksBind)
	r.Post("/security/column-masks/bindings/delete", h.SecurityColumnMasksUnbind)
	r.Get("/security/api-keys", h.SecurityAPIKeysList)
	r.Post("/security/api-keys", h.SecurityAPIKeysCreate)
	r.Post("/security/api-keys/{keyID}/delete", h.SecurityAPIKeysDelete)
	r.Post("/security/api-keys/cleanup", h.SecurityAPIKeysCleanup)
}
