Pipeline:
  description: A pipeline workflow definition for scheduling SQL notebook execution.
  type: object
  properties:
    id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440001
    name:
      type: string
      maxLength: 255
      pattern: '^\S.*$'
      example: daily-etl
    description:
      type: string
      maxLength: 4096
      pattern: '^[\s\S]*$'
      example: Daily ETL pipeline
    schedule_cron:
      type: string
      maxLength: 255
      pattern: '^[\S].*$'
      example: "0 2 * * *"
    is_paused:
      type: boolean
      example: false
    concurrency_limit:
      type: integer
      format: int32
      minimum: 0
      maximum: 100
      example: 1
    created_by:
      type: string
      maxLength: 255
      pattern: '^\S+$'
      example: admin
    created_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T09:30:00Z"
    updated_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T09:30:00Z"

PipelineJob:
  description: A job within a pipeline, referencing a notebook for execution.
  type: object
  properties:
    id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440010
    pipeline_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440001
    name:
      type: string
      maxLength: 255
      pattern: '^\S.*$'
      example: extract-data
    compute_endpoint_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440020
    depends_on:
      type: array
      maxItems: 100
      items:
        type: string
        maxLength: 255
        pattern: '^\S.*$'
      example: ["load-raw-data"]
    notebook_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440030
    job_type:
      type: string
      enum: [NOTEBOOK, MODEL_RUN]
      example: NOTEBOOK
    model_selector:
      type: string
      maxLength: 1024
      pattern: '^[\s\S]*$'
      example: tag:daily
    timeout_seconds:
      type: integer
      format: int64
      minimum: 0
      maximum: 86400
      example: 3600
    retry_count:
      type: integer
      format: int32
      minimum: 0
      maximum: 10
      example: 2
    job_order:
      type: integer
      format: int32
      minimum: 0
      maximum: 1000
      example: 0
    created_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T09:30:00Z"

PipelineRun:
  description: An execution instance of a pipeline.
  type: object
  properties:
    id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440050
    pipeline_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440001
    status:
      type: string
      enum: [PENDING, RUNNING, SUCCESS, FAILED, CANCELLED]
      example: RUNNING
    trigger_type:
      type: string
      enum: [MANUAL, SCHEDULED]
      example: MANUAL
    triggered_by:
      type: string
      maxLength: 255
      pattern: '^\S+$'
      example: admin
    parameters:
      type: object
      additionalProperties:
        type: string
        maxLength: 4096
        pattern: '^[\s\S]*$'
      example:
        env: production
    git_commit_hash:
      type: string
      maxLength: 64
      pattern: '^[0-9a-f]+$'
      example: a1b2c3d4e5f6
    started_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T10:00:00Z"
    finished_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T10:15:00Z"
    error_message:
      type: string
      maxLength: 4096
      pattern: '^[\s\S]*$'
      example: job extract-data failed after 3 retries
    created_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T10:00:00Z"

PipelineJobRun:
  description: Execution status of a single job within a pipeline run.
  type: object
  properties:
    id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440060
    run_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440050
    job_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440010
    job_name:
      type: string
      maxLength: 255
      pattern: '^\S.*$'
      example: extract-data
    status:
      type: string
      enum: [PENDING, RUNNING, SUCCESS, FAILED, SKIPPED, CANCELLED]
      example: SUCCESS
    started_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T10:00:00Z"
    finished_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T10:05:00Z"
    error_message:
      type: string
      maxLength: 4096
      pattern: '^[\s\S]*$'
      example: query execution timed out
    retry_attempt:
      type: integer
      format: int32
      minimum: 0
      maximum: 10
      example: 0
    created_at:
      type: string
      format: date-time
      maxLength: 64
      example: "2025-01-15T10:00:00Z"

CreatePipelineRequest:
  description: Request payload for creating a new pipeline.
  type: object
  additionalProperties: false
  required: [name]
  properties:
    name:
      type: string
      maxLength: 255
      pattern: '^\S.*$'
      example: daily-etl
    description:
      type: string
      maxLength: 4096
      pattern: '^[\s\S]*$'
      example: Daily ETL pipeline
    schedule_cron:
      type: string
      maxLength: 255
      pattern: '^[\S].*$'
      example: "0 2 * * *"
    is_paused:
      type: boolean
      default: false
      example: false
    concurrency_limit:
      type: integer
      format: int32
      minimum: 0
      maximum: 100
      default: 1
      example: 1

UpdatePipelineRequest:
  description: Request payload for updating an existing pipeline.
  type: object
  additionalProperties: false
  properties:
    description:
      type: string
      maxLength: 4096
      pattern: '^[\s\S]*$'
      example: Updated daily ETL pipeline
    schedule_cron:
      type: string
      maxLength: 255
      pattern: '^[\S].*$'
      example: "0 3 * * *"
    is_paused:
      type: boolean
      example: true
    concurrency_limit:
      type: integer
      format: int32
      minimum: 0
      maximum: 100
      example: 2

CreatePipelineJobRequest:
  description: Request payload for creating a new pipeline job.
  type: object
  additionalProperties: false
  required: [name]
  properties:
    name:
      type: string
      maxLength: 255
      pattern: '^\S.*$'
      example: extract-data
    compute_endpoint_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440020
    depends_on:
      type: array
      maxItems: 100
      items:
        type: string
        maxLength: 255
        pattern: '^\S.*$'
      example: ["load-raw-data"]
    notebook_id:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      maxLength: 36
      example: 550e8400-e29b-41d4-a716-446655440030
    job_type:
      type: string
      enum: [NOTEBOOK, MODEL_RUN]
      default: NOTEBOOK
      example: NOTEBOOK
    model_selector:
      type: string
      maxLength: 1024
      pattern: '^[\s\S]*$'
      example: tag:daily
    timeout_seconds:
      type: integer
      format: int64
      minimum: 0
      maximum: 86400
      example: 3600
    retry_count:
      type: integer
      format: int32
      minimum: 0
      maximum: 10
      default: 0
      example: 2
    job_order:
      type: integer
      format: int32
      minimum: 0
      maximum: 1000
      default: 0
      example: 0

TriggerPipelineRunRequest:
  description: Request payload for manually triggering a pipeline run.
  type: object
  additionalProperties: false
  properties:
    parameters:
      type: object
      additionalProperties:
        type: string
        maxLength: 4096
        pattern: '^[\s\S]*$'
      example:
        env: production

PipelineJobList:
  description: A paginated list of pipeline jobs.
  type: object
  properties:
    data:
      type: array
      maxItems: 1000
      items:
        $ref: '#/PipelineJob'
      example: []
    next_page_token:
      type: string
      maxLength: 4096
      pattern: '^\S+$'
      example: eyJpZCI6MTB9

PipelineJobRunList:
  description: A paginated list of pipeline job runs.
  type: object
  properties:
    data:
      type: array
      maxItems: 1000
      items:
        $ref: '#/PipelineJobRun'
      example: []
    next_page_token:
      type: string
      maxLength: 4096
      pattern: '^\S+$'
      example: eyJpZCI6MTB9

PaginatedPipelines:
  description: A paginated list of pipelines.
  type: object
  properties:
    data:
      type: array
      maxItems: 1000
      items:
        $ref: '#/Pipeline'
      example:
        - id: 550e8400-e29b-41d4-a716-446655440001
          name: daily-etl
          description: Daily ETL pipeline
          schedule_cron: "0 2 * * *"
          is_paused: false
          concurrency_limit: 1
          created_by: admin
          created_at: "2025-01-15T09:30:00Z"
          updated_at: "2025-01-15T09:30:00Z"
    next_page_token:
      type: string
      maxLength: 4096
      pattern: '^\S+$'
      example: eyJpZCI6MTB9

PaginatedPipelineRuns:
  description: A paginated list of pipeline runs.
  type: object
  properties:
    data:
      type: array
      maxItems: 1000
      items:
        $ref: '#/PipelineRun'
      example:
        - id: 550e8400-e29b-41d4-a716-446655440050
          pipeline_id: 550e8400-e29b-41d4-a716-446655440001
          status: SUCCESS
          trigger_type: SCHEDULED
          triggered_by: scheduler
          started_at: "2025-01-15T02:00:00Z"
          finished_at: "2025-01-15T02:15:00Z"
          created_at: "2025-01-15T02:00:00Z"
    next_page_token:
      type: string
      maxLength: 4096
      pattern: '^\S+$'
      example: eyJpZCI6MTB9
