package sitegen

import (
	"fmt"
	"html/template"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

func loadPages(root string, templates templateSet) ([]page, error) {
	pages := make([]page, 0)
	renderer := newDirectiveRenderer(templates)

	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}

		p, parseErr := parsePage(root, path, renderer)
		if parseErr != nil {
			return parseErr
		}
		pages = append(pages, p)
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk site content: %w", err)
	}

	sort.Slice(pages, func(i, j int) bool {
		return pages[i].RelPath < pages[j].RelPath
	})
	return pages, nil
}

func parsePage(root, path string, directives directiveRenderer) (page, error) {
	source, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return page{}, fmt.Errorf("read page %q: %w", path, err)
	}
	frontMatter, body := splitFrontMatter(string(source))
	body = stripGeneratedComment(body)
	relPath, err := filepath.Rel(root, path)
	if err != nil {
		return page{}, fmt.Errorf("rel path %q: %w", path, err)
	}
	relPath = filepath.ToSlash(relPath)
	kind, urlPath := routeForRelPath(relPath)

	if relPath == "index.md" {
		var home homeFrontMatter
		if err := yaml.Unmarshal([]byte(frontMatter), &home); err != nil {
			return page{}, fmt.Errorf("decode home front matter: %w", err)
		}
		if strings.TrimSpace(home.Hero.Headline) == "" {
			home.Hero.Headline = strings.TrimSpace(home.Hero.Text)
		}
		if strings.TrimSpace(home.Hero.Name) == "" {
			home.Hero.Name = strings.TrimSpace(home.Hero.Headline)
		}
		for i := range home.Hero.Actions {
			home.Hero.Actions[i].Link = rewriteLink(home.Hero.Actions[i].Link)
		}
		for i := range home.Pillars.Items {
			home.Pillars.Items[i].Link = rewriteLink(home.Pillars.Items[i].Link)
		}
		description := home.Hero.Tagline
		if description == "" {
			description = firstParagraph(body)
		}
		return page{
			SourcePath:   path,
			RelPath:      relPath,
			URLPath:      "/",
			MirrorPath:   "index.md",
			Title:        home.Hero.Name,
			Description:  description,
			Kind:         pageKindHome,
			BodyMarkdown: body,
			MirrorBody:   body,
			BodyHTML:     template.HTML(""),
			Headings:     extractHeadings(body),
			Keywords:     home.Keywords,
			IsHome:       true,
			Home:         home,
		}, nil
	}

	var fm docFrontMatter
	if frontMatter != "" {
		if err := yaml.Unmarshal([]byte(frontMatter), &fm); err != nil {
			return page{}, fmt.Errorf("decode front matter %q: %w", path, err)
		}
	}

	body = rewriteContentLinks(body)
	htmlMarkdown, mirror, err := transformDirectives(body, directives)
	if err != nil {
		return page{}, fmt.Errorf("transform directives %q: %w", path, err)
	}
	rendered, err := renderMarkdown(htmlMarkdown)
	if err != nil {
		return page{}, fmt.Errorf("render markdown %q: %w", path, err)
	}

	title := strings.TrimSpace(fm.Title)
	if title == "" {
		title = firstHeading(body)
	}
	description := strings.TrimSpace(fm.Description)
	if description == "" {
		description = firstParagraph(mirror)
	}

	rendered = addHeadingAnchors(rendered)
	rendered = stripLeadingH1(rendered)
	rendered = enhanceTables(rendered)
	rendered = enhanceCodeBlocks(rendered)
	if kind == pageKindAPI {
		rendered = enhanceAPIHTML(rendered)
	}

	return page{
		SourcePath:   path,
		RelPath:      relPath,
		URLPath:      urlPath,
		MirrorPath:   strings.TrimSuffix(relPath, filepath.Ext(relPath)) + ".md",
		Title:        title,
		Description:  description,
		Kind:         kind,
		Section:      sectionForPage(relPath, kind),
		BodyMarkdown: body,
		MirrorBody:   mirror,
		// #nosec G203 -- rendered markdown is limited to repository-owned docs and generated content.
		BodyHTML: template.HTML(rendered),
		Headings: extractHeadings(mirror),
		Keywords: fm.Keywords,
	}, nil
}

func splitFrontMatter(content string) (string, string) {
	if !strings.HasPrefix(content, "---\n") {
		return "", content
	}
	rest := strings.TrimPrefix(content, "---\n")
	idx := strings.Index(rest, "\n---\n")
	if idx < 0 {
		return "", content
	}
	return rest[:idx], rest[idx+5:]
}

func stripGeneratedComment(source string) string {
	return strings.TrimSpace(strings.ReplaceAll(source, "<!-- Code generated by cmd/docsgen. DO NOT EDIT. -->", ""))
}

func writeMirrorMarkdown(outDir string, p page) error {
	target := filepath.Join(outDir, "llms", filepath.FromSlash(p.MirrorPath))
	if err := os.MkdirAll(filepath.Dir(target), 0o750); err != nil {
		return fmt.Errorf("mkdir llms dir: %w", err)
	}

	var content strings.Builder
	content.WriteString("# ")
	content.WriteString(p.Title)
	content.WriteString("\n\n")
	if p.IsHome {
		writeHomeMirror(&content, p.Home)
	} else {
		if p.Description != "" {
			content.WriteString(p.Description)
			content.WriteString("\n\n")
		}
		content.WriteString(strings.TrimSpace(p.MirrorBody))
		content.WriteString("\n")
	}

	return os.WriteFile(target, []byte(content.String()), 0o600)
}

func writeHomeMirror(content *strings.Builder, home homeFrontMatter) {
	if headline := strings.TrimSpace(home.Hero.Headline); headline != "" {
		content.WriteString(headline)
		content.WriteString("\n\n")
	}
	if tagline := strings.TrimSpace(home.Hero.Tagline); tagline != "" {
		content.WriteString(tagline)
		content.WriteString("\n\n")
	}

	writeHomeMirrorSection(content, home.Pillars)
}

func writeHomeMirrorSection(content *strings.Builder, section homeSection) {
	if strings.TrimSpace(section.Title) == "" {
		return
	}
	content.WriteString("## ")
	content.WriteString(section.Title)
	content.WriteString("\n\n")
	if details := strings.TrimSpace(section.Details); details != "" {
		content.WriteString(details)
		content.WriteString("\n\n")
	}
	for _, item := range section.Items {
		title := strings.TrimSpace(item.Title)
		if title == "" {
			continue
		}
		content.WriteString("### ")
		content.WriteString(title)
		content.WriteString("\n\n")
		if details := strings.TrimSpace(item.Details); details != "" {
			content.WriteString(details)
			content.WriteString("\n\n")
		}
	}
}

func rewriteContentLinks(source string) string {
	replacements := []struct {
		old string
		new string
	}{
		{old: "](/start-here/", new: "](/docs/start-here/"},
		{old: "](/how-to/", new: "](/docs/how-to/"},
		{old: "](/core-concepts/", new: "](/docs/core-concepts/"},
		{old: "](/operations/", new: "](/docs/operations/"},
		{old: "](/reference/generated/api/", new: "](/api-reference/"},
		{old: "](/reference/generated/declarative/", new: "](/docs/reference/generated/declarative/"},
		{old: "](/reference/", new: "](/docs/reference/"},
		{old: "](/browser-local-compute", new: "](/docs/browser-local-compute/"},
		{old: "](/architecture-governance", new: "](/docs/architecture-governance/"},
		{old: "\"/start-here/", new: "\"/docs/start-here/"},
		{old: "\"/how-to/", new: "\"/docs/how-to/"},
		{old: "\"/core-concepts/", new: "\"/docs/core-concepts/"},
		{old: "\"/operations/", new: "\"/docs/operations/"},
		{old: "\"/reference/generated/api/", new: "\"/api-reference/"},
		{old: "\"/reference/generated/declarative/", new: "\"/docs/reference/generated/declarative/"},
		{old: "\"/reference/", new: "\"/docs/reference/"},
		{old: "\"/browser-local-compute", new: "\"/docs/browser-local-compute/"},
		{old: "\"/architecture-governance", new: "\"/docs/architecture-governance/"},
	}
	for _, replacement := range replacements {
		source = strings.ReplaceAll(source, replacement.old, replacement.new)
	}
	return source
}

func rewriteLink(link string) string {
	return strings.TrimSuffix(strings.TrimPrefix(rewriteContentLinks(`"`+link+`"`), `"`), `"`)
}

func buildHomeView(home homeFrontMatter) homePageView {
	cards := make([]homeFeatureCardView, 0, len(home.Pillars.Items))
	for i, item := range home.Pillars.Items {
		spanClass := "lg:col-span-5"
		if i == 0 || i == 3 {
			spanClass = "lg:col-span-7"
		}
		cards = append(cards, homeFeatureCardView{
			SpanClass: spanClass,
			Item:      item,
		})
	}

	return homePageView{
		Hero: homeHeroView{
			Eyebrow:       home.Hero.Eyebrow,
			Headline:      home.Hero.Headline,
			Tagline:       home.Hero.Tagline,
			SnapshotTitle: home.Hero.SnapshotTitle,
			SnapshotNote:  home.Hero.SnapshotNote,
			Actions:       home.Hero.Actions,
			Proofs:        home.Hero.Proofs,
			Snapshot:      home.Hero.Snapshot,
			Visual: homeVisualView{
				AccessTitle:    "Access",
				AccessValue:    "Browser, SQL, API, CLI",
				PolicyTitle:    "Policy",
				PolicyValue:    "RBAC, filters, masks",
				ExecutionTitle: "Execution",
				ExecutionValue: "DuckLake with DuckDB underneath",
			},
		},
		Pillars: homeSectionView{
			Eyebrow: home.Pillars.Eyebrow,
			Title:   home.Pillars.Title,
			Details: home.Pillars.Details,
			Cards:   cards,
		},
	}
}
