apiVersion: duck/v1
kind: PrincipalList
principals:
  - name: __DUCK_DEV_BOOTSTRAP_PRINCIPAL__
    type: user
    is_admin: true
  - name: analyst
    type: user
    is_admin: false
  - name: data_eng
    type: user
    is_admin: false
  - name: product_owner
    type: user
    is_admin: false
