package ui

import (
	"io/fs"
	"net/http"

	"github.com/go-chi/chi/v5"

	"duck-demo/internal/ui/assets"
)

func MountRoutes(r chi.Router, h *Handler) {
	r.Get("/login", h.LoginPage)
	r.Post("/login", h.LoginSubmit)
	r.Get("/login/oidc", h.OIDCLoginStart)
	r.Get("/login/oidc/callback", h.OIDCLoginCallback)
	r.Post("/logout", h.Logout)

	staticFS, err := fs.Sub(assets.StaticFS(), "static")
	if err == nil {
		r.Handle("/static/*", http.StripPrefix("/ui/static/", http.FileServer(http.FS(staticFS))))
	}

	r.Group(func(r chi.Router) {
		r.Use(h.RequireWebSession)
		r.Use(h.EnsureCSRFToken)
		r.Use(h.RequireCSRF)
		r.Get("/", h.Home)
		r.Get("/components", h.ComponentsPage)
		r.Get("/sql", h.SQLEditorPage)
		r.Get("/sql/runtime/manifest", h.SQLEditorRuntimeManifest)
		r.Post("/sql/run", h.SQLEditorRun)
		r.Post("/sql/run-async", h.SQLEditorRunAsync)
		r.Post("/sql/download.csv", h.SQLEditorDownloadCSV)
		r.Get("/sql/jobs", h.SQLEditorJobsList)
		r.Get("/sql/jobs/{jobID}", h.SQLEditorJobDetail)
		r.Post("/sql/jobs/{jobID}/cancel", h.SQLEditorJobCancel)
		r.Post("/sql/jobs/{jobID}/delete", h.SQLEditorJobDelete)

		r.Get("/catalogs", h.CatalogsList)
		r.Get("/catalogs/{catalogName}", h.CatalogsDetail)
		r.Get("/catalogs/new", h.CatalogsNew)
		r.Post("/catalogs", h.CatalogsCreate)
		r.Get("/catalogs/{catalogName}/edit", h.CatalogsEdit)
		r.Post("/catalogs/{catalogName}/update", h.CatalogsUpdate)
		r.Post("/catalogs/{catalogName}/delete", h.CatalogsDelete)
		r.Post("/catalogs/{catalogName}/set-default", h.CatalogsSetDefault)
		r.Get("/catalogs/{catalogName}/schemas/new", h.CatalogSchemasNew)
		r.Post("/catalogs/{catalogName}/schemas", h.CatalogSchemasCreate)
		r.Get("/catalogs/{catalogName}/schemas/{schemaName}", h.CatalogSchemasDetail)
		r.Get("/catalogs/{catalogName}/schemas/{schemaName}/edit", h.CatalogSchemasEdit)
		r.Post("/catalogs/{catalogName}/schemas/{schemaName}/update", h.CatalogSchemasUpdate)
		r.Post("/catalogs/{catalogName}/schemas/{schemaName}/delete", h.CatalogSchemasDelete)
		r.Get("/catalogs/{catalogName}/schemas/{schemaName}/tables/{tableName}", h.CatalogTablesDetail)
		r.Get("/catalogs/{catalogName}/schemas/{schemaName}/views/{viewName}", h.CatalogViewsDetail)

		r.Get("/security", h.SecurityHome)
		r.Get("/security/principals", h.SecurityPrincipalsList)
		r.Get("/security/principals/new", h.SecurityPrincipalsNew)
		r.Post("/security/principals", h.SecurityPrincipalsCreate)
		r.Get("/security/principals/{principalID}", h.SecurityPrincipalsDetail)
		r.Post("/security/principals/{principalID}/delete", h.SecurityPrincipalsDelete)
		r.Post("/security/principals/{principalID}/admin", h.SecurityPrincipalsSetAdmin)
		r.Get("/security/groups", h.SecurityGroupsList)
		r.Get("/security/groups/new", h.SecurityGroupsNew)
		r.Post("/security/groups", h.SecurityGroupsCreate)
		r.Get("/security/groups/{groupID}", h.SecurityGroupsDetail)
		r.Post("/security/groups/{groupID}/delete", h.SecurityGroupsDelete)
		r.Post("/security/groups/{groupID}/members", h.SecurityGroupsAddMember)
		r.Post("/security/groups/{groupID}/members/delete", h.SecurityGroupsRemoveMember)
		r.Get("/security/grants", h.SecurityGrantsList)
		r.Post("/security/grants", h.SecurityGrantsCreate)
		r.Post("/security/grants/{grantID}/delete", h.SecurityGrantsDelete)
		r.Get("/security/row-filters", h.SecurityRowFiltersList)
		r.Post("/security/row-filters", h.SecurityRowFiltersCreate)
		r.Post("/security/row-filters/{filterID}/delete", h.SecurityRowFiltersDelete)
		r.Post("/security/row-filters/bindings", h.SecurityRowFiltersBind)
		r.Post("/security/row-filters/bindings/delete", h.SecurityRowFiltersUnbind)
		r.Get("/security/column-masks", h.SecurityColumnMasksList)
		r.Post("/security/column-masks", h.SecurityColumnMasksCreate)
		r.Post("/security/column-masks/{maskID}/delete", h.SecurityColumnMasksDelete)
		r.Post("/security/column-masks/bindings", h.SecurityColumnMasksBind)
		r.Post("/security/column-masks/bindings/delete", h.SecurityColumnMasksUnbind)
		r.Get("/security/api-keys", h.SecurityAPIKeysList)
		r.Post("/security/api-keys", h.SecurityAPIKeysCreate)
		r.Post("/security/api-keys/{keyID}/delete", h.SecurityAPIKeysDelete)
		r.Post("/security/api-keys/cleanup", h.SecurityAPIKeysCleanup)

		r.Get("/storage", h.StorageHome)
		r.Get("/storage/credentials", h.StorageCredentialsList)
		r.Get("/storage/credentials/new", h.StorageCredentialsNew)
		r.Post("/storage/credentials", h.StorageCredentialsCreate)
		r.Get("/storage/credentials/{credentialName}", h.StorageCredentialsDetail)
		r.Get("/storage/credentials/{credentialName}/edit", h.StorageCredentialsEdit)
		r.Post("/storage/credentials/{credentialName}/update", h.StorageCredentialsUpdate)
		r.Post("/storage/credentials/{credentialName}/delete", h.StorageCredentialsDelete)
		r.Get("/storage/locations", h.StorageLocationsList)
		r.Get("/storage/locations/new", h.StorageLocationsNew)
		r.Post("/storage/locations", h.StorageLocationsCreate)
		r.Get("/storage/locations/{locationName}", h.StorageLocationsDetail)
		r.Get("/storage/locations/{locationName}/edit", h.StorageLocationsEdit)
		r.Post("/storage/locations/{locationName}/update", h.StorageLocationsUpdate)
		r.Post("/storage/locations/{locationName}/delete", h.StorageLocationsDelete)
		r.Get("/storage/volumes", h.StorageVolumesList)
		r.Get("/storage/volumes/new", h.StorageVolumesNew)
		r.Post("/storage/volumes", h.StorageVolumesCreate)
		r.Get("/storage/volumes/{catalogName}/{schemaName}/{volumeName}", h.StorageVolumesDetail)
		r.Get("/storage/volumes/{catalogName}/{schemaName}/{volumeName}/edit", h.StorageVolumesEdit)
		r.Post("/storage/volumes/{catalogName}/{schemaName}/{volumeName}/update", h.StorageVolumesUpdate)
		r.Post("/storage/volumes/{catalogName}/{schemaName}/{volumeName}/delete", h.StorageVolumesDelete)

		r.Get("/compute", h.ComputeHome)
		r.Get("/compute/endpoints", h.ComputeEndpointsList)
		r.Get("/compute/endpoints/new", h.ComputeEndpointsNew)
		r.Post("/compute/endpoints", h.ComputeEndpointsCreate)
		r.Get("/compute/endpoints/{endpointName}", h.ComputeEndpointsDetail)
		r.Get("/compute/endpoints/{endpointName}/edit", h.ComputeEndpointsEdit)
		r.Post("/compute/endpoints/{endpointName}/update", h.ComputeEndpointsUpdate)
		r.Post("/compute/endpoints/{endpointName}/delete", h.ComputeEndpointsDelete)
		r.Post("/compute/endpoints/{endpointName}/assignments", h.ComputeAssignmentsCreate)
		r.Post("/compute/endpoints/{endpointName}/assignments/{assignmentID}/delete", h.ComputeAssignmentsDelete)

		r.Get("/governance", h.GovernanceHome)
		r.Get("/governance/search", h.GovernanceSearch)
		r.Get("/governance/tags", h.GovernanceTagsList)
		r.Post("/governance/tags", h.GovernanceTagsCreate)
		r.Post("/governance/tags/{tagID}/delete", h.GovernanceTagsDelete)
		r.Post("/governance/tag-assignments", h.GovernanceTagAssignmentsCreate)
		r.Post("/governance/tag-assignments/delete", h.GovernanceTagAssignmentsDelete)
		r.Get("/governance/audit-logs", h.GovernanceAuditLogs)
		r.Get("/governance/query-history", h.GovernanceQueryHistory)
		r.Get("/governance/manifest", h.GovernanceManifestPage)
		r.Post("/governance/manifest", h.GovernanceManifestCreate)
		r.Get("/governance/lineage", h.GovernanceLineage)
		r.Post("/governance/lineage/edges/{edgeID}/delete", h.GovernanceLineageDeleteEdge)
		r.Post("/governance/lineage/purge", h.GovernanceLineagePurge)

		r.Get("/assets", h.AssetsList)
		r.Get("/assets/{assetKey}", h.AssetsDetail)
		r.Post("/assets/{assetKey}/materialize", h.AssetMaterialize)
		r.Post("/assets/{assetKey}/backfills", h.AssetBackfillCreate)

		r.Get("/notebooks", h.NotebooksList)
		r.Get("/notebooks/git-repos", h.NotebookGitReposList)
		r.Get("/notebooks/git-repos/new", h.NotebookGitReposNew)
		r.Post("/notebooks/git-repos", h.NotebookGitReposCreate)
		r.Get("/notebooks/git-repos/{gitRepoID}", h.NotebookGitReposDetail)
		r.Post("/notebooks/git-repos/{gitRepoID}/delete", h.NotebookGitReposDelete)
		r.Post("/notebooks/git-repos/{gitRepoID}/sync", h.NotebookGitReposSync)
		r.Get("/notebooks/{notebookID}", h.NotebooksDetail)
		r.Get("/notebooks/{notebookID}/jobs", h.NotebookJobsList)
		r.Get("/notebooks/{notebookID}/jobs/{jobID}", h.NotebookJobsDetail)
		r.Get("/notebooks/new", h.NotebooksNew)
		r.Post("/notebooks", h.NotebooksCreate)
		r.Get("/notebooks/{notebookID}/edit", h.NotebooksEdit)
		r.Post("/notebooks/{notebookID}/update", h.NotebooksUpdate)
		r.Post("/notebooks/{notebookID}/delete", h.NotebooksDelete)
		r.Get("/notebooks/{notebookID}/cells/new", h.NotebookCellsNew)
		r.Post("/notebooks/{notebookID}/cells", h.NotebookCellsCreate)
		r.Get("/notebooks/{notebookID}/cells/{cellID}/edit", h.NotebookCellsEdit)
		r.Post("/notebooks/{notebookID}/cells/{cellID}/update", h.NotebookCellsUpdate)
		r.Post("/notebooks/{notebookID}/cells/{cellID}/run", h.NotebookCellsRun)
		r.Post("/notebooks/{notebookID}/cells/{cellID}/move", h.NotebookCellsMove)
		r.Get("/notebooks/{notebookID}/cells/{cellID}/download.csv", h.NotebookCellsDownloadCSV)
		r.Post("/notebooks/{notebookID}/cells/{cellID}/delete", h.NotebookCellsDelete)
		r.Post("/notebooks/{notebookID}/cells/reorder", h.NotebookCellsReorder)
		r.Post("/notebooks/{notebookID}/run-all", h.NotebookRunAll)
		r.Post("/notebooks/{notebookID}/run-all-async", h.NotebookRunAllAsync)

		r.Get("/macros", h.MacrosList)
		r.Get("/macros/{macroName}/diff", h.MacrosDiff)
		r.Get("/macros/{macroName}/impact", h.MacrosImpact)
		r.Get("/macros/{macroName}", h.MacrosDetail)
		r.Get("/macros/new", h.MacrosNew)
		r.Post("/macros", h.MacrosCreate)
		r.Get("/macros/{macroName}/edit", h.MacrosEdit)
		r.Post("/macros/{macroName}/update", h.MacrosUpdate)
		r.Post("/macros/{macroName}/delete", h.MacrosDelete)

		r.Get("/models", h.ModelsList)
		r.Get("/models/dag", h.ModelsDAG)
		r.Get("/models/runs", h.ModelRunsList)
		r.Get("/models/runs/{runID}", h.ModelRunsDetail)
		r.Get("/models/source-freshness", h.ModelSourceFreshnessPage)
		r.Post("/models/source-freshness", h.ModelSourceFreshnessCheck)
		r.Post("/models/promote", h.ModelPromoteNotebook)
		r.Get("/models/{projectName}/{modelName}", h.ModelsDetail)
		r.Get("/models/new", h.ModelsNew)
		r.Post("/models", h.ModelsCreate)
		r.Get("/models/{projectName}/{modelName}/edit", h.ModelsEdit)
		r.Post("/models/{projectName}/{modelName}/update", h.ModelsUpdate)
		r.Post("/models/{projectName}/{modelName}/delete", h.ModelsDelete)
		r.Get("/models/{projectName}/{modelName}/tests/new", h.ModelTestsNew)
		r.Post("/models/{projectName}/{modelName}/tests", h.ModelTestsCreate)
		r.Post("/models/{projectName}/{modelName}/tests/{testID}/delete", h.ModelTestsDelete)
		r.Post("/models/{projectName}/{modelName}/freshness", h.ModelFreshnessCheck)
		r.Post("/models/runs/trigger", h.ModelRunsTrigger)
		r.Post("/models/runs/{runID}/cancel", h.ModelRunsCancel)
		r.Post("/models/runs/manual-cancel", h.ModelRunsManualCancel)

		r.Get("/semantic", h.SemanticHome)
		r.Get("/semantic/models", h.SemanticModelsList)
		r.Get("/semantic/models/new", h.SemanticModelsNew)
		r.Post("/semantic/models", h.SemanticModelsCreate)
		r.Get("/semantic/models/{projectName}/{semanticModelName}", h.SemanticModelsDetail)
		r.Get("/semantic/models/{projectName}/{semanticModelName}/edit", h.SemanticModelsEdit)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/update", h.SemanticModelsUpdate)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/delete", h.SemanticModelsDelete)
		r.Get("/semantic/models/{projectName}/{semanticModelName}/metrics/{metricName}/edit", h.SemanticMetricsEdit)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/metrics/{metricName}/update", h.SemanticMetricsUpdate)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/metrics", h.SemanticMetricsCreate)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/metrics/{metricName}/delete", h.SemanticMetricsDelete)
		r.Get("/semantic/models/{projectName}/{semanticModelName}/pre-aggregations/{preAggName}/edit", h.SemanticPreAggregationsEdit)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/pre-aggregations/{preAggName}/update", h.SemanticPreAggregationsUpdate)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/pre-aggregations", h.SemanticPreAggregationsCreate)
		r.Post("/semantic/models/{projectName}/{semanticModelName}/pre-aggregations/{preAggName}/delete", h.SemanticPreAggregationsDelete)
		r.Get("/semantic/relationships", h.SemanticRelationshipsList)
		r.Get("/semantic/relationships/{relationshipName}/edit", h.SemanticRelationshipsEdit)
		r.Post("/semantic/relationships/{relationshipName}/update", h.SemanticRelationshipsUpdate)
		r.Post("/semantic/relationships", h.SemanticRelationshipsCreate)
		r.Post("/semantic/relationships/{relationshipName}/delete", h.SemanticRelationshipsDelete)
		r.Post("/semantic/query/explain", h.SemanticQueryExplain)
		r.Post("/semantic/query/run", h.SemanticQueryRun)
	})
}
