apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quackstack.fullname" . }}-config
  labels:
    {{- include "quackstack.labels" . | nindent 4 }}
data:
  DEPLOYMENT_PROFILE: {{ .Values.deploymentProfile | quote }}
  PLATFORM_PROVIDER: {{ .Values.platformProvider | quote }}
  CONTROL_DB_DRIVER: {{ .Values.controlDB.driver | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

