{{- if .Values.secrets.controlPlane.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.controlPlane.name }}
  labels:
    {{- include "quackstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.controlPlane.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

