// Package cuesqlgen renders CUE-authored query definitions into generated Go code.
package cuesqlgen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	cuesql "duck-demo/pkg/cue-sql"
)

// Generator emits the generated cue-sql store package for a source tree of query definitions.
type Generator struct {
	MigrationsDir string
	SourceDir     string
	OutputDir     string
}

// Run validates the configured query definitions and writes generated Go files to OutputDir.
func (g Generator) Run() error {
	catalog, err := LoadCatalog(g.MigrationsDir)
	if err != nil {
		return err
	}
	queries, err := LoadQueries(g.SourceDir)
	if err != nil {
		return err
	}
	if err := ValidateQueries(catalog, queries); err != nil {
		return err
	}

	if err := os.MkdirAll(g.OutputDir, 0o750); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	files := map[string][]byte{
		"db.gen.go":      mustFormat(generateDB()),
		"models.gen.go":  mustFormat(generateModels(catalog, queries)),
		"queries.gen.go": mustFormat(generateQueries(catalog, queries)),
	}
	for name, contents := range files {
		target := filepath.Join(g.OutputDir, name)
		if err := os.WriteFile(target, contents, 0o600); err != nil {
			return fmt.Errorf("write %s: %w", target, err)
		}
	}
	return nil
}

func generateDB() []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/cue-sql-gen. DO NOT EDIT.\n")
	buf.WriteString("package cuestore\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"database/sql\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString("type DBTX interface {\n")
	buf.WriteString("\tExecContext(context.Context, string, ...interface{}) (sql.Result, error)\n")
	buf.WriteString("\tPrepareContext(context.Context, string) (*sql.Stmt, error)\n")
	buf.WriteString("\tQueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)\n")
	buf.WriteString("\tQueryRowContext(context.Context, string, ...interface{}) *sql.Row\n")
	buf.WriteString("}\n\n")
	buf.WriteString("type Store struct {\n")
	buf.WriteString("\tdb DBTX\n")
	buf.WriteString("}\n\n")
	buf.WriteString("type Queries = Store\n\n")
	buf.WriteString("func New(db DBTX) *Store {\n")
	buf.WriteString("\treturn &Store{db: db}\n")
	buf.WriteString("}\n\n")
	buf.WriteString("func (s *Store) WithTx(tx *sql.Tx) *Store {\n")
	buf.WriteString("\treturn &Store{db: tx}\n")
	buf.WriteString("}\n")
	return buf.Bytes()
}

func generateModels(_ Catalog, queries []cuesql.Query) []byte {
	customRows := make(map[string][]cuesql.Field)
	for _, query := range queries {
		if query.Result.Row != "" {
			customRows[query.Result.Row] = query.Result.Fields
		}
	}

	customNames := make([]string, 0, len(customRows))
	for name := range customRows {
		customNames = append(customNames, name)
	}
	sort.Strings(customNames)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/cue-sql-gen. DO NOT EDIT.\n")
	buf.WriteString("package cuestore\n\n")
	imports := modelImports(customRows)
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range imports {
			buf.WriteString("\t\"" + imp + "\"\n")
		}
		buf.WriteString(")\n\n")
	}
	for _, rowName := range customNames {
		buf.WriteString("type " + rowName + " struct {\n")
		for _, field := range customRows[rowName] {
			buf.WriteString("\t" + fieldName(field.Name) + " " + field.Type + "\n")
		}
		buf.WriteString("}\n\n")
	}
	return buf.Bytes()
}

func generateQueries(catalog Catalog, queries []cuesql.Query) []byte {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/cue-sql-gen. DO NOT EDIT.\n")
	buf.WriteString("package cuestore\n\n")
	imports := queryImports(queries)
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for _, imp := range imports {
			buf.WriteString("\t\"" + imp + "\"\n")
		}
		buf.WriteString(")\n\n")
	}

	for _, query := range queries {
		if len(query.Params) > 0 {
			buf.WriteString("type " + query.Name + "Params struct {\n")
			for _, param := range query.Params {
				buf.WriteString("\t" + fieldName(param.Name) + " " + param.Type + "\n")
			}
			buf.WriteString("}\n\n")
		}

		rendered, err := cuesql.RenderSQLite(query, catalog)
		if err != nil {
			panic(err)
		}
		if !rendered.Dynamic {
			buf.WriteString("const " + lowerFirst(query.Name) + "SQL = `" + rendered.SQL + "`\n\n")
		} else {
			buf.WriteString(generateDynamicSQLBuilder(query, catalog))
		}
		buf.WriteString(generateMethod(query, catalog, rendered.Dynamic))
		buf.WriteString("\n")
	}
	return buf.Bytes()
}

func generateMethod(query cuesql.Query, catalog Catalog, dynamic bool) string {
	var buf bytes.Buffer
	resultType := methodResultType(query)
	paramsSignature, argRef, callArgs := methodArgs(query)

	buf.WriteString("func (s *Store) " + query.Name + "(ctx context.Context" + paramsSignature + ") " + resultType + " {\n")
	sqlRef := lowerFirst(query.Name) + "SQL"
	if dynamic {
		buf.WriteString("\tquerySQL, queryArgs := build" + query.Name + "SQL(" + argRef + ")\n")
		sqlRef = "querySQL"
		callArgs = "queryArgs..."
	}
	switch query.Kind {
	case cuesql.KindExec:
		buf.WriteString("\t_, err := s.db.ExecContext(ctx, " + sqlRef)
		if callArgs != "" {
			buf.WriteString(", " + callArgs)
		}
		buf.WriteString(")\n")
		buf.WriteString("\treturn err\n")
	case cuesql.KindExecResult:
		buf.WriteString("\treturn s.db.ExecContext(ctx, " + sqlRef)
		if callArgs != "" {
			buf.WriteString(", " + callArgs)
		}
		buf.WriteString(")\n")
	case cuesql.KindExecRows:
		buf.WriteString("\tresult, err := s.db.ExecContext(ctx, " + sqlRef)
		if callArgs != "" {
			buf.WriteString(", " + callArgs)
		}
		buf.WriteString(")\n")
		buf.WriteString("\tif err != nil {\n\t\treturn 0, err\n\t}\n")
		buf.WriteString("\treturn result.RowsAffected()\n")
	case cuesql.KindOne:
		buf.WriteString("\trow := s.db.QueryRowContext(ctx, " + sqlRef)
		if callArgs != "" {
			buf.WriteString(", " + callArgs)
		}
		buf.WriteString(")\n")
		if query.Result.Scalar != "" {
			buf.WriteString("\tvar value " + query.Result.Scalar + "\n")
			buf.WriteString("\terr := row.Scan(&value)\n")
			buf.WriteString("\treturn value, err\n")
			break
		}
		rowType := methodRowType(query)
		buf.WriteString("\tvar item " + rowType + "\n")
		buf.WriteString("\terr := row.Scan(\n")
		for _, target := range scanTargets(query, catalog, "&item.") {
			buf.WriteString("\t\t" + target + ",\n")
		}
		buf.WriteString("\t)\n")
		buf.WriteString("\treturn item, err\n")
	case cuesql.KindMany:
		buf.WriteString("\trows, err := s.db.QueryContext(ctx, " + sqlRef)
		if callArgs != "" {
			buf.WriteString(", " + callArgs)
		}
		buf.WriteString(")\n")
		buf.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		buf.WriteString("\tdefer rows.Close()\n")
		rowType := methodRowType(query)
		buf.WriteString("\tvar items []" + rowType + "\n")
		buf.WriteString("\tfor rows.Next() {\n")
		buf.WriteString("\t\tvar item " + rowType + "\n")
		buf.WriteString("\t\tif err := rows.Scan(\n")
		for _, target := range scanTargets(query, catalog, "&item.") {
			buf.WriteString("\t\t\t" + target + ",\n")
		}
		buf.WriteString("\t\t); err != nil {\n\t\t\treturn nil, err\n\t\t}\n")
		buf.WriteString("\t\titems = append(items, item)\n")
		buf.WriteString("\t}\n")
		buf.WriteString("\tif err := rows.Close(); err != nil {\n\t\treturn nil, err\n\t}\n")
		buf.WriteString("\tif err := rows.Err(); err != nil {\n\t\treturn nil, err\n\t}\n")
		buf.WriteString("\treturn items, nil\n")
	}
	buf.WriteString("}\n")
	return buf.String()
}

func generateDynamicSQLBuilder(query cuesql.Query, catalog Catalog) string {
	if query.Select == nil {
		panic("dynamic generation currently only supports SELECT queries")
	}
	stmt := query.Select
	columns := stmt.Columns
	if len(columns) == 0 {
		tableColumns, err := catalog.ColumnsForTable(query.Result.Table)
		if err != nil {
			panic(err)
		}
		qualifier := stmt.From
		if stmt.Alias != "" {
			qualifier = stmt.Alias
		}
		for _, name := range tableColumns {
			columns = append(columns, cuesql.Column{Expr: qualifier + "." + name})
		}
	}

	var buf bytes.Buffer
	buf.WriteString("func build" + query.Name + "SQL(arg " + query.Name + "Params) (string, []any) {\n")
	buf.WriteString("\tvar builder strings.Builder\n")
	buf.WriteString("\targs := make([]any, 0, " + fmt.Sprintf("%d", len(query.Params)) + ")\n")
	buf.WriteString("\tbuilder.WriteString(\"SELECT ")
	if stmt.Distinct {
		buf.WriteString("DISTINCT ")
	}
	buf.WriteString(escapeQuoted(cuesql.JoinColumns(columns)))
	buf.WriteString("\\nFROM " + escapeQuoted(stmt.From))
	if stmt.Alias != "" {
		buf.WriteString(" " + escapeQuoted(stmt.Alias))
	}
	for _, join := range stmt.Joins {
		joinType := strings.TrimSpace(join.Type)
		if joinType == "" {
			joinType = "JOIN"
		}
		buf.WriteString("\\n" + escapeQuoted(joinType+" "+join.Table))
		if join.Alias != "" {
			buf.WriteString(" " + escapeQuoted(join.Alias))
		}
		buf.WriteString(" ON " + escapeQuoted(join.On))
	}
	buf.WriteString("\")\n")
	buf.WriteString("\twhere := make([]string, 0, " + fmt.Sprintf("%d", len(stmt.Where)) + ")\n")
	for _, predicate := range stmt.Where {
		if predicate.RawSQL != "" {
			buf.WriteString("\twhere = append(where, \"" + escapeQuoted(predicate.RawSQL) + "\")\n")
			continue
		}
		if predicate.Optional || predicate.Slice {
			field := "arg." + fieldName(predicate.Param)
			lhs := predicate.Column
			if lhs == "" {
				lhs = predicate.Expr
			}
			if predicate.Slice {
				if predicate.Optional {
					buf.WriteString("\tif len(" + field + ") > 0 {\n")
				} else {
					buf.WriteString("\tif len(" + field + ") == 0 {\n\t\twhere = append(where, \"1 = 0\")\n\t} else {\n")
				}
				buf.WriteString("\t\tplaceholders := make([]string, len(" + field + "))\n")
				buf.WriteString("\t\tfor i, value := range " + field + " {\n")
				buf.WriteString("\t\t\tplaceholders[i] = \"?\"\n")
				buf.WriteString("\t\t\targs = append(args, value)\n")
				buf.WriteString("\t\t}\n")
				buf.WriteString("\t\twhere = append(where, \"" + escapeQuoted(lhs) + " IN (\"+strings.Join(placeholders, \", \")+\")\")\n")
				buf.WriteString("\t}\n")
				continue
			}
			buf.WriteString("\tif " + presentExpr(typeForParam(query, predicate.Param), field) + " {\n")
			buf.WriteString("\t\twhere = append(where, \"" + escapeQuoted(lhs+" "+predicate.Op+" ?") + "\")\n")
			buf.WriteString("\t\targs = append(args, " + field + ")\n")
			buf.WriteString("\t}\n")
			continue
		}
		buf.WriteString("\twhere = append(where, \"" + escapeQuoted(mustPredicateSQL(predicate)) + "\")\n")
		buf.WriteString("\targs = append(args, arg." + fieldName(predicate.Param) + ")\n")
	}
	buf.WriteString("\tif len(where) > 0 {\n")
	buf.WriteString("\t\tbuilder.WriteString(\"\\nWHERE \")\n")
	buf.WriteString("\t\tbuilder.WriteString(strings.Join(where, \"\\n  AND \"))\n")
	buf.WriteString("\t}\n")
	if len(stmt.OrderBy) > 0 {
		buf.WriteString("\tbuilder.WriteString(\"\\nORDER BY " + escapeQuoted(cuesql.JoinOrderBy(stmt.OrderBy)) + "\")\n")
	}
	if stmt.LimitParam != "" {
		buf.WriteString("\tbuilder.WriteString(\"\\nLIMIT ?\")\n")
		buf.WriteString("\targs = append(args, arg." + fieldName(stmt.LimitParam) + ")\n")
	}
	if stmt.OffsetParam != "" {
		buf.WriteString("\tbuilder.WriteString(\" OFFSET ?\")\n")
		buf.WriteString("\targs = append(args, arg." + fieldName(stmt.OffsetParam) + ")\n")
	}
	buf.WriteString("\treturn builder.String(), args\n")
	buf.WriteString("}\n\n")
	return buf.String()
}

func methodArgs(query cuesql.Query) (signature string, argRef string, callArgs string) {
	if len(query.Params) == 0 {
		return "", "", ""
	}
	if query.Select != nil {
		hasDynamic := false
		for _, predicate := range query.Select.Where {
			if predicate.Optional || predicate.Slice {
				hasDynamic = true
				break
			}
		}
		if hasDynamic {
			return ", arg " + query.Name + "Params", "arg", ""
		}
	}

	mode := query.ParamMode
	if mode == "" {
		if len(query.Params) == 1 {
			mode = "single"
		} else {
			mode = "struct"
		}
	}

	args := callArgExprs(query)
	switch mode {
	case "single":
		param := query.Params[0]
		return ", " + param.Name + " " + param.Type, param.Name, strings.Join(args, ", ")
	case "struct":
		return ", arg " + query.Name + "Params", "arg", strings.Join(args, ", ")
	default:
		panic("unsupported param mode: " + mode)
	}
}

func methodResultType(query cuesql.Query) string {
	switch query.Kind {
	case cuesql.KindExec:
		return "error"
	case cuesql.KindExecResult:
		return "(sql.Result, error)"
	case cuesql.KindExecRows:
		return "(int64, error)"
	case cuesql.KindOne:
		if query.Result.Scalar != "" {
			return "(" + query.Result.Scalar + ", error)"
		}
		return "(" + methodRowType(query) + ", error)"
	case cuesql.KindMany:
		return "([]" + methodRowType(query) + ", error)"
	default:
		return ""
	}
}

func methodRowType(query cuesql.Query) string {
	if query.Result.Row != "" {
		return query.Result.Row
	}
	if query.Result.Table != "" {
		return structNameForTable(query.Result.Table)
	}
	panic("query missing row type")
}

func scanTargets(query cuesql.Query, catalog Catalog, prefix string) []string {
	if query.Result.Row != "" {
		targets := make([]string, 0, len(query.Result.Fields))
		for _, field := range query.Result.Fields {
			targets = append(targets, prefix+fieldName(field.Name))
		}
		return targets
	}
	table := catalog.Tables[query.Result.Table]
	targets := make([]string, 0, len(table.Columns))
	for _, column := range table.Columns {
		targets = append(targets, prefix+camel(column.Name))
	}
	return targets
}

func queryImports(queries []cuesql.Query) []string {
	imports := map[string]struct{}{
		"context":      {},
		"database/sql": {},
	}
	for _, query := range queries {
		for _, param := range query.Params {
			if strings.HasPrefix(param.Type, "sql.") {
				imports["database/sql"] = struct{}{}
			}
			if strings.HasPrefix(param.Type, "time.") {
				imports["time"] = struct{}{}
			}
		}
		if query.Select != nil {
			for _, predicate := range query.Select.Where {
				if predicate.Optional || predicate.Slice {
					imports["strings"] = struct{}{}
				}
			}
		}
	}
	return sortedKeys(imports)
}

func modelImports(customRows map[string][]cuesql.Field) []string {
	imports := map[string]struct{}{}
	for _, fields := range customRows {
		for _, field := range fields {
			if strings.HasPrefix(field.Type, "sql.") {
				imports["database/sql"] = struct{}{}
			}
			if strings.HasPrefix(field.Type, "time.") {
				imports["time"] = struct{}{}
			}
		}
	}
	return sortedKeys(imports)
}

func callArgExprs(query cuesql.Query) []string {
	if len(query.Params) == 0 {
		return nil
	}
	if query.Raw != nil && len(query.Raw.Bind) > 0 {
		args := make([]string, 0, len(query.Raw.Bind))
		for _, name := range query.Raw.Bind {
			args = append(args, paramExpr(query, name))
		}
		return args
	}
	args := make([]string, 0, len(query.Params))
	for _, param := range query.Params {
		args = append(args, paramExpr(query, param.Name))
	}
	return args
}

func paramExpr(query cuesql.Query, name string) string {
	mode := query.ParamMode
	if mode == "" {
		if len(query.Params) == 1 {
			mode = "single"
		} else {
			mode = "struct"
		}
	}
	if mode == "single" {
		return name
	}
	return "arg." + fieldName(name)
}

func structNameForTable(tableName string) string {
	name := camel(tableName)
	switch {
	case strings.HasSuffix(name, "ies"):
		return strings.TrimSuffix(name, "ies") + "y"
	case strings.HasSuffix(name, "s"):
		return strings.TrimSuffix(name, "s")
	default:
		return name
	}
}

func camel(input string) string {
	parts := strings.FieldsFunc(input, func(r rune) bool {
		return r == '_' || r == '-' || r == ' '
	})
	for i, part := range parts {
		if part == "" {
			continue
		}
		if strings.EqualFold(part, "id") {
			parts[i] = "ID"
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func fieldName(input string) string {
	if input == "" {
		return ""
	}
	if strings.ToUpper(input[:1]) == input[:1] {
		return input
	}
	return camel(input)
}

func lowerFirst(input string) string {
	if input == "" {
		return input
	}
	return strings.ToLower(input[:1]) + input[1:]
}

func presentExpr(goType, field string) string {
	switch {
	case strings.HasPrefix(goType, "[]"):
		return "len(" + field + ") > 0"
	case strings.HasPrefix(goType, "*"):
		return field + " != nil"
	case strings.HasPrefix(goType, "sql.Null"):
		return field + ".Valid"
	case goType == "string":
		return field + " != \"\""
	default:
		return field + " != 0"
	}
}

func typeForParam(query cuesql.Query, name string) string {
	for _, param := range query.Params {
		if param.Name == name {
			return param.Type
		}
	}
	return ""
}

func mustPredicateSQL(predicate cuesql.Predicate) string {
	sqlPart, err := cuesql.RenderPredicateSQL(predicate)
	if err != nil {
		panic(err)
	}
	return sqlPart
}

func escapeQuoted(input string) string {
	return strings.ReplaceAll(input, "\"", "\\\"")
}

func sortedKeys(values map[string]struct{}) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func mustFormat(contents []byte) []byte {
	formatted, err := format.Source(contents)
	if err != nil {
		panic(fmt.Sprintf("format generated code: %v\n%s", err, contents))
	}
	return formatted
}
